[millennium-hieroglyph]
id = 900000000
template = "artwork"
name = "Millennium Hieroglyph"
strings = [
    "Mulligan?",
    "Place field?",
    "Perform Destiny Draw?",
    "Perform Destiny Excavate?",
]

[obelisk]
id = 900000001
alias = 10000000
rarity = "gold"
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|Obelisk the Tormentor}
{EGYPTIAN_EFFECT} \
Once per turn, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls, \
    also inflict damage to your opponent equal to this card's ATK. \
    Cannot be activated as Chain Link 2 or higher. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn, while a monster with Divine Hierarchy 2 or more on the field (Quick Effect): \
    You can Tribute 2 other monsters; \
    once during this turn, if this card battles an opponent's monster, \
    it gains ∞ ATK during the damage calculation only. \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & Inflict damage",
    "Gain ∞ ATK for 1 attack",
]

[osiris]
id = 900000002
alias = 10000020
rarity = "gold"
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
{EGYPTIAN_EFFECT} \
This card's original ATK/DEF are equal to the number of cards in your hand x 1000. \
If a monster(s) is Normal or Special Summoned to your opponent's field, \
    while this card is able to attack: \
    Choose that monster(s) as Target; it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK has been reduced to 0 as a result, destroy it. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[ra]
id = 900000003
alias = 10000010
rarity = "gold"
name = "Sun Divine Dragon of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
{EGYPTIAN_EFFECT} \
This card's original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field. \
While this card is able to attack, you can pay 1000 LP; destroy 1 monster on the field. \
Once while face-up on the field: You can pay LP so that you only have 1 left; \
    this card become Fusion Monster and gains ATK/DEF become equal to the amount of LP paid, \
    also any increase in LP is changed to increase it's ATK/DEF instead. \
    If your "De-Fusion" targets this Fusion Monster, apply these effect instead, \
    "that target loses its above effects, cannot activate its effects, \
    its ATK/DEF become 0, and if it do, its controller gains LP equal to that lost ATK". \
    Cards and effects cannot be activated in response to the above effects' activation. \
    You can also use this effect when this card is Summoned. \
While this card was Special Summoned, it gains the following effects. \
    This card must be become Fusion Monster by its own effect to gain, to activate, and to resolve the following effects.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated. \
● Once per turn, when an attack is declared involving this card: \
    You can Tribute any number of other face-up monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, until the end of this turn.
"""
strings = [
    "De-fuse from \"The Winged Dragon of Ra\"",
    "Destroy 1 monster on the field",
    "Life Point Transfer",
    "Tribute other monsters to gain ATK",
]

[ra-sphere]
id = 900000004
alias = 10000080
rarity = "gold"
name = "Sun Divine Dragon of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
If your "The Winged Dragon of Ra" is Normal Summoned to your field, \
    its original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field, \
    or your opponent's field, Dimension Change it to this card with the same Divine Hierarchy. \
Control and battle position of it cannot change by card effects. \
Cannot be Tributed, or used as material for an Summon. \
Unaffected by other cards' effects, except for cards with the equal or higher Divine Hierarchy. \
    This effect cannot be negated. \
Cannot attack. \
Neither player can target it for attacks or by card effects, \
    but does not prevent your opponent from attacking you directly. \
Once per turn, except the turn this card is Dimension Changed: \
    The turn player can reveal 1 "Ancient Chant" from everywhere; \
    Dimension Change this card to the material monster with the same Divine Hierarchy in any face-up position, \
    and if they do, its original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field, or 4000. \
    This effect's activation cannot be negated. \
    The owner no need to reveal. \
"""
strings = ["Change to Battle Mode"]

[ra-phoenix]
id = 900000005
alias = 10000090
rarity = "gold"
name = "Sun Divine Dragon of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
If "The Winged Dragon of Ra" is Special Summoned from the GY to your field, \
    you can Dimension Change it to this card with the same Divine Hierarchy. \
If "The Winged Dragon of Ra" you control would be destroyed by its own effect, \
    Dimension Change it to this card with the same Divine Hierarchy instead, \
    and this card's original ATK/DEF become the same as that monster's ATK/DEF had on the field. \
Control and battle position of it cannot change by card effects. \
Cannot be Tributed, or used as material for an Summon. \
Unaffected by other cards' effects, \
    and cannot be destroyed by battle, also you take no battle damage from that battle, \
    except for monsters with the higher Divine Hierarchy. \
    This effect cannot be negated. \
Cannot attack, except by its own effect. \
Once per Chain, while this card is in Attack Position, except the End Phase (Quick Effect): \
    You can pay 1000 LP, then choose 1 monster your opponent control as Target; \
    this card attacks it, and perform damage calculation, \
    after that, send the targeted monster to the GY, ignoring card effects. \
During the End Phase, \
    Dimension Change this card to 1 "The Winged Dragon of Ra - Sphere Mode" \
    with the same Divine Hierarchy (transfer this card's materials to that monster). \
    If you cannot, send this card to the GY. \
"""
strings = [
    "Select the form",
    "Battle Mode",
    "Phoenix Mode",
    "Perform attack",
    "Turn into Sphere Mode or to the GY",
]

[dreadroot]
id = 900000006
alias = 62180201
frame-path = "frame/black.png"
rarity = "gold"
name = "The Wicked Deity Dreadroot"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|The Wicked Dreadroot}
{EGYPTIAN_EFFECT} \
The ATK/DEF of all other monsters on the field are halved, \
    except monsters with the same or higher Divine Hierarchy. \
If this card attacks, your opponent cannot activate monster effects until the end of the Damage Step. \
"""
strings = []

[eraser]
id = 900000007
alias = 57793869
frame-path = "frame/black.png"
rarity = "gold"
name = "The Wicked Deity Eraser"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|1|The Wicked Eraser}
{EGYPTIAN_EFFECT} \
This card's original ATK/DEF are equal to the number of cards in your opponent controls x 1000. \
Once per turn: You can destroy this card. \
If this face-up card is sent from the field to the GY, send all cards on the field to the GY. \
"""
strings = ["Destroy itself"]

[avatar]
id = 900000008
alias = 21208154
frame-path = "frame/black.png"
rarity = "gold"
name = "The Wicked Deity Avatar"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|2|The Wicked Avatar}
{EGYPTIAN_EFFECT} \
This card's ATK/DEF are equal to the highest ATK on the field +100, except "The Wicked Avatar". \
Monsters' destruction by battle with this card cannot be negated. \
If this card is Normal Summoned, your opponent cannot activate Spell/Trap Cards \
    until the end of their 2nd turn after this effect's activation. \
"""
strings = ["Affected by \"{CARD_NAME}\": Cannot activate Spell/Trap Cards"]

[egyptian-god-slime-2]
id = 900000009
name = "Egyptian God Slime 2"
type = "monster fusion effect"
attribute = "water"
race = "aqua"
level = 10
atk = 2000
def = 2000
effect = """\
1 Aqua monster + 1 Level 10 WATER monster
Must first be either Fusion Summoned, or Special Summoned from your Extra Deck by Tributing 1 Level 10 Aqua monster with 0 ATK. \
This card can be treated as 1 or 3 Tributes for the Tribute Summon of a monster. \
Cannot be destroyed by battle. \
Your opponent's monsters with less ATK than this card cannot attack, also they cannot activate their effects. \
"""
strings = []

[egyptian-god-slime-3]
id = 900000010
name = "Egyptian God Slime 3"
type = "monster fusion effect"
attribute = "water"
race = "aqua"
level = 10
atk = 3300
def = 1800
effect = """\
1 Aqua monster + 1 Level 10 WATER monster
Must first be either Fusion Summoned, or Special Summoned from your Extra Deck by Tributing 1 Level 10 Aqua monster with 0 ATK. \
This card can be treated as 1 or 3 Tributes for the Tribute Summon of a monster. \
Cannot be destroyed by battle. \
You take no effect damage. \
"""
strings = []

[the-descent-sun-god]
id = 900000011
name = "The Descent Sun God"
type = "spell"
effect = """\
The activation of this card, or its effects, cannot be negated, nor can its effects be negated. \
Tribute 3 monsters on your field or your opponent's, and if you do, \
    Special Summon 1 "The Winged Dragon of Ra" from your hand or Deck, ignoring its Summoning conditions, \
    its original ATK/DEF become the combined ATK/DEF of the monsters Tributed had on the field. \
    If you Tributed monsters on your opponent's field, it cannot attack this turn. \
If this card is in your GY: \
    You can target 1 "The Winged Dragon of Ra" or 1 card that mentions it \
    that is banished, or in your GY, except "{CARD_NAME}"; \
    add this card to your hand, and if you do, \
    shuffle that card into the Deck. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Tribute your monsters", "Tribute your opponent's monsters"]

[deity-evolution]
id = 900000012
name = "Deity Evolution"
type = "spell quick-play"
effect = """\
The activation of this card, or its effects, cannot be negated, nor can its effects be negated. \
All face-up monsters with Divine Hierarchy you control that not affected by "{CARD_NAME}" \
    gain 1000 ATK/DEF, their Divine Hierarchy is increased by 1, \
    and their effects cannot be negated, \
    ignoring card effects. \
During your Main Phase, if this card is in your GY and you control a original Divine-Beast monster: \
    You can discard 1 Spell; Set this card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = []
