[millennium-hieroglyph]
id = 900000000
template = "artwork"
name = "Millennium Hieroglyph"
strings = ["Mulligan?", "Place field?", "Perform Destiny Draw?"]

[obelisk]
id = 900000001
alias = 10000000
rarity = "gold"
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|Obelisk the Tormentor}
{EGYPTIAN_EFFECT} \
Once per turn, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls, \
    also inflict damage to your opponent equal to this card's ATK. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn, while the total monster's Divine Hierarchy on the field are 3 or more (Quick Effect): \
    You can Tribute 2 other monsters; \
    once during this turn, if this card battles an opponent's monster, \
    it gains ∞ ATK during the damage calculation only. \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & Inflict damage",
    "Gain ∞ ATK for 1 attack",
]

[osiris]
id = 900000002
alias = 10000020
rarity = "gold"
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
{EGYPTIAN_EFFECT} \
This card's original ATK/DEF are equal to the number of cards in your hand x X000. \
    (X is its Divine Hierarchy). \
If a monster(s) is Normal or Special Summoned to your opponent's field, \
    while this card is able to attack: \
    Choose that monster(s) as Target; it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK has been reduced to 0 as a result, destroy it. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[ra]
id = 900000003
alias = 10000010
rarity = "gold"
name = "Sun Divine Dragon of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
{EGYPTIAN_EFFECT} \
This card's original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field. \
While this card is able to attack, you can pay 1000 LP, then choose 1 monster on the field as Target; destroy it. \
Once while face-up on the field: You can pay LP so that you only have 1 left; \
    this card become Fusion Monster and gains ATK/DEF become equal to the amount of LP paid, \
    also any increase in LP is changed to increase it's ATK/DEF instead. \
    If your "De-Fusion" targets this Fusion Monster, apply these effect instead, \
    "that target loses its above effects, cannot activate its effects, \
    its ATK/DEF become 0, and if it do, its controller gains LP equal to that lost ATK". \
    Cards and effects cannot be activated in response to the above effects' activation. \
    You can also use this effect when this card is Summoned. \
While this card was Special Summoned, it gains the following effects. \
    This card must be become Fusion Monster by its own effect to gain, to activate, and to resolve the following effects.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
● Once per turn, when an attack is declared involving this card: You can Tribute any number of other face-up monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, until the end of this turn.
● At the end of the Damage Step, when this card attacks an opponent's monster, \
    send all monsters your opponent controls to the GY.
"""
strings = [
    "De-fuse from \"The Winged Dragon of Ra\"",
    "Destroy 1 monster on the field",
    "Life Point Transfer",
    "Tribute other monsters to gain ATK",
    "Send your opponent's monster to the GY",
]

[ra-sphere]
id = 900000004
alias = 10000080
rarity = "gold"
name = "Sun Divine Dragon of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
While this card is in Dimension Zone: \
    You can Normal Summon "The Winged Dragon of Ra" to your opponent's field. \
If your "The Winged Dragon of Ra" is Normal Summoned to your field, \
    its original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field, \
    or your opponent's field, Dimension Change it to this card with the same Divine Hierarchy. \
Control of it cannot switch. \
Cannot be Tributed, or used as a material for an Summon. \
Unaffected by other cards' effects, except for cards with the higher Divine Hierarchy. \
    This effect cannot be negated. \
Cannot attack. \
Neither player can target it for attacks or by card effects, \
    but does not prevent your opponent from attacking you directly. \
Once per turn, except the turn this card is Dimension Changed: \
    The turn player can reveal 1 "Ancient Chant" from everywhere; \
    Dimension Change this card to the material monster with the same Divine Hierarchy in any face-up position, \
    and if they do, its original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field, or 4000/4000. \
    This effect's activation cannot be negated. \
    The owner no need to reveal. \
"""
strings = [
    "Summon to your field",
    "Summon to opponent's field",
    "Change to Battle Mode",
    "Reveal \"Ancient Chant\"?",
]

[ra-phoenix]
id = 900000005
alias = 10000090
rarity = "gold"
name = "Sun Divine Dragon of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
If "The Winged Dragon of Ra" is Special Summoned from the GY to your field, \
    you can Dimension Change it to this card with the same Divine Hierarchy, \
If "The Winged Dragon of Ra" you control would be destroyed by its own effect, \
    Dimension Change it to this card with the same Divine Hierarchy instead, \
    and its original ATK/DEF become the same as that monster's ATK/DEF had on the field. \
Control of it cannot switch. \
Cannot be Tributed, or used as a material for an Summon. \
Unaffected by other cards' effects, \
    and cannot be destroyed by battle, also you take no battle damage from that battle, \
    except for monsters with the higher Divine Hierarchy. \
    This effect cannot be negated. \
Cannot attack, except by its own effect. \
Once per Chain, while this card is in Attack Position, except the End Phase (Quick Effect): \
    You can pay 1000 LP, then choose 1 monster your opponent control as Target; \
    this card attacks it, and perform damage calculation, \
    after that, send the targeted monster to the GY, ignoring card effects. \
During the End Phase, \
    Dimension Change this card to 1 "The Winged Dragon of Ra - Sphere Mode" \
    with the same Divine Hierarchy (transfer this card's materials to that monster), \
    or send it to the GY. \
"""
strings = [
    "Select the form",
    "Battle Mode",
    "Phoenix Mode",
    "Perform attack",
    "Turn into Sphere Mode or to the GY",
]
