[millennium-hieroglyph]
id = 900000000
template = "artwork"
name = "Millennium Hieroglyph"
strings = ["Mulligan?", "Place field?", "Perform Destiny Draw?"]

[obelisk]
id = 900000001
alias = 10000000
rarity = "gold"
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|Obelisk the Tormentor}
{EGYPTIAN_EFFECT} \
Once per turn, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls, \
    also inflict damage to your opponent equal to this card's ATK. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn, while the total monster's Divine Hierarchy on the field are 3 or more (Quick Effect): \
    You can Tribute 2 other monsters; \
    once during this turn, if this card battles an opponent's monster, \
    it gains ∞ ATK during the damage calculation only. \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & inflict damage",
    "Gain ∞ ATK for 1 attack",
]

[osiris]
id = 900000002
alias = 10000020
rarity = "gold"
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
{EGYPTIAN_EFFECT} \
This card's original ATK and DEF are each equal to the number of cards in your hand x X000. \
    (X is this card's Divine Hierarchy). \
If a monster(s) is Normal or Special Summoned to your opponent's field, \
    while this card is able to attack: \
    Choose that monster(s) as Target; it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK has been reduced to 0 as a result, destroy it. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[ra]
id = 900000003
alias = 10000010
rarity = "gold"
name = "Sun Divine Dragon of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
${EGYPTIAN_EFFECT} \
You can pay 1000 LP, then choose 1 monster on the field as Target; destroy it. \
Once while face-up on the field: You can pay LP so that you only have 100 left; \
    this card become Fusion Monster and gains original ATK/DEF become equal to the amount of LP paid, \
    also any increase in LP is changed to increase it's original ATK/DEF instead. \
    If your "De-Fusion" targets this Fusion Monster, apply these effect instead, \
    "that target loses its above effects, cannot activate its effects, \
    its ATK/DEF become 0, and if it do, its controller gains LP equal to that lost ATK, \
    and also send it to the GY during the End Phase, ignoring card effects". \
    Cards and effects cannot be activated in response to the above effects' activation. \
    You can also use this effect when this card is Summoned. \
"""
strings = ["Destroy 1 monster on the field", "Life Point Transfer"]
