[millennium-hieroglyph]
id = 900000000
template = "artwork"
name = "Millennium Hieroglyph"
strings = [
    "Mulligan?",
    "Place field?",
    "Perform Destiny Draw?",
    "Perform Destiny Excavate?",
]

[obelisk]
id = 900000001
alias = 10000000
rarity = "gold"
frame-path = "artwork/frame/obelisk.png"
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|Obelisk the Tormentor}
Cannot be Special Summoned, except by it's owner. \
{EGYPTIAN_EFFECT} \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & Inflict damage",
    "Gain ∞ ATK for 1 attack",
]

[dreadroot]
id = 900000006
alias = 62180201
frame-path = "artwork/frame/wicked.png"
rarity = "gold"
name = "The Wicked Deity Dreadroot"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = 4000
def = 4000
effect = """\
{HIERARCHY_ALIAS|1|The Wicked Dreadroot}
Cannot be Special Summoned. \
{EGYPTIAN_EFFECT} \
"""
strings = []
