HIERARCHY = """(This card's base Divine Hierarchy is {0}.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""
HIERARCHY_CUSTOM = """(This card's base Divine Hierarchy is {0}{1}.)"""

EGYPTIAN_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN_EFFECT = """\
This card's effects cannot be negated by Spell/Trap effects. \
Control of it cannot switch. \
Cannot be Tributed, or used as a material for an Summon by your opponent. \
Cannot change battle position, or leave the field by other cards' effects, \
    except for monsters with the higher Divine Hierarchy. \
Unaffected by your opponent's monster effects with the lower Divine Hierarchy. \
Other cards' effects are only applied on it for 1 turn. \
"""
EGYPTIAN_SPSUMMON_EFFECT = """\
During the turn this card is Special Summoned from the GY, \
    it cannot attack, and send it to the GY during the End Phase. \
"""