HIERARCHY = """(This card's base Divine Hierarchy is {0}.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""
HIERARCHY_CUSTOM = """(This card's base Divine Hierarchy is {0}{1}.)"""

EGYPTIAN_EFFECT = """\
Cannot be Special Summoned, except by owner player. \
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated. \
Control and battle position of it cannot change by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Cannot be destroyed, also unaffected by other card effects that would make it leave the field, \
    except monsters with equal or higher Divine Hierarchy. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, \
    also you take no battle damage from that battle. \
Other card effects are only applied on it for 1 turn. \
During the turn it is Special Summoned from the GY, \
    it cannot attack (except by cards that mentions it), \
    also send it to the GY during the End Phase.\
"""

EGYPTIAN_EFFECT_1 = """\
{EGYPTIAN_EFFECT} \
The above effects cannot be negated.\
"""

EGYPTIAN_EFFECT_2 = """\
{EGYPTIAN_EFFECT} \
This card's effects cannot be negated.\
"""
