HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""

EGYPTIAN_EFFECT = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""