HIERARCHY = """(This card's base Divine Hierarchy is {0}.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""
HIERARCHY_CUSTOM = """(This card's base Divine Hierarchy is {0}{1}.)"""

EGYPTIAN_EFFECT = """\
Cannot be Special Summoned, except by its owner. \
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon and its effects cannot be negated. \
Control of this card cannot switch. \
Cannot change battle position by card effect. \
Cannot be Tributed, or used as a material for an Summon by your opponent. \
Cannot leave the field by other cards' activated effects, \
    except monsters with the higher Divine Hierarchy. \
Unaffected by your opponent's monster effects with the lower Divine Hierarchy. \
Other cards' effects are only applied on it for 1 turn. \
Cannot attack the turn it is Special Summoned. \
Once per turn, during the turn this card is Special Summoned from the GY, \
    send it to the GY during the End Phase.\
"""
