HIERARCHY = """(This card's base Divine Hierarchy is {0}.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""
HIERARCHY_CUSTOM = """(This card's base Divine Hierarchy is {0}{1}.)"""

EGYPTIAN_EFFECT = """\
Cannot be Special Summoned, except by its owner. \
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon and its effects cannot be negated. \
Control of it cannot switch. \
Cannot change battle position by card effect. \
Cannot be Tributed, or used as a material for an Summon by your opponent. \
Cannot leave the field by other cards' effects, except cards with the higher Divine Hierarchy. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, \
    also you take no battle damage from that battle. \
Other cards' effects are only applied on it for 1 turn. \
During the turn this card is Special Summoned from the GY, \
    send it to the GY during the End Phase. \
Cannot attack the turn it is Special Summoned\
"""