HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is {0}, and is always treated as "{1}".)"""

EGYPTIAN_EFFECT = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated. \
Control and battle position cannot be changed by card effects. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, \
    also you take no battle damage from that battle. \
Unaffected by other card effects that would make it leave the field, \
    except monster effects with higher Divine Hierarchy. \
Other card effects are only applied on it for 1 turn, \
    except cards that mentions it. \
The above effects cannot be negated.\
"""