[mausoleum-signer-dragons]
id = 900000300
name = "Mausoleum of the Signer Dragons"
type = "spell field"
effect = """
Special Summons of your Synchro Monsters cannot be negated. \
"""
strings = []

[cosmic-ultimaya-dragon]
id = 900000301
rarity = "gold"
name = "Cosmic Ultimaya Dragon"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 13
show-level = false
effect = """
(This card's original Level is always treated as 13.)
Cannot be Synchro Summoned. \
"""
strings = []
