[mausoleum-signer-dragons]
id = 900000300
name = "Mausoleum of the Signer Dragons"
type = "spell field"
effect = """
When this card is activated: You can place 1 Level 1 Dragon monster from your hand, Deck or GY on top of the Deck. \
Special Summons of your Dragon Synchro Monsters cannot be negated. \
Neither player can return your Dragon Synchro Monster from the field to the Extra Deck. \
If you Synchro Summon a Dragon Synchro Monster: You can draw 1 card. \
If a Dragon Synchro Monster(s) you control leaves the field by your card effect, or to activate the effect of your card: \
    You can Special Summon 1 of those monsters. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Place 1 Level 1 Dragon monster on top of the Deck?",
    "Draw 1 card",
    "Special Summon the leaved monster",
]

[ultimaya-cosmic-dragon]
id = 900000301
rarity = "gold"
name = "Ultimaya Cosmic Dragon"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 13
show-level = false
effect = """
(This card's original Level is always treated as 13.)
[Add "Majestic" version of your Signer Dragons to your Extra Deck.]
Cannot be Synchro Summoned. \
Must be Special Summoned (from your Extra Deck) by sending 2 Level 7 or higher Dragon Synchro Monsters you control with the same Level to the GY (1 Tuner and 1 non-Tuner). \
    This card's Special Summon cannot be negated. \
Cannot be Tributed, or used as a material for an Summon. \
Unaffected by other cards' effects. This effect cannot be negated. \
While you control another Synchro Monster, your opponent cannot target this card for attacks or by card effects. \
"""
strings = []

[ultimaya-stardust-dragon]
id = 900000302
set = "stardust"
name = "Ultimaya Stardust Dragon"
type = "monster synchro tuner effect"
attribute = "wind"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Stardust Dragon".)
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
When a card or effect is activated that would destroy a card(s) on the field (Quick Effect): \
    You can Tribute this card; negate the activation, and if you do, destroy it. \
    During the End Phase, if this effect was activated this turn (and was not negated), \
    Special Summon this card from your GY. \
While this card is in your GY, if a Dragon Synchro Monster(s) you control that used this card as Synchro Material \
    is destroyed by battle or card effect and sent to the GY or banished (Quick Effect): \
    You can return that monster to the Extra Deck, and if you do, Special Summon this card, \
    also it cannot be destroyed by battle this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Negate the activation"]

[ultimaya-red-archfiend-dragon]
id = 900000303
set = "red-dragon-archfiend"
name = "Ultimaya Red Archfiend Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Red Dragon Archfiend".)
Once per turn: You can destroy all face-up Attack Position monsters on the field \
    with ATK less than or equal to this card's (other than this card). \
After damage calculation, if this card attacked an opponent's Defense Position monster: \
    Destroy all Defense Position monsters your opponent controls. \
"""
strings = [
    "Destroy monster with ATK less than or equal to this card's",
    "Destroy all your opponent's defense position monsters",
]

[ultimaya-black-winged-dragon]
id = 900000304
name = "Ultimaya Black-Winged Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2800
def = 1600
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Black-Winged Dragon".)
If you would take damage from a card effect, place 1 Black Feather Counter on this card instead. \
If you take damage from an attack not involving this card, place 1 Black Feather Counter on this card. \
This card gains 100 ATK for each Black Feather Counter on it. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    the target loses 700 ATK for each Black Feather Counter on this card, \
    and if it does, remove all Black Feather Counters on this card \
    and inflict damage to your opponent equal to that lost ATK. \
    This is a Quick Effect if this card has 4 or more Black Feather Counter on it. \
"""
strings = ["Remove counter to low ATK and inflict damage"]

[ultimaya-black-rose-dragon]
id = 900000305
set = "rose-dragon"
name = "Ultimaya Black Rose Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 8
atk = 2400
def = 1800
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Black Rose Dragon".)
If this card is Summoned: You can destroy any number of cards you control, \
    and if you do, destroy the same number of cards your opponent controls. \
Once per turn: \
    You can target 1 Tuner that is banished or in your GY, and 1 face-up monster your opponent controls; \
    shuffle the first target into the Deck, and if you do, \
    the second target's ATK/DEF becomes half its current ATK/DEF until the End Phase. \
"""
strings = ["Destroy cards on the field", "Halve ATK/DEF of 1 monster"]

[ultimaya-ancient-fairy-dragon]
id = 900000306
name = "Ultimaya Ancient Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2100
def = 3000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Ancient Fairy Dragon".)
Once per turn, after resolving a Field Spell that was activated during your turn: \
    This card gain 1000 ATK until the end of your opponent's turn. \
Once per turn: You can destroy as many Field Spells on the field as possible, \
    and if you do, gain 1000 LP for each destroyed cards, \
    then you can add 1 Field Spell from your Deck or GY to your hand. \
"""
strings = ["Destroy Field Spells", "Add 1 Field Spell to your hand?"]

[ultimaya-life-stream-dragon]
id = 900000307
name = "Ultimaya Life Stream Dragon"
type = "monster synchro tuner effect"
attribute = "earth"
race = "dragon"
level = 8
atk = 2900
def = 2400
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Life Stream Dragon".)
If this card was Synchro Summoned using a Synchro Monster as material: You can make your LP become 4000. \
After this card is Special Summoned, you take no effect damage until the end of your opponent's turn. \
Once per turn: You can discard 1 Tuner; \
    add 1 Equip Spell from your Deck or GY to your hand. \
Once per turn: You can declare a Level from 1 to 12; \
    all other Synchro Monsters you currently control become that Level until the end of this turn, \
    also for the rest of this turn, you cannot Special Summon from the Extra Deck, except Dragon Synchro Monsters. \
"""
strings = [
    "Make your LP become 4000",
    "Take no effect damage",
    "Add 1 Equip Spell to your hand",
    "Change Level of other Synchro Monsters",
    "Cannot Special Summon from the Extra Deck, except Dragon Synchro Monsters",
]

[majestic-black-dragon]
id = 900000308
set = "majestic"
name = "Majestic Black Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 3900
def = 2600
effect = """
"Majestic Dragon" + "Black-Winged Dragon" + 1 non-Tuner monster
Each time another monster effect is activated, \
    place 1 Black Feather Counter on this card immediately after it resolves, \
    and if you do, inflict 700 damage to them. \
(Quick Effect): You can Tribute this card with 4 or more Black Feather Counters; \
    banish all cards your opponent controls. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, inflict damage to your opponent equal to the ATK of that target. \
{MAJESTIC_RETURN|Black-Winged Dragon} \
"""
strings = [
    "Tribute to banish your opponent cards",
    "Negate effect & inflict damage",
]

[majestic-rose-dragon]
id = 900000309
set = "majestic rose-dragon"
name = "Majestic Rose Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 10
atk = 3750
def = 2800
effect = """
"Majestic Dragon" + "Black Rose Dragon" + 1 non-Tuner monster
If this card is Synchro Summoned: You can banish all cards from your opponent's GY face-down. \
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects, and if you do, change its ATK and DEF to 0. \
    These changes last until the end of this turn. \
{MAJESTIC_RETURN|Black Rose Dragon} \
"""
strings = [
    "Banish all cards from your opponent's GY face-down",
    "Negate effect & make ATK/DEF become 0",
]

[majestic-fairy-dragon]
id = 900000310
set = "majestic"
name = "Majestic Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 10
atk = 3600
def = 4000
effect = """
"Majestic Dragon" + "Ancient Fairy Dragon" + 1 non-Tuner monster
This card gains ATK equal to the difference between your LP and your opponent's. \
Once per turn, during your Main Phase 1: \
    You can Special Summon 1 Level 4 or lower monster from your hand or in either GY. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, and if you do, gain LP equal to its ATK. \
{MAJESTIC_RETURN|Ancient Fairy Dragon} \
"""
strings = [
    "Special Summon 1 Level 4 or lower monster",
    "Negate effect & recover LP",
]

[majestic-life-dragon]
id = 900000311
set = "majestic"
name = "Majestic Life Dragon"
type = "monster synchro tuner effect"
attribute = "earth"
race = "dragon"
level = 10
atk = 3950
def = 3400
effect = """
"Majestic Dragon" + "Life Stream Dragon" + 1 non-Tuner monster
If this card is Special Summoned: \
    You can equip up to 3 Equip Spells with different names from your Deck and/or GY to this card, \
    and if you do, your opponent cannot target those cards with card effects, \
    also they cannot be destroyed by your opponent's card effects. \
Any effect that would inflict damage to you makes you gain that much LP, instead. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, you can change its battle position. \
{MAJESTIC_RETURN|Life Stream Dragon} \
"""
strings = [
    "Equip Spells to this card",
    "Negate effect & change position",
    "Change position?",
]

[cosmic-quasar-dragon]
id = 900000312
name = "Cosmic Quasar Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 12
atk = 4000
def = 4000
effect = """
1 Dragon Tuner Synchro Monster + 2+ non-Tuner Synchro Monsters
Must be Synchro Summoned. \
This card's Synchro Summon and its effects cannot be negated. \
After this card is Synchro Summoned, place Signer Counters on this card \
    equal to the number of Dragon Synchro Monsters used as its Synchro Material. \
Unaffected by other monsters' effects. \
When a card or effect is activated (Quick Effect):
    You can remove 1 Signer Counter from this card; \
    negate that effect, and if you do, destroy it. \
If this card attacks, your opponent cannot activate cards or effects until the end of the Damage Step, \
    also negate the effects of the battling monster during the Damage Step only. \
At the end of the Damage Step, if this card attacked, \
    you can remove 1 Signer Counter from this card, \
    and if you do, this card can attack gain. \
"""
strings = ["Negate the effect", "Attack again?"]

[shooting-stardust-dragon]
id = 900000313
set = "stardust"
name = "Shooting Stardust Dragon"
type = "monster synchro effect"
attribute = "wind"
race = "dragon"
level = 10
atk = 3300
def = 2500
effect = """
1 Tuner Synchro Monster + 1 non-Tuner Synchro Monster
(This card's name is also treated as "Shooting Star Dragon".)
Once per turn, during the Main Phase, you can (Quick Effect): Immediately after this effect resolves, \
    Synchro Summon this card from your Extra Deck using monsters you control, including "Stardust Dragon". \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
Once per turn: You can excavate the top 5 cards of your Deck, shuffle them back in, \
    also this card gains 1 additional attack each Battle Phase for every Tuner monsters excavated. \
Once per Chain, when a card or effect is activated that would destroy a card(s) on the field (Quick Effect): \
    You can negate that effect, and if you do, destroy it. \
Once per turn, during your opponent's turn, \
    when your opponent activates a card or effect, or when an opponent's monster declares an attack (Quick Effect): \
    You can banish this card, and if you do, you can negate 1 attack this turn from a monster your opponent controls. \
    During the next End Phase, Special Summon this card banished by this effect. \
"""
strings = [
    "Excavate Tuner to gain multi-attack",
    "Negate the effect",
    "Banish this card until the end phase",
    "Do you want negate the attack by effect of \"{CARD_NAME}\"?",
]

[shooting-star-synchron]
id = 900000314
set = "synchron"
name = "Shooting Star Synchron"
type = "monster synchro tuner effect"
attribute = "wind"
race = "machine"
level = 2
atk = 1500
def = 200
effect = """
1 Tuner + 1 non-Tuner monster
If this card is Special Summoned: You can draw 1 card. \
If you Special Summon a Dragon Synchro Monster while this card is in your GY \
    (except during the Damage Step, or when this card is used as a Synchro Material): \
    You can Special Summon this card in Defense Position, \
    also for the rest of this turn, you cannot Special Summon from the Extra Deck, except Synchro Monsters. \
You can only use each effect of "{CARD_NAME}" once per turn. \
A Synchro Monster that used this card as material is unaffected by your opponent's activated effects \
    during the turn it is Synchro Summoned. \
"""
strings = ["Cannot Special Summon from the Extra Deck, except Synchro Monsters"]
