[mausoleum-signer-dragons]
id = 900000300
rarity = "gold"
name = "Mausoleum of the Signer Dragons"
type = "spell field"
effect = """
Special Summons of your Synchro Monsters cannot be negated. \
"""
strings = []
