[mausoleum-signer-dragons]
id = 900000300
name = "Mausoleum of the Signer Dragons"
type = "spell field"
effect = """
Special Summons of your Dragon Synchro Monsters cannot be negated. \
Neither player can return your Dragon Synchro Monster from the field to the Extra Deck. \
"""
strings = []

[ultimaya-cosmic-dragon]
id = 900000301
rarity = "gold"
name = "Ultimaya Cosmic Dragon"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 13
show-level = false
effect = """
(This card's original Level is always treated as 13.)
[Add "Majestic" version of your Signer Dragons to your Extra Deck.]
Cannot be Synchro Summoned. \
Must be Special Summoned (from your Extra Deck) by sending 2 Level 7 or higher Dragon Synchro Monsters you control with the same Level to the GY (1 Tuner and 1 non-Tuner). \
    This card's Special Summon cannot be negated. \
Unaffected by other cards' effects. This effect cannot be negated. \
While you control another Synchro Monster, your opponent cannot target this card for attacks or by card effects. \
"""
strings = []

[majestic-black-dragon]
id = 900000302
set = "majestic"
name = "Majestic Black Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 3920
def = 2600
effect = """
"Majestic Dragon" + "Black-Winged Dragon" + 1 non-Tuner monster
{MAJESTIC_RETURN|Black-Winged Dragon} \
"""
strings = []

[majestic-rose-dragon]
id = 900000303
set = "majestic rose-dragon"
name = "Majestic Rose Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 10
atk = 3760
def = 2800
effect = """
"Majestic Dragon" + "Black Rose Dragon" + 1 non-Tuner monster
{MAJESTIC_RETURN|Black Rose Dragon} \
"""
strings = []

[majestic-fairy-dragon]
id = 900000304
set = "majestic"
name = "Majestic Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 10
atk = 3640
def = 4000
effect = """
"Majestic Dragon" + "Ancient Fairy Dragon" + 1 non-Tuner monster
{MAJESTIC_RETURN|Ancient Fairy Dragon} \
"""
strings = []

[majestic-life-dragon]
id = 900000305
set = "majestic"
name = "Majestic Life Dragon"
type = "monster synchro tuner effect"
attribute = "earth"
race = "dragon"
level = 10
atk = 3960
def = 3400
effect = """
"Majestic Dragon" + "Life Stream Dragon" + 1 non-Tuner monster
{MAJESTIC_RETURN|Life Stream Dragon} \
"""
strings = []

[ultimaya-stardust-dragon]
id = 900000306
set = "stardust"
name = "Ultimaya Stardust Dragon"
type = "monster synchro tuner effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Stardust Dragon".)
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
"""
strings = []

[ultimaya-red-archfiend-dragon]
id = 900000307
set = "red-dragon-archfiend"
name = "Ultimaya Red Archfiend Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Red Dragon Archfiend".)
"""
strings = []

[ultimaya-black-winged-dragon]
id = 900000308
name = "Ultimaya Black-Winged Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2800
def = 1600
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Black-Winged Dragon".)
"""
strings = []

[ultimaya-black-rose-dragon]
id = 900000309
set = "rose-dragon"
name = "Ultimaya Black Rose Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2400
def = 1800
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Black Rose Dragon".)
"""
strings = []

[ultimaya-ancient-fairy-dragon]
id = 900000310
name = "Ultimaya Ancient Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2100
def = 3000
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Ancient Fairy Dragon".)
"""
strings = []

[ultimaya-life-stream-dragon]
id = 900000311
name = "Ultimaya Life Stream Dragon"
type = "monster synchro tuner effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2900
def = 2400
effect = """
1 Tuner + 1+ non-Tuner monsters
(This card's name is also treated as "Life Stream Dragon".)
"""
strings = []

[assault-shooting-star-dragon]
id = 900000312
name = "Assault Shooting Star Dragon"
type = "monster synchro effect"
attribute = "wind"
race = "dragon"
level = 10
atk = 3300
def = 2500
effect = """
1 Tuner Synchro Monster + 1 "Stardust Dragon" or 1 non-Tuner Dragon Synchro Monster
(This card's name is also treated as "Shooting Star Dragon".)
Once per turn, during your opponent's turn, you can (Quick Effect): \
    Immediately after this effect resolves, Synchro Summon this card from your Extra Deck using monsters you control. \
"""
strings = []