[card.divine-hieroglyph]
id = 910000000
name = "Divine Hieroglyph"
type = "spell quick-play"
effect = """\
This card's activation and effect cannot be negated. \
Activate 1 of these effects; You can only activate 1 "Divine Hieroglyph" per turn.
● During the Main Phase: Immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster, \
    or, if you control 3 or more monsters with different names, \
    you can add 1 DIVINE monster from your Deck to your hand, then, \
    immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster. \
    When you do, you can Tribute a monster(s) your opponent controls, even though you do not control them.
● During your Main Phase or your opponent's Battle Phase: \
    Target 1 monster in either GY; Special Summon it, but send it to the GY during the End Phase. \
    You can also Special Summon "The Winged Dragon of Ra" with this effect, ignoring its Summoning conditions.
During your Draw Phase, instead of conducting your normal draw: \
    You can reveal 1 DIVINE monster in your hand; \
    add this card from your Deck or GY to your hand.

[ \
Add from Outside Dimension versions of your Divine-Beast Monsters. \
] \
"""
strings = [
    "Tribute Summon",
    "Special Summon",
    "Add 1 DIVINE monster",
    "Special Summoned by \"Divine Hieroglyph\"",
]

[card.palladium-magic]
id = 910000010
set = "palladium"
name = "Palladium Magic"
type = "spell quick-play"
effect = """\
Apply these effects, in sequence, depending on the monster you control. \
    If you meet 2 or more of these conditions, your opponent cannot activate cards or effects in response to this card's activation. \
    You can only activate 1 "Palladium Magic" per turn.
● Level 8 DARK Spellcaster "Chaos" Ritual Monster: This turn, any card sent to your opponent's GY is banished instead.
● "Dark Magician": Destroy All Spells and Traps your opponent controls.
● "Dark Magician Girl" monster: Destroy all monsters your opponent controls.
"""
strings = ["Card sent to the GY is banished instead"]

[card.palladium-oracles]
id = 410000013
set = "palladium"
name = "The Palladium Oracles"
type = "monster link effect"
attribute = "light"
race = "spellcaster"
link-arrows = "bottom-left bottom-right"
link-rating = 2
atk = 2800
effect = """\
(This card is also always treated as DARK monster.)
2 Level/Rank 6 or higher Spellcaster monsters, including 1 "Palladium" monster
This card gains effects of material monsters used to Link Summon this card. \
Once per turn, if a Spell/Trap Card or effect is activated (except during the Damage Step): \
    You can draw 1 card, \
    then if it was a Monster, you can Special Summon it, \
    or you can Set it, and if it was a Trap or Quick-Play Spell, you can activate it this turn. \
If this card leaves the field: \
    You can Special Summon all Link Materials from your hand, Deck, and/or GY, \
    and if you do, shuffle this card into the Extra Deck. \
"""
strings = ["Draw and check"]

[card.palladium-magician-arcane]
id = 410000014
set = "palladium"
name = "Palladium Magician's Arcane"
type = "monster union tuner effect"
attribute = "dark"
race = "spellcaster"
level = 2
atk = 300
def = 500
effect = """\
You can target 1 "Palladium" Spellcaster monster you control; this card's Level becomes the Level of that monster. \
Once per turn, you can either: Target 1 "Palladium" Spellcaster monster you control; \
    equip this card, from your hand, GY or on the field, to that target, OR: Unequip this card and Special Summon it. \
    If the equipped monster would be destroyed by battle or card effect, destroy this card instead. \
During damage calculation, if the equipped monster battles your opponent's monster: \
    The Attribute of opponent's battling monster become DARK. \
If this card is in your hand, GY: You can target 1 "Palladium" Xyz Monster you control; \
    attach this card to it as an Xyz Material. \
    You can only use this effect of "Palladium Magician's Arcane" once per turn. \
"""
strings = ["Copy level", "Change battling monster's Attribute", "Attach"]

[card.palladium-paladin-ace-joker]
id = 410000020
set = "palladium"
name = "Palladium Paladin Ace Joker"
type = "fusion monster effect"
attribute = "light"
race = "warrior"
level = 9
atk = 3800
def = 2500
effect = """\
"Queen's Knight" + "Jack's Knight" + "King's Knight"
A Fusion Summon of this card can only be done with the above materials. \
Must first be either Fusion Summoned, or Special Summoned by sending the above monsters you control to the GY \
    (in which case you do not use "Polymerization"). \
When a card or effect, is activated that targets this face-up card on the field (Quick Effect): \
    You can discard 1 card; negate the activation, and if you do, destroy it. \
Once per turn (Quick Effect): \
    You can send the top card of your deck to the GY, for the rest of the turn, \
    and if you do, your opponent cannot activate card effects with the same type (Monster, Spell, or Trap) as that card.
"""
strings = ["Negate activation", "Block activate"]

[card.tablet-of-lost-memories]
id = 410000021
set = "palladium"
name = "Tablet of Lost Memories"
type = "spell quick-play"
effect = """\
(This card is always treated as "Palladium" card.)
During the Main Phase, if you control "Millennium Ascension": \
    You can reveal 1 "Dark Magician", "Blue-Eyes White Dragon" or "Red-Eyes Black Dragon" in your hand; \
    Add this card from your Deck or GY to your hand. \
    You can only use this effect of "Tablet of Lost Memories" once per turn. \
During the Main Phase, activate 1 of these effect;
● Add to your hand from your Deck or GY, \
    OR Special Summon from your hand, Deck or GY, \
    1 "Dark Magician", "Blue-Eyes White Dragon" or "Red-Eyes Black Dragon".
● If you control "Dark Magician": \
    Destroy all Spells and Traps your opponent controls.
● If you control "Blue-Eyes White Dragon": \
    Destroy all monsters your opponent controls.
● If you control "Red-Eyes Black Dragon": \
    Inflict damage to your opponent equal to original ATK of 1 monster you control.
"""
strings = [
    "Search a monster",
    "Destroy Spells and Traps",
    "Destroy monsters",
    "Inflict damage",
]

[card.palladium-sacrophagus]
id = 410000026
set = "palladium"
name = "Palladium Sacrophagus"
type = "spell quick-play"
effect = """\
Banish 1 card in either player GY or your Deck, \
    and if you do, until the end of the next turn, its effects are negated, \
    as well as the activated effects and effects on your opponent's side of the field of cards with the same original name. \
If you control no monsters, you can activate this card from your hand in either player's turn. \
During the Standby Phase, if you control "Millennium Ascension": You can add this card from your Deck to your hand, \
    You can only use this effect of "Palladium Sacrophagus" once per turn. \
During your Main Phase, except the turn this card was sent to the GY: \
    You can shuffle this card from your GY into the Deck, \
    and if you do, add 1 your face-up banished card to your hand. \
"""
strings = []

[card.chaos-eyes-palladium-dragoon]
id = 410000035
set = "chaos palladium"
name = "Chaos-Eyes Palladium Dragoon"
type = "monster fusion effect"
attribute = "light"
race = "spellcaster"
level = 10
atk = 3950
def = 3300
effect = """\
(This card is also always treated as DARK monster.)
"Dark Magician" + "Blue-Eyes White Dragon" + "Red-Eyes Black Dragon"
Must be Special Summoned with "Polymerization". \
Cannot be destroyed by card effects, be Tributed, nor used as Fusion Material, also neither player can target it with card effects. \
Once per turn: You can destroy up to 3 cards your opponent controls, \
    and if you do, banish them and inflict damage to your opponent equal to the combined original ATK of those destroyed monster(s). \
Once per turn, when your opponent activates a card or effect (Quick Effect): \
    You can negate the activation, \
    and if you do, banish that card, \
    and if you do that, this card gains 1000 ATK. \
Once per turn, at the start of the Damage Step, if this card battles an opponent's monster: \
    You can banish that monster, also, this card can make a second attack in a row. \
If this card leaves the field: Shuffle it into the Extra Deck, \
    also, you can add 1 Spell/Trap from your GY to your hand. \
"""
strings = [
    "Destroy & damage",
    "Negate activation",
    "Banish battling monster",
    "Add 1 Spell/Trap?",
]

[card.chaos-end-ruler]
id = 410000036
set = "chaos palladium"
name = "Chaos End Ruler - Envoy of Palladium"
type = "monster xyz effect"
attribute = "dark"
race = "warrior"
level = 8
atk = 3500
def = 2500
effect = """\
2 Level 8 "Palladium" Ritual Pendulum Monsters
This card's activation and effect cannot be negated. \
Gains 100 ATK for each banished cards. \
Banish any monster destroyed by battle with this card. \
This card gains effects based on the Attribute of materials attached to it.
● LIGHT: Your opponent cannot target or destroy this card with card effects. \
    If this card attacks an opponent's monster, during the Damage Step only, \
        negate the effects of that monster while it is face-up on the field \
        (but its effects can still be activated)
● DARK: You can detach 1 material from this card; \
    Banish as many cards in your opponent's hands and on their side of the field, \
    then inflict 500 damage to your opponent for each banished card this effect, \
    also other monsters you control cannot attack for the rest of this turn. \
    You can only use this effect of "Chaos End Ruler - Envoy of Palladium" once per turn.
"""
strings = [
    "Activated \"Chaos End Ruler - Envoy of Palladium\" effect",
    "Banish all of your opponent's cards",
]
