# [card.the-true-name-of-palladium-ruler]
# id = 410000007
# set = "palladium"
# name = "The True Name of Palladium Ruler"
# type = "spell"
# effect = """\
# Declare 1 card name; excavate the top card of your Deck, and if it is the declared card, add it to your hand, \
#     then you can take 1 original DIVINE monster, \
#     and add it to your hand from Deck, GY or Special Summon it from hand, Deck. \
#     Otherwise, send it to the GY. \
# You can only activate 1 "The True Name of Palladium Ruler" per turn. \
# """
# strings = ["Take 1 DIVINE monster?", "Add to hand", "Special Summon"]

# [card.palladium-reborn]
# id = 410000008
# set = "palladium"
# name = "Palladium Reborn"
# type = "spell quick-play"
# effect = """\
# This card's name is also treated as "Monster Reborn". \
# Target 1 monster in either GY; Special Summon it, but send it to the GY during the End Phase of this turn. \
#     you can also Special Summon "The Winged Dragon of Ra" with this card's effect, ignoring its Summoning conditions. \
# You can only activate 1 "Palladium Reborn" per turn. \
# """
# strings = ["Special Summoned by \"Palladium Reborn\""]

# [card.palladium-apostle-obelisk]
# id = 410000009
# set = "palladium"
# name = "Palladium Apostle of Obelisk"
# type = "monster effect"
# attribute = "light"
# race = "spellcaster"
# level = 4
# atk = 1500
# def = 1500
# effect = """\
# This card can be treated as 3 Tributes for the Tribute Summon of a DIVINE monster. \
# If this card is Tributed for a Tribute Summon of a DIVINE monster: \
#     You can Special Summon 2 "Palladium Token" (Spellcaster/LIGHT/Level 1/ATK 0/DEF 0) in Defense Position. \
# While this card is in the GY: If you would Tribute a DIVINE monster for a Tribute Summon, \
#     you can Tribute a monster(s) your opponent controls, even though you do not control them. \
# """
# strings = ["Summon a DIVINE monster"]

# [card.palladium-apostle-slifer]
# id = 410000010
# set = "palladium"
# name = "Palladium Apostle of Slifer"
# type = "monster effect"
# attribute = "light"
# race = "spellcaster"
# level = 4
# atk = 1200
# def = 2000
# effect = """\
# This card can be treated as 3 Tributes for the Tribute Summon of a DIVINE monster. \
# If this card is Tributed for a Tribute Summon of a DIVINE monster: You can draw 2 cards. \
# While this card is in the GY: There is no limit to the number of cards in your hand. \
# """
# strings = []

# [card.palladium-apostle-ra]
# id = 410000011
# set = "palladium"
# name = "Palladium Apostle of Ra"
# type = "monster effect"
# attribute = "light"
# race = "spellcaster"
# level = 4
# atk = 1800
# def = 1000
# effect = """\
# This card can be treated as 3 Tributes for the Tribute Summon of a DIVINE monster. \
# If this card is Tributed for a Tribute Summon of a DIVINE monster: You can gain 2000 LP. \
# While this card is in the GY (Quick Effect): You can Tribute 1 face-up original DIVINE monster; gain LP equal to the ATK it had on the field. \
# """
# strings = []

# [card.palladium-knight-queen]
# id = 410000012
# set = 'palladium'
# name = "Palladium Knight of Queen"
# type = "monster effect"
# attribute = "light"
# race = "warrior"
# level = 4
# atk = 1500
# def = 1600
# effect = """\
# This card's name is also treated as "Queen's Knight". \
# You can Special Summon this card (from your hand) by revealing 1 other Warrior monster in your hand. \
# If this card is Summoned: You can add 1 LIGHT Warrior monster from your Deck or GY to your hand, except "Palladium Knight of Queen". \
#     You can only use this effect of "Palladium Knight of Queen" once per turn. \
# """
# strings = []

# [card.palladium-knight-jack]
# id = 410000013
# set = 'palladium'
# name = "Palladium Knight of Jack"
# type = "monster effect"
# attribute = "light"
# race = "warrior"
# level = 4
# atk = 1900
# def = 1000
# effect = """\
# This card's name is also treated as "Jack's Knight". \
# If this card is Summoned: \
#     You can target cards your opponent control, up to the number of LIGHT Warrior monsters you control with different names; destroy them. \
#     You can only use this effect of "Palladium Knight of Jack" once per turn. \
# A monster that was Fusion Summoned using this card as material gains the following effect.
# ● Cannot be destroyed by battle or card effects.
# """
# strings = ["Cannot be destroyed by battle or card effects"]

# [card.palladium-knight-king]
# id = 410000014
# set = 'palladium'
# name = "Palladium Knight of King"
# type = "monster effect"
# attribute = "light"
# race = "warrior"
# level = 4
# atk = 1800
# def = 1400
# effect = """\
# This card's name is also treated as "King's Knight". \
# If you control "Queen's Knight", you can Special Summon this card from your hand, \
#     then you can Special Summon 1 LIGHT Warrior monster from your hand, Deck or GY, \
#     except "Palladium Knight of King" and "King's Knight". \
# If this card is Summoned: You can add 1 "Polymerization" from your Deck to your hand. \
#     You can only use this effect of "Palladium Knight of King" once per turn. \
# """
# strings = ["Summon a LIGHT Warrior monster?"]

# [card.palladium-paladin-ace-joker]
# id = 410000015
# set = 'palladium'
# name = "Palladium Paladin Ace Joker"
# type = "fusion monster effect"
# attribute = "light"
# race = "warrior"
# level = 9
# atk = 3800
# def = 2500
# effect = """\
# "Queen's Knight" + "Jack's Knight" + "King's Knight"
# A Fusion Summon of this card can only be done with the above materials. \
# Must first be either Fusion Summoned, \
#     or Special Summoned by sending the above monsters you control to the GY (in which case you do not use "Polymerization"). \
# When a card or effect, is activated that targets this face-up card on the field (Quick Effect): \
#     You can discard 1 card; negate the activation, and if you do, destroy it. \
# Once per turn (Quick Effect): \
#     You can send the top card of your deck to the GY, for the rest of the turn, \
#     and if you do, your opponent cannot activate card effects with the same type (Monster, Spell, or Trap) as that card.
# """
# strings = ["Negate activation", "Block activate"]
