# [card.palladium-reborn]
# id = 410000008
# set = "palladium"
# name = "Palladium Reborn"
# type = "spell quick-play"
# effect = """\
# This card's name is also treated as "Monster Reborn". \
# Target 1 monster in either GY; Special Summon it, but send it to the GY during the End Phase of this turn. \
#     you can also Special Summon "The Winged Dragon of Ra" with this card's effect, ignoring its Summoning conditions. \
# You can only activate 1 "Palladium Reborn" per turn. \
# """
# strings = ["Special Summoned by \"Palladium Reborn\""]
