[expansion.triplesix]
default = true
recipe  = [
    "macro.toml",
    "setcard.toml",
    "pack/generic.toml",
    "pack/nordic.toml",
    "pack/palladium.toml",
]

[picset.triplesix]
field = true
mode  = "proxy"
