[expansion.triplesix]
default = true
recipe  = [
    "pack/_macro.toml",
    "pack/_setcard.toml",
    "pack/generic.toml",
    "pack/nordic.toml",
    "pack/number.toml",
    "pack/supreme-dragon.toml",
]

[picset.triplesix]
field = true
mode  = "proxy"
