[expansion.triplesix]
default = true
recipe  = [
    "pack/_macro.toml",
    "pack/generic.toml",
    "pack/egyptian_god.toml",
    "pack/phantasms_god.toml",
    "pack/aesir_god.toml",    
    "pack/wicked_god.toml",    
]

[picset.triplesix]
field = true
mode  = "proxy"
