[expansion.triplesix]
default = true
recipe  = [
    "pack/_macro.toml",
    "pack/generic.toml",
    "pack/palladium.toml",
    "pack/blue-eyes.toml",
    "pack/red-eyes.toml",
    "pack/signer-dragon.toml",
]

[picset.triplesix]
field = true
mode  = "proxy"
