set_name = "triplesix"

packs = [
    "./pack/egyptian/pack.toml",
    # "./pack/dracodeity/pack.toml",
]

marcos = [
    "./pack/egyptian/marco.toml"
    #"./pack/dracodeity/marco.toml"
]

setcodes = [ "./setcode.toml" ]
