set_name = "triplesix"
setcodes = ["./setcode.toml"]

packs = [
    "./pack/egyptian",
    "./pack/palladium",
    "./pack/blue-eyes",
    "./pack/signer-dragons",
]

skip_compile_packs = [
    "./pack/egyptian",
    "./pack/palladium",
    "./pack/blue-eyes",
    # "./pack/signer-dragons",
]
