[macro]

HIERARCHY = """(This card's base Divine Hierarchy is $1.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is $1, and is always treated as "$2".)"""
HIERARCHY_CUSTOM = """(This card's base Divine Hierarchy is $1$2.)"""
EGYPTIAN_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN_EFFECT = """\
This card's effects cannot be copied, \
    or be negated by Spell/Trap effects. \
Control of it cannot switch. \
Cannot be Tributed, or used as a material for an Summon by your opponent. \
Cannot change battle position, or leave the field by other cards' effects, \
    except for monsters with the higher Divine Hierarchy. \
Unaffected by your opponent's monster effects, \
    whose Divine Hierarchy lower than its. \
Other cards' effects are only applied on it for 1 turn.\
"""
EGYPTIAN_SPSUMMON_EFFECT = """\
When this card is Special Summoned in Defense Position, \
    while your opponent targeting exactly 1 monster you control \
    for attack or with card effect, you can switch the target to it, \
    ignoring card effects. \
During the turn this card is Special Summoned from the GY, \
    it cannot attack, and send it to the GY during the End Phase.\
"""

NORDIC_GOD_EFFECT = """\
This card's $1 Summon cannot be negated. \
Cannot be Tributed, or be used as a material for an Summon.\
"""
NORDIC_GOD_REBORN = """\
Once per turn, during the End Phase, if this card on the field was destroyed and sent to the GY: \
    You can Special Summon it from the GY.\
"""
AESIR_GOD_EFFECT = """\
${NORDIC_GOD_EFFECT|Synchro}\
"""

TO_PZONE_WHEN_DESTROYED = """\
If this card in the Monster Zone is destroyed: You can place it in your Pendulum Zone.\
"""