[macro]

HIERARCHY = """(This card's base Divine Hierarchy is $1.)"""
HIERARCHY_ALIAS = """(This card's name is always treated as "$2". This card's base Divine Hierarchy is $1.)"""
EGYPTIAN_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN_DIVINE_IMMUNITY = """\
This card's activation and effects cannot be negated. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Cannot be flipped face-down. \
Possession of this card cannot be switched. \
Unaffected by your opponent's monster effects and other cards' effects that would make this card leave the field, \
    except cards' effects with the same or higher Divine Hierarchy. \
Cannot be destroyed by battle with a monster has lower Divine Hierarchy, also you take no Battle Damage from that battle. \
Cards' effects are only applied on this card for 1 turn.\
"""
EGYPTIAN_DIVINE_LIMIT = """\
During the End Phase, if this card was Special Summoned from the GY: Send it to the GY.\
"""
EGYPTIAN_GOD_IMMUNITY = """\
This card's Special Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Cannot be flipped face-down. \
Possession of this card cannot be switched. \
Unaffected by other cards' effects, except cards' effects with the same or higher Divine Hierarchy. \
Cannot be destroyed by battle with a monster have no or lower Divine Hierarchy, also you take no Battle Damage from that battle.\
"""

NORDIC_GOD_EFFECT = """\
Must first be $1 Summoned. \
This card's $1 Summon cannot be negated. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
"""
NORDIC_GOD_REBORN = """\
Once per turn, during the End Phase, if this card on the field was destroyed and sent to the GY: \
    You can Special Summon this card from the GY. \
"""
AESIR_GOD_EFFECT = """\
${NORDIC_GOD_EFFECT|Synchro} \
"""

TO_PZONE_WHEN_DESTROYED = """\
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""