[macro]

HIERARCHY = """(This card's base Divine Hierarchy is $1.)"""
HIERARCHY_ALIAS = """(This card's base Divine Hierarchy is $1, and is always treated as "$2".)"""
EGYPTIAN_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN_EFFECT = """\
This card's effects cannot be negated or copied. \
Control of it cannot switch. \
Cannot be Tributed, nor used as a material for an Summon by your opponent. \
Cannot change battle position or leave the field with Spell/Trap effects. \
Unaffected by other monsters' effects, whose Divine Hierarchy lower than its. \
Other cards' effects are only applied on it for 1 turn.\
"""
EGYPTIAN_SPSUMMON_EFFECT = """\
When it is Special Summoned in Defense Position \
    while your opponent targets exactly 1 monster you control \
    for attack or card effect, you can switch the target to it. \
Cannot attack the turn it is Special Summoned from the GY, and send it to the GY during the End Phase.\
"""

NORDIC_GOD_EFFECT = """\
This card's $1 Summon cannot be negated. \
Cannot be Tributed, or be used as a material for an Summon.\
"""
NORDIC_GOD_REBORN = """\
Once per turn, during the End Phase, if this card on the field was destroyed and sent to the GY: \
    You can Special Summon it from the GY.\
"""
AESIR_GOD_EFFECT = """\
${NORDIC_GOD_EFFECT|Synchro}\
"""

TO_PZONE_WHEN_DESTROYED = """\
If this card in the Monster Zone is destroyed: You can place it in your Pendulum Zone.\
"""