[macro]

HIERARCHY = """(This card's base Divine Hierarchy is $1.)"""
HIERARCHY_ALIAS = """(This card is always treated as "$2", and it's base Divine Hierarchy is $1.)"""
EGYPTIAN_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN_EFFECT = """\
This card's activation and effects cannot be negated. \
Control of this card cannot switch. \
Cannot be changed to face-down Position. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Unaffected by Spell/Trap effects that would make this card leave the field, \
    and also other monster effects with the lower Divine Hierarchy. \
Other cards' effects are only applied on this card for 1 turn.\
"""
EGYPTIAN_LIMIT = """\
Cannot attack the turn it is Special Summoned. \
During the End Phase, return this Special Summoned card to the location it was Special Summoned from.\
"""

NORDIC_GOD_EFFECT = """\
This card's $1 Summon cannot be negated. \
Cannot be Tributed, or be used as a material for a Summon.\
"""
NORDIC_GOD_REBORN = """\
Once per turn, during the End Phase, if this card on the field was destroyed and sent to the GY: \
    You can Special Summon it from the GY.\
"""
AESIR_GOD_EFFECT = """\
${NORDIC_GOD_EFFECT|Synchro}\
"""

TO_PZONE_WHEN_DESTROYED = """\
If this card in the Monster Zone is destroyed: You can place it in your Pendulum Zone.\
"""