DRACODEITY_SUMMON = """\
3+ Dragon monsters, except Tokens, including a {0} monster \
"""

DRACODEITY_EFFECT = """\
You can only control 1 "{CARD_NAME}". \
Must be Link Summoned. \
This card's Link Summon cannot be negated. \
Control of this card cannot switch. \
"""