[goshenite]
id = 990000000
rarity = "gold"
name = "Goshenite of Dracodeity"
type = "monster link effect"
race = "dragon"
link = 3
link_arrow = "top left right"
atk = 0
effect = """\
3 monsters
{DRACODEITY_EFFECT} \
You can use face-up monsters your opponent control as material to Link Summon a High Dragon Link Monster, \
    as if they were Dragon monsters. \
"""

[greisen]
id = 990000001
rarity = "gold"
name = "Greisen, Dracodeity of the Cosmogony"
type = "monster link effect"
attribute = "light"
race = "high-dragon"
link = 5
link_arrow = "top bottom left right bottom-right"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|LIGHT}
{DRACODEITY_EFFECT} \
"""

[obsidian]
id = 990000002
rarity = "gold"
name = "Obsidian, Dracodeity of the Void"
type = "monster link effect"
attribute = "dark"
race = "high-dragon"
link = 5
link_arrow = "top bottom left right bottom-left"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|DARK}
{DRACODEITY_EFFECT} \
"""

[amber]
id = 990000003
rarity = "gold"
name = "Amber, Dracodeity of the Inferno"
type = "monster link effect"
attribute = "fire"
race = "high-dragon"
link = 5
link_arrow = "bottom left top-right bottom-left bottom-right"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|FIRE}
{DRACODEITY_EFFECT} \
"""

[lapis]
id = 990000004
rarity = "gold"
name = "Lapis, Dracodeity of the Abyss"
type = "monster link effect"
attribute = "water"
race = "high-dragon"
link = 5
link_arrow = "bottom right top-left bottom-left bottom-right"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|WATER}
{DRACODEITY_EFFECT} \
"""

[andalusite]
id = 990000005
rarity = "gold"
name = "Andalusite, Dracodeity of the Continent"
type = "monster link effect"
attribute = "earth"
race = "high-dragon"
link = 5
link_arrow = "bottom left right top-left bottom-left"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|EARTH}
{DRACODEITY_EFFECT} \
"""

[chrysoprase]
id = 990000006
rarity = "gold"
name = "Chrysoprase, Dracodeity of the Air"
type = "monster link effect"
attribute = "wind"
race = "high-dragon"
link = 5
link_arrow = "bottom left right top-right bottom-right"
atk = 4000
effect = """\
{DRACODEITY_SUMMON|WIND}
{DRACODEITY_EFFECT} \
"""

[messiah]
id = 990000007
rarity = "gold"
name = "Messiah, Genesis of Dracodeity"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link = 6
link_arrow = "left right top bottom top-left top-right"
atk = "?"
effect = """\
"""