[goshenite]
id = 990000000
rarity = "gold"
name = "Goshenite of Dracodeity"
type = "monster link effect"
race = "dragon"
link = 3
link_arrow = "top left right"
atk = 0
effect = """\
3 monsters, except Tokens
You can only control 1 {CARD_NAME}. \
This card's Link Summon cannot be negated. \
After this card is Special Summoned, \
    declare 1 Attribute, this card becomes that Attribute. \
Cannot be used as material for the Link Summon, \
    except for the Link Summon of a Divine-Beast monster. \
If this card you control would be used as Link Material for a Divine-Beast monster, \
    you can also use up to 2 face-up monsters your opponent controls as material, \
    as if they were Dragon monsters. \
While this card is in your GY, except the turn this card was sent to the GY (Quick Effect): \
    You can target 1 Link Monster; \
    banish it until the End Phase this turn, and if you do, \
    Special Summon this card, but shuffle it into the Extra Deck during the End Phase, \
    also, for the rest of this turn after this card resolves, your opponent takes no damage. \
    You can only use this effect of {CARD_NAME} once per turn. \
"""
strings = [
    "Take no damage this turn",
    "Return banished monster to field",
    "Shuffle this card into the Extra Deck"
]

[greisen]
id = 990000001
rarity = "gold"
name = "Greisen, Dracodeity of the Cosmogony"
type = "monster link effect"
attribute = "light"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|LIGHT}
{DRACODEITY_EFFECT}\
The activation and activated effects of co-linked monsters you control cannot be negated. \
    This effect cannot be negated. \
"""

[obsidian]
id = 990000002
rarity = "gold"
name = "Obsidian, Dracodeity of the Void"
type = "monster link effect"
attribute = "dark"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|DARK}
{DRACODEITY_EFFECT}\
Co-linked monsters you control cannot be sent to GY, or be banished by your opponent's activated effects. \
"""

[amber]
id = 990000003
rarity = "gold"
name = "Amber, Dracodeity of the Inferno"
type = "monster link effect"
attribute = "fire"
race = "divine-beast"
link = 5
link_arrow = "bottom left top-right bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|FIRE}
{DRACODEITY_EFFECT}\
Your opponent cannot Tributed, or use co-linked monsters you control as a material for an Summon. \
You can target cards your opponent controls, \
    up to the number of cards this card points to; destroy them. \
    Your opponent cannot activate the targeted card(s) in response to this effect's activation. \
    You can only use this effect of {CARD_NAME} once per turn. \
When this card destroys a monster by battle: \
    You can inflict damage to your opponent equal to either the ATK or DEF (whichever is higher) of the destroyed monster. \
"""
strings = [
    "Destroy card(s) on the field",
    "Inflict damage equal to the ATK/DEF of the destroyed monster"
]

[lapis]
id = 990000004
rarity = "gold"
name = "Lapis, Dracodeity of the Abyss"
type = "monster link effect"
attribute = "water"
race = "divine-beast"
link = 5
link_arrow = "bottom right top-left bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WATER}
{DRACODEITY_EFFECT}\
Co-linked monsters you control cannot be returned to hand or Deck by your opponent's activated effects. \
"""

[andalusite]
id = 990000005
rarity = "gold"
name = "Andalusite, Dracodeity of the Continent"
type = "monster link effect"
attribute = "earth"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-left bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|EARTH}
{DRACODEITY_EFFECT}\
Co-linked monsters you control cannot be destroyed by battle. \
"""

[chrysoprase]
id = 990000006
rarity = "gold"
name = "Chrysoprase, Dracodeity of the Air"
type = "monster link effect"
attribute = "wind"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WIND}
{DRACODEITY_EFFECT}\
Co-linked monsters you control cannot be destroyed by card effects. \
"""

[messiah]
id = 990000007
rarity = "gold"
name = "Messiah, Genesis of Dracodeity"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link = 6
link_arrow = "left right top bottom top-left top-right"
atk = "?"
effect = """\
"""