[goshenite]
id = 990000000
rarity = "gold"
name = "Goshenite of Dracodeity"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link = 3
link_arrow = "top left right"
atk = 0
effect = """\
2+ monsters, except Tokens
This card's Link Summon cannot be negated. \
After this card is Special Summoned, declare 1 Attribute, this card becomes that Attribute. \
Once per turn, during your opponent's Main Phase, you can (Quick Effect): \
    Immediately after this effect resolves, Link Summon 1 Link Monster using materials you control, \
    including this card. \
If this card you control would be used as Link Material for a Divine-Beast monster, \
    you can also use up to 2 face-up Special Summoned monsters your opponent controls as material. \
While this card is in your GY, except the turn this card was sent to the GY and during the Battle Phase (Quick Effect): \
    You can target 1 Link-5 or higher monster you control; \
    banish it until the End Phase, and if you do, Special Summon this card, \
    also, for the rest of this turn after this card resolves, your opponent takes no damage. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Take no damage this turn"]

[greisen]
id = 990000001
rarity = "gold"
name = "Greisen, Dracodeity of the Chronology "
type = "monster link effect"
attribute = "light"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|LIGHT}
{DRACODEITY_EFFECT}\
The effects of this card and co-linked cards you control cannot be negated. This effect cannot be negated. \
Each time a card or effect is activated, this card gain 1000 ATK until the end of this turn. \
During your Draw Phase, before you draw: \
    You can look at up to 3 cards from the top of your Deck, \
    then place them on the top or bottom of the Deck in any order. \
During the Main Phase (Quick Effect): \
    You can take cards that is banished or in either GY, \
    up to the number of cards currently co-linked to this card, \
    add them to your hand, or Special Summon them if they were a Monster Card. \
    Neither player can activate cards, or the effects of cards, with that name for the rest of this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Look and sort top of your Deck",
    "Place on top of the Deck",
    "Place on bottom of the Deck",
    "Take card and block activate",
]

[obsidian]
id = 990000002
rarity = "gold"
name = "Obsidian, Dracodeity of the Void"
type = "monster link effect"
attribute = "dark"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|DARK}
{DRACODEITY_EFFECT}\
This card and co-linked cards you control cannot be sent to GY, or be banished by your opponent's activated effects. \
Negate the effects of your opponent's monsters destroyed by monsters you control (by battle or card effect). \
Once per turn, during the Main Phase (Quick Effect): \
    You can destroy all your opponent's monsters with 0 ATK, and if you do, banish them, \
    then this card gains 1000 ATK for each destroyed card until the end of this turn. \
During the End Phase: \
    You can make all monsters your opponent controls lose 1000 ATK for each cards currently co-linked to this card, \
    then if those monster's ATK has been reduced to 0 as a result, they cannot activate theirs effects while on the field. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Destroy monsters with 0 ATK", "Lower ATK of your monsters"]

[amber]
id = 990000003
rarity = "gold"
name = "Amber, Dracodeity of the Inferno"
type = "monster link effect"
attribute = "fire"
race = "divine-beast"
link = 5
link_arrow = "bottom left top-right bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|FIRE}
{DRACODEITY_EFFECT}\
Your opponent cannot Tributed, or use this card and co-linked cards you control as a material for an Summon. \
During your Main Phase (Quick Effect): \
    You can destroy of other cards on the field, up to the number of cards currently co-linked to this card, \
    and if you do, this card gains 500 ATK for each destroyed card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles an opponent's monster, \
    negate the effects of that monster during the Damage Step only. \
Once per turn, if this card destroys a monster by battle: \
    You can inflict damage to your opponent \
    equal to double the destroyed monster's original ATK or DEF (whichever is higher). \
"""
strings = ["Destroy other card(s) on the field", "Inflict damage"]

[lapis]
id = 990000004
rarity = "gold"
name = "Lapis, Dracodeity of the Abyss"
type = "monster link effect"
attribute = "water"
race = "divine-beast"
link = 5
link_arrow = "bottom right top-left bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WATER}
{DRACODEITY_EFFECT}\
This card and co-linked cards you control cannot be returned to Deck. \
At the start of your Battle Phase: \
    You can make 1 co-linked monster you control gains 500 ATK and 1 additional attack \
    for every card currently co-linked to it, during this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles an opponent's monster whose ATK is higher than its original ATK, \
    its ATK becomes its original ATK during the Damage Step only. \
Once per turn, at the end of the Battle Phase: \
    You can gain LP equal to combined original ATK of those monsters \
    are destroyed by battle with this card this turn. \
"""
strings = ["Gain multiple attacks", "Gain LP equal to destroyed monster"]

[peridot]
id = 990000005
rarity = "gold"
name = "Peridot, Dracodeity of the Atmosphere"
type = "monster link effect"
attribute = "wind"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WIND}
{DRACODEITY_EFFECT}\
This card and co-linked cards you control cannot be destroyed by card effects. \
You can negate the effects of all face-up monsters your opponent currently controls, until the end of this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles an opponent's monster has its effects negated, \
    that monster's ATK becomes 0 during the Damage Step only. \
When your opponent activates a card or effect (Quick Effect): \
    You can negate the activation, and if you do, destroy that card, \
    then if it was a Monster Card, this card gains ATK equal to the its original ATK until the end of this turn. \
    You can use this effect a number of times per turn up to the number of cards co-linked to this card. \
"""
strings = [
    "Negate effects all opponent monsters",
    "Negate activation & destroy",
]

[andalusite]
id = 990000006
rarity = "gold"
name = "Andalusite, Dracodeity of the Continent"
type = "monster link effect"
attribute = "earth"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-left bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|EARTH}
{DRACODEITY_EFFECT}\
This card and co-linked cards you control cannot be destroyed by battle. \
You take no Battle Damage from battles involving this card. \
At the start of your Battle Phase: \
    You can make 1 other face-up monster's ATK on the field become 0, and if it does, \
    this card gains that lost ATK, these changes last until the end of this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per Chain, when an opponent's monster declares an attack: \
    You can change the attack target to this card and perform damage calculation. \
    You can use this effect a number of times per turn up to the number of cards co-linked to this card. \
"""
strings = ["Absorpt ATK", "Attack redirect"]

[messiah]
id = 990000007
rarity = "gold"
name = "Messiah, Genesis of Dracodeity"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link = 7
link_arrow = "left right top-left top-right bottom-left bottom-right bottom"
atk = "?"
effect = """\
You can only control 1 "{CARD_NAME}". \
Cannot be Link Summoned. \
Must be Special Summoned (from your Extra Deck) by stacking it on top of all co-linked monsters you control. \
This card's Special Summon cannot be negated. \
After this card is Special Summoned, you can move it to another of your Main Monster Zones. \
The original ATK of this card becomes 1000 x the number of monster's original Attribute used for its Summon. \
This card gains effects of all original Divine-Beast monsters used for its Summon. \
Once per turn (Quick Effect): \
    You can move 1 monster stacked underneath this card to your zone this card points to, \
    that monster is treated as Link Spell if it was move to Spell & Trap Zone, \
    and also it cannot declare attacks or activate its effects. \
Once per turn, if this card have 7 or more co-link cards (Quick Effect): \
    You can shuffle all cards that are banished, on the field, and in the GYs into the Decks. \
    Neither player can activate cards or effects in response to this effect's activation. \
"""
strings = [
    "Move to another Main Monster Zones?",
    "Move stacked monster to zone",
    "Shuffle all cards into the Deck",
]
