[goshenite]
id = 990000000
rarity = "gold"
name = "Goshenite of Dracodeity"
type = "monster link effect"
race = "dragon"
link = 3
link_arrow = "top left right"
atk = 0
effect = """\
3 monsters, except Tokens
You can only control 1 "{CARD_NAME}". \
You can only Special Summon "{CARD_NAME}(s)" once per turn. \
This card's Link Summon cannot be negated. \
After this card is Special Summoned, \
    declare 1 Attribute, this card becomes that Attribute. \
Cannot be used as material for the Link Summon, \
    except for the Link Summon of a Divine-Beast monster. \
If this card you control would be used as Link Material for a Divine-Beast monster, \
    you can also use up to 2 face-up monsters your opponent controls as material, \
    as if they were Dragon monsters. \
While this card is banished or is in your GY: \
    You can banish 1 Link Monster you control until the End Phase; \
    Special Summon this card, but shuffle it into the Extra Deck during the End Phase, \
    also, for the rest of this turn after this card resolves, your opponent takes no damage. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Return banished monster to field",
    "Take no damage this turn",
    "Shuffle this card into the Extra Deck"
]

[greisen]
id = 990000001
rarity = "gold"
name = "Greisen, Dracodeity of the Cosmogony"
type = "monster link effect"
attribute = "light"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|LIGHT}
{DRACODEITY_EFFECT}\
The activation and effects of this card and co-linked monsters you control cannot be negated. \
    This effect cannot be negated. \
"""

[obsidian]
id = 990000002
rarity = "gold"
name = "Obsidian, Dracodeity of the Void"
type = "monster link effect"
attribute = "dark"
race = "divine-beast"
link = 5
link_arrow = "top bottom left right bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|DARK}
{DRACODEITY_EFFECT}\
Your opponent cannot Tributed, or use this card and co-linked monsters you control as a material for an Summon. \
"""

[amber]
id = 990000003
rarity = "gold"
name = "Amber, Dracodeity of the Inferno"
type = "monster link effect"
attribute = "fire"
race = "divine-beast"
link = 5
link_arrow = "bottom left top-right bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|FIRE}
{DRACODEITY_EFFECT}\
This card and co-linked monsters you control cannot be destroyed by card effects. \
Once per turn: You can destroy other cards on the field, up to the number of cards this card points to. \
If this card destroys an opponent's monster by battle or by its effects: \
    You can inflict damage to your opponent equal to the highest original ATK among those destroyed monsters. \
    This card must be face-up on the field to activate and to resolve this effect. \
"""
strings = [
    "Inflict damage equal to the highest original ATK of destroyed monsters",
    "Destroy other card(s) on the field",
]

[lapis]
id = 990000004
rarity = "gold"
name = "Lapis, Dracodeity of the Abyss"
type = "monster link effect"
attribute = "water"
race = "divine-beast"
link = 5
link_arrow = "bottom right top-left bottom-left bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WATER}
{DRACODEITY_EFFECT}\
This card and co-linked monsters you control cannot be destroyed by battle. \
"""

[andalusite]
id = 990000005
rarity = "gold"
name = "Andalusite, Dracodeity of the Continent"
type = "monster link effect"
attribute = "earth"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-left bottom-left"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|EARTH}
{DRACODEITY_EFFECT}\
This card and co-linked monsters you control cannot be sent to GY, or be banished by your opponent's activated effects. \
"""

[chrysoprase]
id = 990000006
rarity = "gold"
name = "Chrysoprase, Dracodeity of the Atmosphere"
type = "monster link effect"
attribute = "wind"
race = "divine-beast"
link = 5
link_arrow = "bottom left right top-right bottom-right"
atk = 3500
effect = """\
{DRACODEITY_SUMMON|WIND}
{DRACODEITY_EFFECT}\
This card and co-linked monsters you control cannot be returned to hand or Deck by your opponent's activated effects. \
"""

[messiah]
id = 990000007
rarity = "gold"
name = "Messiah, Genesis of Dracodeity"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link = 6
link_arrow = "left right top bottom top-left top-right"
atk = "?"
effect = """\
"""