[millennium-hieroglyph]
id = 900000000
template = "artwork"
name = "Millennium Hieroglyph"
strings = [
    "Mulligan?",
    "Place field?",
    "Perform Destiny Draw?",
    "Perform Destiny Excavate?",
]

[obelisk]
id = 900000001
alias = 10000000
rarity = "gold"
frame-path = "artwork/frame/obelisk.png"
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
{EGYPTIAN_GOD_HIERARCHY_1|Obelisk the Tormentor|Warrior} \
Once per turn, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls, \
    and also inflict damage to your opponent equal to this card's ATK. \
    This card cannot declare an attack the turn this effect is activated. \
    Cannot be activated as Chain Link 2 or higher. \
Once per turn, while a monster with Divine Hierarchy 2 or more on the field (Quick Effect): \
    You can Tribute 2 other monsters; \
    once during this turn, if this card battles an opponent's monster, \
    it gains ∞ ATK during the damage calculation only. \
If this card is Special Summoned in face-up Defense position during your opponent's turn, \
    for the rest of this turn, your opponent cannot target monsters for attacks, except this one. \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & inflict damage",
    "Gain ∞ ATK for 1 attack",
]

[osiris]
id = 900000002
alias = 10000020
frame-path = "artwork/frame/osiris.png"
rarity = "gold"
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{EGYPTIAN_GOD_HIERARCHY_1|Slifer the Sky Dragon|Dragon} \
This card's original ATK/DEF are equal to the number of cards in your hand x 1000. \
    This effect cannot be negated. \
If a monster(s) is Normal or Special Summoned to your opponent's field, \
    or a monster(s) is take control by your opponent, while this card is able to attack: \
    Choose that monster(s) as a Target; it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK or DEF has been reduced to 0 as a result, destroy it. \
If this card is Special Summoned in face-up Defense position during your opponent's turn, \
    for the rest of this turn, your opponent cannot target your monsters with card effect, except this one. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[ra]
id = 900000003
alias = 10000010
frame-path = "artwork/frame/ra.png"
rarity = "gold"
name = "Sun Divine Dragon of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
{EGYPTIAN_GOD_HIERARCHY_2|The Winged Dragon of Ra|Winged Beast} \
This card's original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field. \
While this card is able to attack, you can pay 1000 LP; destroy 1 monster on the field. \
Once while face-up on the field: You can pay LP so that you only have 1 left; \
    this card become Fusion Monster and gains ATK/DEF become equal to the amount of LP paid, \
    any increase in LP is changed to increase it's ATK/DEF instead, \
    unaffected by card effects that prevent it from attacking, also its attacks cannot be negated. \
    Cards and effects cannot be activated in response to this effect's activation. \
    You can also use this effect when Summon this card. \
If your "De-Fusion" targets this Fusion Monster, apply these effect instead: \
    The target loses its above effects, cannot activate its effects, \
    its ATK/DEF become 0, and if it do, its controller gains LP equal to that lost ATK". \
Once per turn, when an attack is declared involving this card: \
    You can Tribute any number of other face-up monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, until the end of this turn. \
    This card must be become Fusion Monster by its own effect to activate and to resolve this effects. \
"""
strings = [
    "De-fuse from \"The Winged Dragon of Ra\"",
    "Destroy 1 monster on the field",
    "Life Point Transfer",
    "Tribute other monsters to gain ATK",
]

[dreadroot]
id = 900000006
alias = 62180201
frame-path = "artwork/frame/wicked.png"
rarity = "gold"
name = "The Wicked Deity Dreadroot"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = 4000
def = 4000
effect = """\
{WICKED_GOD_HIERARCHY_1|The Wicked Dreadroot} \
The ATK/DEF of all other monsters on the field are halved, except monsters with higher Divine Hierarchy. \
If this card attacks an opponent's monster, during the Damage Step only, that monster cannot activate its effect. \
"""
strings = []

[eraser]
id = 900000007
alias = 57793869
frame-path = "artwork/frame/wicked.png"
rarity = "gold"
name = "The Wicked Deity Eraser"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = "?"
def = "?"
effect = """\
{WICKED_GOD_HIERARCHY_1|The Wicked Eraser} \
This card's original ATK/DEF are equal to the number of cards in your opponent controls x 1000. \
    This effect cannot be negated. \
Once per turn, if this card is Normal Summoned/Set: You can destroy this card. \
If this face-up card leaves the field, send all cards on the field to the GY, \
    ignoring card effects, except monsters with higher Divine Hierarchy. \
"""
strings = ["Destroy itself"]

[avatar]
id = 900000008
alias = 21208154
frame-path = "artwork/frame/wicked.png"
rarity = "gold"
name = "The Wicked Deity Avatar"
type = "monster effect"
attribute = "dark"
race = "divine-beast fiend"
level = 10
atk = "?"
def = "?"
effect = """\
{WICKED_GOD_HIERARCHY_2|The Wicked Avatar} \
This card's ATK/DEF are equal to the highest ATK on the field +100, except "The Wicked Avatar". \
Monster's destruction by battle with this card cannot be negated, \
    except monsters with higher Divine Hierarchy. \
After this card is Normal Summoned, your opponent cannot activate Spell/Trap Cards \
    until the end of their 2nd turn after this effect's activation. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": Cannot activate Spell/Trap Cards",
]

[the-chosen-pharaoh]
id = 900000009
rarity = "gold"
name = "The Chosen Pharaoh"
type = "trap continuous"
effect = """\
The activation of this card, or its effects, cannot be negated, nor can its effects be negated. \
The activation and effects of "The True Name" activated on your field cannot be negated. \
During your turn, if you control 3 monsters whose original names are \
    "Obelisk the Tormentor", "Slifer the Sky Dragon", and "The Winged Dragon of Ra": \
    Add 1 "Holactie the Creator of Light" from Outside to your hand. \
    You can only use this effect of "{CARD_NAME}" once per Duel. \
If this face-up card leaves the field: Destroy all monsters you control. \
You can only use the following effect of "{CARD_NAME}" once per turn. You can activate 1 of these effects;
● Add 1 "The True Name" from your Deck or GY to your hand.
● Special Summon 1 "Obelisk the Tormentor", "Slifer the Sky Dragon", or "The Winged Dragon of Ra" from your hand or GY.
● Add to your hand or Set directly from your Deck, 1 Spell/Trap that mentions \
    "Obelisk the Tormentor", "Slifer the Sky Dragon", or "The Winged Dragon of Ra", \
    with a different name from the cards you control and in your GY.
"""
strings = [
    "Call \"Holactie the Creator of Light\"",
    "Add \"The True Name\"",
    "Special Summon a Divine-Beast",
    "Add or Set Spell/Trap that mentions Divine-Beast",
]

[deity-evolution]
id = 900000010
name = "Deity Evolution"
type = "spell quick-play"
effect = """\
The activation of this card, or its effects, cannot be negated, nor can its effects be negated. \
All face-up monsters with Divine Hierarchy you control that not affected by "{CARD_NAME}" gain these effects, ignoring card effects;
● Gain 1000 ATK/DEF.
● Divine Hierarchy is increased by 1.
● The activation and effect of this card's effects cannot be negated.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
During your Main Phase, if this card is in your GY and you control a original Divine-Beast monster: \
    You can discard 1 Spell; add this card to your hand. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Affected by \"{CARD_NAME}\""]

[sun-god-descend]
id = 900000011
name = "Sun God Descend"
type = "spell quick-play"
effect = """\
The activation of this card, or its effects, cannot be negated, nor can its effects be negated. \
During the Main Phase: \
    Tribute 3 monsters on your field or your opponent's, and if you do, \
    Special Summon 1 "The Winged Dragon of Ra" from your hand or Deck, ignoring its Summoning conditions, \
    and its original ATK/DEF become the combined ATK/DEF of the monsters Tributed had on the field. \
    If you Tributed monsters on your opponent's field, it cannot attack this turn. \
If this card is in your GY: \
    You can target 1 "The Winged Dragon of Ra" or 1 card that mentions it \
    that is banished, or in your GY, except "{CARD_NAME}"; \
    shuffle both this card and that target into the Deck, \
    then draw 1 card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Tribute your monsters", "Tribute your opponent's monsters"]
