[supreme-king-dark-castle]
id = 900002100
set = "supreme-king"
name = "Supreme King's Dark Castle"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Add 1 "Polymerization" Spell Card or "Fusion" Spell Card from your Deck to your hand. \
You can Fusion Summon Fusion Monsters that must be Special Summoned with "Dark Fusion", \
    with effects other than "Dark Fusion". \
The activation of your cards and effects that include an effect that Fusion Summons a Fusion Monster cannot be negated, \
    also your opponent's cards and effects cannot activate when a monster is Fusion Summoned this way. \
"""
strings = ["Add 1 Fusion Spell?"]

# [blue-eyes-legend-dragon]
# id = 900001200
# alias = 89631139
# set = "blue-eyes"
# name = "Blue-Eyes Legend Dragon"
# type = "monster normal"
# attribute = "light"
# race = "dragon"
# level = 8
# atk = 3000
# def = 2500
# effect = """\
# (This card's name is always treated as "Blue-Eyes White Dragon".)
# You can Special Summon this card (from your hand) by \
#     revealing 1 Level 1 LIGHT Tuner in your hand. \
#     You can only Special Summon "{CARD_NAME}" once per turn this way. \
# Once per turn: You can destroy 1 other face-up card on the field. \
#     This card cannot attack the turn this effect is activated. \
# """
# strings = ["Destroy 1 other card on the field"]
