[supreme-king-dark-castle]
id = 900002100
set = "supreme-king"
name = "Supreme King's Dark Castle"
type = "spell field"
effect = """
You can only activate 1 "{CARD_NAME}" per turn. \
When this card is activated: Add 1 "Polymerization" Spell Card or "Fusion" Spell Card from your Deck to your hand. \
You can Fusion Summon Fusion Monsters that must be Special Summoned with "Dark Fusion", \
    with effects other than "Dark Fusion". \
The activation of your cards and effects that include an effect that Fusion Summons a Fusion Monster cannot be negated, \
    also your opponent's cards and effects cannot activate when a monster is Fusion Summoned this way. \
"""
strings = ["Add 1 Fusion Spell?"]

[the-supreme-king]
id = 900002101
rarity = "gold"
set = "supreme-king"
name = "The Supreme King of Spirit World"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"""
strings = []

[evil-hero-aero-scout]
id = 900002102
set = "evil-hero"
name = "Evil HERO Aero Scout"
type = "monster effect"
attribute = "wind"
race = "fiend"
level = 3
atk = 1000
def = 1000
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Avian". \
    This effect cannot be negated. \
"""
strings = []

[evil-hero-blaster-minx]
id = 900002103
set = "evil-hero"
name = "Evil HERO Blaster Minx"
type = "monster effect"
attribute = "fire"
race = "fiend"
level = 3
atk = 1200
def = 800
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Burstinatrix". \
    This effect cannot be negated. \
"""
strings = []

[evil-hero-igneous-insurgent]
id = 900002104
set = "evil-hero"
name = "Evil HERO Igneous Insurgent"
type = "monster effect"
attribute = "earth"
race = "fiend"
level = 4
atk = 800
def = 2000
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Clayman". \
    This effect cannot be negated. \
"""
strings = []

[evil-hero-bubbling-anger]
id = 900002105
set = "evil-hero"
name = "Evil HERO Bubbling Anger"
type = "monster effect"
attribute = "water"
race = "fiend"
level = 4
atk = 800
def = 1200
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Bubbleman". \
    This effect cannot be negated. \
If you control no monsters, you can Special Summon this card (from your hand). \
If this card is banished: You can draw 2 cards, then discard 1 card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[evil-hero-black-bolt]
id = 900002106
set = "evil-hero"
name = "Evil HERO Black Bolt"
type = "monster effect"
attribute = "light"
race = "fiend"
level = 4
atk = 1600
def = 1400
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Sparkman". \
    This effect cannot be negated. \
"""
strings = []

[evil-hero-savage-heart]
id = 900002107
set = "evil-hero"
name = "Evil HERO Savage Heart"
type = "monster effect"
attribute = "earth"
race = "fiend"
level = 4
atk = 1500
def = 1600
effect = """\
If this card is used as Fusion Material, its name can be treated as "Elemental HERO Wildheart". \
    This effect cannot be negated. \
"""
strings = []