[void-eyes-infernity-dragon]
id = 900003100
set = "void infernity"
name = "Void-Eyes Infernity Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 3000
effect = """\
"""
strings = [""]
