[void-eyes-infernity-dragon]
id = 900003100
set = "void infernity"
name = "Void-Eyes Infernity Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 3000
effect = """\
1 DARK Tuner + 1+ non-Tuner Fiend monsters
While this card is face-up on the field, it gains the effects of all "Infernity" monsters in your GY, \
    except "{CARD_NAME}". \
If your LP becomes 0 while you have no cards in your hand: \
    You can Special Summon this card (from your Extra Deck or GY), and if you do, gains these effects. \
    Your opponent cannot activate cards or effects in response to this effect's activation.
● You cannot lose the Duel. If this card leaves the field, you lose the Duel.
● Cannot be Tributed, or used as material for an Summon. \
    Control and battle position of this card cannot change by card effects. \
    The above effects cannot be negated.
● Once per turn, when your opponent activates a card or effect while you have no cards in your hand (Quick Effect): \
    You can negate the activation, and if you do, destroy it, \
    and if you do, this card gains 500 ATK.
"""
strings = [
    "Open the Zero Gate of the Void",
    "Summoned by Zero Gate of the Void",
    "Negate the activation & gain 500 ATK",
]
