[palladium-oracle-mahad]
id = 910000000
alias = 71703785
set = "palladium"
name = "Sacred Palladium Oracle Mahad"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 7
atk = 2500
def = 2100
effect = """\
(This card's name is always treated as "Palladium Oracle Mahad")
If this card is added to your hand, you can Special Summon it from your hand. \
Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell resolves (max 5). \
While this card has a Spell Counter, it is unaffected by your opponent's card effects. \
If this card battles a DARK monster, its ATK is doubled during the Damage Step only. \
"""
strings = ["Special Summon this card?"]

[palladium-oracle-mana]
id = 910000001
alias = 42006475
set = "palladium"
name = "Illusory Palladium Oracle Mana"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 6
atk = 2000
def = 1700
effect = """\
(This card's name is always treated as "Palladium Oracle Mana")
If you control "Palladium Oracle Mahad", you can Special Summon this card (from your hand). \
"Palladium" Spellcaster monsters you control cannot be destroyed by card effects. \
When your opponent targets a monster(s) you control with a card effect, \
    while this card is in your hand or GY: You can Special Summon this card. \
    You can only use this effects of "{CARD_NAME}" once per turn. \
"""
strings = []

[palladium-oracle-seto]
id = 910000002
set = "palladium"
name = "Azure Palladium Oracle Seto"
type = "monster tuner effect"
attribute = "light"
race = "spellcaster"
level = 1
atk = 0
def = 0
effect = """\
You can reveal this card in your hand; \
    add from your Deck or GY to your hand, \
    1 LIGHT or DARK Dragon monsters with 3000 or more ATK and 2500 or less DEF. \
    You cannot Normal Summon monsters the turn you activate this effect. \
You can discard this card, then target 1 "Blue-Eyes" monster you control; \
    Fusion Summon 1 Fusion Monster from your Extra Deck that lists that monster on the field as Fusion Material, \
    using it as the Fusion Material. \
You can Tribute this card; \
    Special Summon up to 3 copies of "Blue-Eyes White Dragon" from your hand, Deck or GY. \
    You cannot Special Summon other monsters the turn you activate this effect. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn.
"""
strings = [
    "Add a Dragon monster",
    "Summon 3 \"Blue-Eyes White Dragon\"",
    "Affected by effect \"{CARD_NAME}\": cannot Normal Summon monsters",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon monsters",
]

[palladium-oracle-aknamkanon]
id = 910000003
set = "chaos palladium"
name = "Chaos Palladium Oracle Aknamkanon"
type = "monster ritual effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 2800
def = 2600
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must first be Ritual Summoned, with using at least 1 Spellcaster monster. \
After this card was Special Summoned, your opponent cannot activate monster effects for the rest of that turn. \
You can only use the following effect of "{CARD_NAME}" once per turn.
● You can reveal this card in your hand; \
    add 1 "Palladium Oracle Mahad" or 1 non-Ritual Monster that mentions it, \
    from your Deck or GY to your hand, then place 1 card from your hand on top of the Deck.
● If this card destroys an opponent's monster by battle: \
    You can target 1 Spell/Trap in your GY; add it to your hand.
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot activate monster effects",
    "Add 1 Spell/Trap from the GY",
]

[black-luster-soldier-palladium]
id = 910000004
set = "palladium black-luster-soldier"
name = "Black Luster Soldier - Palladium Soldier"
type = "monster ritual effect"
attribute = "light"
race = "warrior"
level = 8
atk = 3000
def = 2500
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must first be either Ritual Summoned, \
    or Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
You can only Special Summon "{CARD_NAME}(s)" once per turn. \
Your opponent cannot target or destroy this Ritual Summoned card with card effects. \
When this card destroys an opponent's monster by battle: You can activate 1 of these effects;
● This card gains 1500 ATK.
● This card can make a second attack during the Battle Phase of your next turn.
● Banish 1 card your opponent control.
● Banish 1 random card from your opponent's hand face-down.
"""
strings = [
    "Gains 1500 ATK",
    "Make 2 attacks during next turn",
    "Banish 1 card on the field",
    "Banish 1 random card in hand",
]

[chaos-emperor-dragon-palladium]
id = 910000005
set = "chaos palladium"
name = "Chaos Emperor Dragon - Envoy of the Palladium"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
Cannot be Normal Summoned/Set. \
Must be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
You can pay 1000 LP; \
    send all cards your opponent controls to the GY, \
    then inflict 300 damage to your opponent for each card sent to the GY by this effect. \
    You cannot activate cards or effects and monsters you control cannot attack the turn you activate this effect, \
    except "{CARD_NAME}". \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this face-up card leaves the field, return it to the bottom of the Deck. \
"""
strings = [
    "Send card to the GY & inflict damage",
    "Affected by effect \"{CARD_NAME}\": cannot activate cards or effects and monsters cannot attack, except \"Chaos Emperor Dragon - Envoy of the Palladium\"",
]

[palladium-guardian-shada]
id = 910000007
set = "palladium guardian"
name = "Palladium Guardian Shada"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1400
def = 1200
effect = """\
During the Battle Step, while you control a "Palladium" monster \
    other than "{CARD_NAME}" (Quick Effect): \
    You can Special Summon this card from your hand, \
    and if you do, until the end of this turn, \
    "Palladium" monster you currently control cannot be destroyed by battle. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
The first time this card would be destroyed by battle each turn, \
    it is not destroyed, and you take no battle damage from that battle. \
At the end of the Damage Step, if this card battled an opponent's monster, \
    that monster lose 800 ATK. \
"""
strings = []

[palladium-gardna-karim]
id = 910000008
set = "palladium"
name = "Palladium Gardna Karim"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 100
def = 2600
effect = """\
When your opponent activates a card or effect \
    that targets this card (face-up or face-down) or "Palladium" monster you control (Quick Effect): \
    You can negate that activation, also change this card to face-up Defense Positionm, if able. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
When an opponent's monster declares an attack on a "Palladium" monster you control: \
    You can switch the attack target to this card. \
If this Defense Position card is attacked, it loses 800 DEF. \
"""
strings = ["Switch attack target"]

[palladium-maiden-isis]
id = 910000009
set = "palladium"
name = "Palladium Maiden Isis"
type = "monster effect"
attribute = "light"
race = "fairy"
level = 4
atk = 800
def = 2000
effect = """\
When your opponent activates a card or effect \
    in response to your "Palladium" monster's effect activation (Quick Effect): \
    You can Tribute this card from your hand or face-up field; \
    negate that effect. \
During your Main Phase: \
    You can change this card from face-up Attack Position to face-up Defense Position; \
    immediately after this effect resolves, look at up to 5 cards from the top of each player's Deck. \
During your Main Phase, while this card is in the GY, except the turn it was sent to the GY: \
    You can target 5 "Palladium" monsters that is banished or in your GY, except "{CARD_NAME}"; \
    shuffle this card and all the targeted cards into the Deck, then draw 1 card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Look at Deck"]

[palladium-oracle-hassan]
id = 910000010
set = "palladium"
name = "Serect Palladium Oracle Hassan"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 2300
def = 2800
effect = """\
When an opponent's monster declares a direct attack: \
    You can Special Summon this card from your hand or GY in Defense Position. \
When your opponent activates a card or effect that would inflict damage, \
    or when you would take battle damage during damage calculation (Quick Effect): \
    You can discard this card; you take no damage from that effect or battle. \
If this card is destroyed by battle or card effect: \
    You can return this card to the bottom of the Deck; \
    look at the top 3 cards of your Deck, then you can reveal 1 "Palladium" card, and add it to your hand, \
    also place the remaining cards on top of your Deck in any order. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Reduce damage", "Add 1 \"Palladium\" card to you hand"]

[chaos-eyes-palladium-dragon]
id = 910000011
set = "chaos palladium"
name = "Chaos-Eyes Palladium Dragon"
type = "monster effect"
attribute = "light dark"
race = "dragon"
level = 9
atk = 3300
def = 2500
effect = """\
(This card is always treated as DARK monster.)
To Tribute Summon this card, you must "Palladium" monster. \
You can Special Summon this card (from your hand) by \
    revealing 1 Level 1 LIGHT Tuner in your hand and \
    sending 1 Level 8 DARK Dragon from your hand, Deck, or your side of the field to the GY. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
Your opponent cannot target this card with card effects. \
Once per turn: You can target 1 card your opponent controls; \
    destroy it, and if you do, banish it. \
    This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy and banish 1 card"]

[palladium-knight-gaia]
id = 910000012
set = "palladium"
name = "Palladium Knight Gaia"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2300
def = 2100
effect = """\
If you control no monsters, or your opponent controls a monster with 2000 or more ATK, \
    you can Special Summon this card (from your hand). \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
When you Ritual or Fusion Summon a "Palladium" monster, \
    you can banish this card from your GY as 1 of materials. \
"""
strings = []

[palladium-knight-queen]
id = 910000013
alias = 25652259
name = "Palladium Knight of Queen"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1500
def = 1600
effect = """\
(This card's name is always treated as "Queen's Knight" and it is "Palladium" card.)
You can Special Summon this card (from your hand) by revealing 1 other LIGHT Warrior monster in your hand. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card is Normal or Special Summoned: \
    You can add 1 Level 4 LIGHT Warrior monster from your Deck or GY to your hand, except "Queen's Knight". \
    This card cannot declare an attack the turn this effect is activated. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion Summoned using this card as material gains this effect.
● If this card destroys an opponent's monster by battle: You can draw 1 card.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[palladium-knight-king]
id = 910000014
alias = 64788463
name = "Palladium Knight of King"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1600
def = 1400
effect = """\
(This card's name is always treated as "King's Knight" and it is "Palladium" card.)
If this card is added to your hand, except by drawing it: \
    You can Special Summon this card from your hand, \
    also you cannot Special Summon for the rest of this turn, except LIGHT Warrior monster. \
If this card is Normal or Special Summoned while you control another Level 4 LIGHT Warrior monster: \
    You can Special Summon 1 Level 5 LIGHT Warrior monster from your hand, Deck or GY. \
    This card cannot declare an attack the turn this effect is activated. \
You can only use each effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion Summoned using this card as material gains this effect.
● If this card attacks, your opponent cannot activate any Spell/Trap until the end of the Damage Step.
"""
strings = [
    "Summoned using \"{CARD_NAME}\"",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon, except LIGHT Warrior monster",
]

[palladium-knight-jack]
id = 910000015
alias = 90876561
name = "Palladium Knight of Jack"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 5
atk = 1900
def = 1000
effect = """\
(This card's name is always treated as "Jack's Knight" and it is "Palladium" card.)
If this card is Special Summoned: \
    You can target face-up cards your opponent control, \
    up to the number of LIGHT Warrior monsters you control with different names; destroy them. \
    This card cannot declare an attack the turn this effect is activated. \
You can Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters you control as materials, including this card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion Summoned using this card as material gains this effect.
● The first time this card would be destroyed by card effect each turn, it is not destroyed.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[palladium-archfiend-gilfer]
id = 910000016
set = "palladium archfiend"
name = "Palladium Archfiend Gilfer"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 6
atk = 2200
def = 2500
effect = """\
You can Normal Summon this card without Tributing, but send it to the GY during the End Phase. \
You can Special Summon this card (from your GY) by Tributing 1 "Palladium" monster. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card is sent to the GY: \
    You can target 1 face-up monster on the field; equip this card to that target. \
    That monster loses 500 ATK and has its effects negated while equipped with this card. \
"""
strings = ["Normal Summon without Tributing"]

[palladium-beast-gazelle]
id = 910000017
set = "palladium"
name = "Palladium Beast Gazelle"
type = "monster effect"
attribute = "dark"
race = "beast"
level = 4
atk = 1500
def = 1200
effect = """\
If this card is Normal or Special Summoned: \
    You can send 1 Level 5 or higher "Palladium" monster from your Deck to the GY; \
    add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. \
If this card is used as material for a Fusion Summon: You can draw 1 card. \
"""
strings = []

[palladium-beast-berfomet]
id = 910000018
set = "palladium"
name = "Palladium Beast Berfomet"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 5
atk = 1400
def = 1800
effect = """\
You can discard this card; \
    add 1 "Fusion" or "Polymerization" Spell, or 1 Level 4 or lower "Palladium" monster from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
When this card destroys a monster by battle: \
    Inflict damage to your opponent equal to the ATK of the destroyed monster. \
When you Fusion Summon a "Palladium" monster, you can banish this card from your GY as 1 of materials. \
"""
strings = []
