[palladium-oracle-mahad]
id = 900000100
alias = 71703785
set = "palladium"
name = "Sacred Palladium Oracle Mahad"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 7
atk = 2500
def = 2100
effect = """\
(This card's name is always treated as "Palladium Oracle Mahad".)
If this card is added to your hand: You can Special Summon it from your hand. \
You can reveal this card in your hand; add 1 Spell/Trap that mentions it, \
    from your Deck to your hand, then place 1 card from your hand on top of the Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles a DARK monster, its ATK is doubled during the Damage Step only. \
"""
strings = []

[palladium-oracle-mana]
id = 900000101
alias = 42006475
set = "palladium"
name = "Illusory Palladium Oracle Mana"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 6
atk = 2000
def = 1700
effect = """\
(This card's name is always treated as "Palladium Oracle Mana".)
When a card or effect is activated that targets a Spellcaster monster(s) you control, \
    while this card is in your hand or GY (Quick Effect): You can Special Summon this card. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"Palladium" Spellcaster monsters and Level 7 or higher Spellcaster monsters you control cannot be destroyed by card effects. \
During damage calculation, if your other "Palladium" Spellcaster monster battles an opponent's monster (Quick Effect): \
    You can send this card from your hand or face-up field to the GY; \
    that monster you control gains ATK equal to this card's original ATK during that damage calculation only. \
"""
strings = ["Send this card to GY to up ATK"]

[palladium-oracle-aknamkanon]
id = 900000102
set = "chaos palladium"
name = "Chaos Palladium Oracle Aknamkanon"
type = "monster ritual effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 2800
def = 2600
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
You can also Special Summon this card (from your hand) by Tributing 1 Level 7 or higher "Palladium" Spellcaster monster. \
After this card was Ritual Summoned, your opponent cannot activate monster effects for the rest of that turn. \
Spellcaster monsters you control gains 100 ATK/DEF for each banished cards. \
Banish any monster destroyed by battle with this card. \
If this card destroys an opponent's monster by battle: \
    You can target 1 Spell/Trap in your GY; add it to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot activate monster effects",
    "Return 1 Spell/Trap from the GY",
]

[black-luster-soldier-palladium]
id = 900000103
set = "palladium black-luster-soldier"
name = "Black Luster Soldier - Palladium Soldier"
type = "monster ritual effect"
attribute = "light"
race = "warrior"
level = 8
atk = 3000
def = 2500
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must first be either Ritual Summoned, \
    or Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
You can only Special Summon "{CARD_NAME}(s)" once per turn. \
Your opponent cannot target or destroy this Ritual Summoned card with card effects. \
When this card destroys an opponent's monster by battle: You can activate 1 of these effects;
● This card gains 1500 ATK.
● This card can make a second attack during the Battle Phase of your next turn.
● Banish 1 card your opponent control.
● Banish 1 random card from your opponent's hand face-down.
"""
strings = [
    "Gains 1500 ATK",
    "Make 2 attacks during next turn",
    "Banish 1 card on the field",
    "Banish 1 random card in hand",
]

[chaos-emperor-dragon-palladium]
id = 900000104
set = "chaos palladium"
name = "Chaos Emperor Dragon - Envoy of the Palladium"
type = "monster ritual effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must be either Ritual Summoned, \
    or Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
You can only Special Summon "{CARD_NAME}(s)" once per turn. \
Your opponent cannot activate cards or effects in response to this Ritual Summoned card's effect activations. \
Once per turn, you can pay 1000 LP; \
    send all other cards from the field to the GY, \
    then inflict 300 damage to your opponent for each card sent to the GY by this effect, \
    also for the rest of this turn, you cannot activate other cards or effects, \
    and other monsters you control cannot attack. \
"""
strings = [
    "Send card to the GY & inflict damage",
    "Affected by effect \"{CARD_NAME}\": cannot activate other cards or effects, and other monsters you control cannot attack",
]

[chaos-end-ruler]
id = 900000105
set = "chaos"
name = "Chaos End Ruler - Ruler of the Beginning and the End"
type = "monster xyz effect"
attribute = "light dark"
race = "fiend"
rank = 8
atk = 3500
def = 2000
effect = """\
2 Level 8 "Chaos" or "Black Luster Soldier" Ritual Monsters
(This card's Attribute is also DARK.)
Must first be Xyz Summoned. \
This card's Special Summon, activation and effect cannot be negated. \
Cannot be Tributed, or be used as a material for an Summon by your opponent. \
Gains 100 ATK/DEF for each cards in either GY. \
If this card attacks an opponent's monster, during the Damage Step only, \
        negate the effects of that monster while it is face-up on the field. \
This card gains the following effect(s), based on the material attached on it.
● LIGHT Warrior monster: \
    Cannot be destroyed by card effects, also your opponent cannot target it with card effects.
● DARK Dragon monster, during your Main Phase (Quick Effect): \
    You can detach 1 material from this card; \
    send all cards in your opponent's hands and on their side of the field to the GY, \
    then inflict 500 damage to your opponent for each card sent to the GY by this effect, \
    also other monsters you control cannot attack for the rest of this turn. \
    You can only use this effect of "Chaos End Ruler - Ruler of the Beginning and the End" once per turn.
"""
strings = [
    "Send card to GY & inflict damage",
    "Affected by effect \"Chaos End Ruler - Ruler of the Beginning and the End\": other monsters cannot attack",
]

[palladium-knight-queen]
id = 900000106
alias = 25652259
name = "Palladium Knight of Queen"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1500
def = 1600
effect = """\
(This card's name is always treated as "Queen's Knight" and it is "Palladium" card.)
This card is treated as a Normal Monster while in the hand or GY. \
You can Special Summon this card (from your hand) by revealing 1 other LIGHT Warrior monster in your hand. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card is Normal or Special Summoned: \
    You can add 1 Level 4 LIGHT Warrior monster from your Deck or GY to your hand, except "Queen's Knight". \
    This card cannot declare an attack the turn this effect is activated. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion or Link Summoned using this card as material gains this effect.
● If this card destroys an opponent's monster by battle: You can draw 1 card.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[palladium-knight-king]
id = 900000107
alias = 64788463
name = "Palladium Knight of King"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1600
def = 1400
effect = """\
(This card's name is always treated as "King's Knight" and it is "Palladium" card.)
This card is treated as a Normal Monster while in the hand or GY. \
If this card is added to your hand, except by drawing it: \
    You can Special Summon this card from your hand. \
If this card is Normal or Special Summoned while you control another Level 4 LIGHT Warrior monster: \
    You can Special Summon 1 Level 5 LIGHT Warrior monster from your hand, Deck or GY. \
    This card cannot declare an attack the turn this effect is activated. \
You can only use each effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion or Link Summoned using this card as material gains this effect.
● If this card attacks, your opponent cannot activate any Spell/Trap until the end of the Damage Step.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[palladium-knight-jack]
id = 900000108
alias = 90876561
name = "Palladium Knight of Jack"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 5
atk = 1900
def = 1000
effect = """\
(This card's name is always treated as "Jack's Knight" and it is "Palladium" card.)
This card is treated as a Normal Monster while in the hand or GY. \
If this card is Special Summoned: \
    You can target face-up cards your opponent control, \
    up to the number of LIGHT Warrior monsters you control with different names; destroy them. \
    This card cannot declare an attack the turn this effect is activated. \
You can Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters you control as materials, including this card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
A LIGHT Warrior monster that was Fusion or Link Summoned using this card as material gains this effect.
● The first time this card would be destroyed each turn, by battle or card effect, it is not destroyed.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[arcana-palladium-joker]
id = 900000109
set = "palladium"
name = "Arcana Palladium Joker"
type = "fusion monster effect"
attribute = "light"
race = "warrior"
level = 9
atk = 3800
def = 2500
effect = """\
3 Warrior monsters with different names
If this card is Fusion Summoned using "Queen's Knight", "Jack's Knight", and "King's Knight" as materials, \
    it is unaffected by your opponent's activated effects. \
A Fusion Summon of this card can only be done with the above materials. \
When your opponent activates a card or effect that targets a card(s) you control (Quick Effect): \
    You can discard 1 card; negate the effect. \
You can discard 1 card, then target 1 other card on the field; destroy it. \
If this Fusion Summoned card is destroyed by battle or card effect: \
    You can target 1 non-Fusion LIGHT Warrior monster in your GY; add it to your hand. \
"""
strings = [
    "Unaffected by your opponent's activated effects",
    "Discard to negate",
    "Discard to destroy",
]
