[palladium-oracle-mahad]
id = 900000100
alias = 71703785
set = "palladium"
name = "Sacred Palladium Oracle Mahad"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 7
atk = 2500
def = 2100
effect = """\
(This card's name is always treated as "Palladium Oracle Mahad".)
If this card is added to your hand: You can Special Summon it from your hand. \
You can reveal this card in your hand; add 1 Spell/Trap that mentions it, \
    from your Deck to your hand, then place 1 card from your hand on top of the Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card battles a DARK monster, its ATK is doubled during the Damage Step only. \
"""
strings = ["Special Summon this card?"]
