[palladium-oracle-mahad]
id = 910000000
alias = 71703785
set = "palladium"
name = "Sacred Palladium Oracle Mahad"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 7
atk = 2500
def = 2100
effect = """\
(This card's name is always treated as "Palladium Oracle Mahad")
If this card is added to your hand, you can Special Summon it from your hand. \
Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell resolves (max 5). \
While this card has a Spell Counter, it is unaffected by your opponent's card effects. \
If this card battles a DARK monster, its ATK is doubled during the Damage Step only. \
"""
strings = ["Special Summon this card?"]

[palladium-oracle-mana]
id = 910000001
alias = 42006475
set = "palladium"
name = "Illusory Palladium Oracle Mana"
type = "monster effect"
attribute = "light"
race = "spellcaster"
level = 6
atk = 2000
def = 1700
effect = """\
(This card's name is always treated as "Palladium Oracle Mana")
If you control "Palladium Oracle Mahad", you can Special Summon this card (from your hand). \
"Palladium" Spellcaster monsters you control cannot be destroyed by card effects. \
When your opponent targets a monster(s) you control with a card effect, \
    while this card is in your hand or GY: You can Special Summon this card. \
    You can only use this effects of "{CARD_NAME}" once per turn. \
"""
strings = []

[palladium-oracle-seto]
id = 910000002
set = "palladium"
name = "Azure Palladium Oracle Seto"
type = "monster tuner effect"
attribute = "light"
race = "spellcaster"
level = 1
atk = 0
def = 0
effect = """\
You can reveal this card in your hand; \
    add 1 "Blue-Eyes" monster from your Deck or GY to your hand. \
    You cannot Normal Summon monsters the turn you activate this effect. \
You can discard this card, then target 1 "Blue-Eyes White Dragon" you control; \
    Fusion Summon 1 Fusion Monster from your Extra Deck that lists that monster on the field as Fusion Material, \
    using it as the Fusion Material. \
You can Tribute this card; \
    Special Summon up to 3 copies of "Blue-Eyes White Dragon" from your hand, Deck or GY. \
    You cannot Special Summon other monsters the turn you activate this effect. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn.
"""
strings = [
    "Add 1 \"Blue-Eyes\" monster",
    "Summon 3 \"Blue-Eyes White Dragon\"",
    "Affected by effect \"{CARD_NAME}\": cannot Normal Summon monsters",
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon monsters",
]

[palladium-oracle-aknamkanon]
id = 910000003
set = "chaos palladium"
name = "Chaos Palladium Oracle Aknamkanon"
type = "monster ritual effect"
attribute = "light"
race = "spellcaster"
level = 8
atk = 2800
def = 2600
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must first be Ritual Summoned, with using at least 1 Spellcaster monster. \
After this card was Special Summoned, your opponent cannot activate monster effects for the rest of that turn. \
You can only use the following effect of "{CARD_NAME}" once per turn.
● You can reveal this card in your hand; \
    add 1 "Palladium Oracle Mahad" or 1 non-Ritual Monster that mentions it, \
    from your Deck or GY to your hand, then place 1 card from your hand on top of the Deck.
● If this card destroys an opponent's monster by battle: \
    You can target 1 Spell/Trap in your GY; add it to your hand.
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot activate monster effects",
    "Add 1 Spell/Trap from the GY",
]

[black-luster-soldier-palladium]
id = 910000004
set = "palladium black-luster-soldier"
name = "Black Luster Soldier - Palladium Soldier"
type = "monster ritual effect"
attribute = "light"
race = "warrior"
level = 8
atk = 3000
def = 2500
effect = """\
You can Ritual Summon this card with a "Palladium" card. \
Must first be either Ritual Summoned, \
    or Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
You can only Special Summon "{CARD_NAME}(s)" once per turn. \
Your opponent cannot target or destroy this Ritual Summoned card with card effects. \
When this card destroys an opponent's monster by battle: You can activate 1 of these effects;
● This card gains 1500 ATK.
● This card can make a second attack during the Battle Phase of your next turn.
● Banish 1 card your opponent control.
● Banish 1 random card from your opponent's hand face-down.
"""
strings = [
    "Gains 1500 ATK",
    "Make 2 attacks during next turn",
    "Banish 1 card on the field",
    "Banish 1 random card in hand",
]

[chaos-emperor-dragon-palladium]
id = 910000005
set = "chaos palladium"
name = "Chaos Emperor Dragon - Envoy of the Palladium"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
Cannot be Normal Summoned/Set. \
Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
You can pay 1000 LP; \
    send all cards your opponent controls to the GY, \
    then inflict 300 damage to your opponent for each card sent to the GY by this effect. \
    You cannot activate cards or effects and monsters you control cannot attack the turn you activate this effect, \
    except "{CARD_NAME}". \
If this card is sent to the GY: \
    You can target 1 your banished LIGHT or DARK monster; \
    add it to your hand. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Send card to the GY & inflict damage",
    "Affected by effect \"{CARD_NAME}\": cannot activate cards or effects and monsters cannot attack, except \"Chaos Emperor Dragon - Envoy of the Palladium\"",
]


[palladium-vizier-shimon]
id = 910000006
set = "palladium"
name = "Palladium Vizier Shimon"
type = "monster effect"
attribute = "light"
race = "fairy"
level = 5
atk = 1800
def = 2200
effect = """\
During the Main Phase (Quick Effect): \
    You can destroy 1 "Palladium", "Exodia", or "Forbidden One" monster \
    you control or in your hand, except "{CARD_NAME}", \
    and if you do, Special Summon this card from your hand in Defense Position. \
During your Main Phase, while this card is in the GY, except the turn it was sent to the GY: \
    You can target 5 "Palladium", "Exodia", and/or "Forbidden One" monsters \
    that is banished or in your GY, except "{CARD_NAME}"; \
    shuffle this card and all the targeted cards into the Deck, then draw 1 card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[palladium-guardian-shada]
id = 910000007
set = "palladium guardian"
name = "Palladium Guardian Shada"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1400
def = 1200
effect = """\
During the Battle Step, while you control a "Palladium" monster \
    other than "{CARD_NAME}" (Quick Effect): \
    You can Special Summon this card from your hand, \
    and if you do, until the end of this turn, \
    "Palladium" monster you currently control cannot be destroyed by battle. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
The first time this card would be destroyed by battle each turn, \
    it is not destroyed, and you take no battle damage from that battle. \
"""
strings = []

[palladium-gardna-karim]
id = 910000008
set = "palladium"
name = "Palladium Gardna Karim"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 100
def = 2600
effect = """\
When your opponent activates a card or effect \
    that targets this card (face-up or face-down) or "Palladium" monster you control (Quick Effect): \
    You can negate that activation, also change this card to face-up Defense Positionm, if able. \
    You can only use this effect of "Palladium Gardna Karim" once per turn. \
If this Defense Position card is attacked, it loses 800 DEF. \
"""
strings = []
