[card.millennium-hieroglyph]
id = 900000000
name = "Millennium Hieroglyph"
strings = [
    "Do nothing",
    "Go to next turn",
    "Move monster",
    "Return banished cards to the GY",
    "Return cards to Deck",
    "Reset game",
    "Place Continuous",
]

[card.obelisk]
id = 900000001
alias = 10000000
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|Obelisk the Tormentor}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Warrior-Type while on the field. \
Once per turn, while this card is able to attack: You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls and inflict damage to your opponent equal to this card's ATK. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn, while the total of monster's Divine Hierarchy on the field are 3 or more (Quick Effect): \
    You can Tribute 2 other monsters; \
    this turn, if this card battles, it gain ∞ ATK during damage calculation only. \
"""
strings = [
    "Soul Energy MAX",
    "Destroy all monsters & inflict damage",
    "Gain ∞ ATK",
]

[card.osiris]
id = 900000002
alias = 10000020
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Dragon-Type while on the field. \
The original ATK and DEF of this card each become equal to the number of cards in your hand x X000. (X is this card Divine Hierarchy.) \
If a monster(s) is Summoned to your opponent's field, while this card is able to attack: \
    Target that monster(s), ignoring card effects; it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK or DEF is 0, destroy it, \
    that monster(s) cannot activate its effects in response to this effect's activation. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[card.ra]
id = 900000003
alias = 10000010
name = "Sun Divine Beast of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Winged-Beast-Type while on the field. \
"""
strings = []

[card.ra-sphere]
id = 900000004
alias = 10000080
name = "Sun Divine Beast of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
After "The Winged Dragon of Ra" is Normal Summoned, \
    Dimension Change it to this card in the same battle position and Divine Hierarchy. \
${EGYPTIAN_EFFECT} \
This card is also Machine-Type while on the field. \
Cannot attack. \
Neither player can target this card for attacks or by card effects, \
    but does not prevent your opponent from attacking you directly. \
Once per turn: The original owner of this card can send this card to the Dimension Zone; \
    Dimension Summon the Dimension Material Monster (it's Divine Hierarchy is the same as with this card's) \
    then it gains the following effects effects. \
    If you just Dimension Changed this card, you can immediately used this effect with the same battle position. \
    Cards and effects cannot be activated in response to this effect's activation.
● The original ATK/DEF of this card become the combined original ATK/DEF of the monsters Tributed for its Tribute Summon, \
    or its become 4000/4000.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
"""
strings = ["Turn back to Normal Form", "Unstoppable Attack"]

[card.ra-phoenix]
id = 900000005
alias = 10000080
name = "Sun Divine Beast of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
${EGYPTIAN_EFFECT} \
This card is also Pyro-Type while on the field. \
Cannot attack. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy. \
Once per Chain, during the Main or Battle Phase (Quick Effect): You can pay 1000 LP; \
    ignoring card effects, this card immediately attacks and send 1 monster your opponent controls to the GY, \
    also you take no battle damage from that attack. \
During the End Phase, \
    Dimension Change this card to 1 "The Winged Dragon of Ra - Sphere Mode" Dimension Monster in Defense Position \
    (it's Divine Hierarchy is the same as with this card's, transfer materials to it), \
    if you don't, send it to the GY. \
After "The Winged Dragon of Ra" is Special Summoned from the GY to your field, \
    you can Dimension Change it to this card in the same battle position and Divine Hierarchy, \
    or can pay LP so that you only have 1 left; it gains the following effects until the end of this turn.
● This card become Fusion Monster and its original ATK/DEF become equal to the amount of LP paid, \
    and also, while it is on the field, any increase in LP is changed to increase it's original ATK/DEF instead.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
● Once per turn (Quick Effect): You can Tribute any number of other monsters that did not declare an attack this turn; \
    this card gains ATK equal to the Tributed monsters' combined original ATK, until the end of this turn.
● After damage calculation, if this card attacked, send all monsters your opponent controls to the GY.
● If "De-Fusion" targets this card, apply \
    "that target loses its above effects and its ATK/DEF become 0, \
    and if you do, its controller gains LP equal to that lost ATK" instead of. \
"""
strings = [
    "Do nothing",
    "Life Point Transfer",
    "Immortal Phoenix Form",
    "Quick attack",
    "Return to Dimension",
    "Tribtue monsters for ATK/DEF",
    "De-fuse from Ra"
]
