[card.millennium-hieroglyph]
id = 900000000
name = "Millennium Hieroglyph"
strings = [
    "Go to next turn",
    "Move monster",
    "Return banished cards to the GY",
    "Return cards to Deck",
    "Reset game",
]

[card.obelisk]
id = 900000001
alias = 10000000
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|Obelisk the Tormentor}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Warrior-Type while it is on the field. \
Once per turn, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; \
    destroy all monsters your opponent controls, \
    also inflict damage to your opponent equal to this card's ATK. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn, while the total monster's Divine Hierarchy on the field are 3 or more (Quick Effect): \
    You can Tribute 2 other monsters; \
    once during this turn, if this card battles an opponent's monster, \
    during damage calculation, it gains ∞ ATK during the damage calculation only. \
"""
strings = ["Soul Energy MAX", "Destroy & damage", "Gain ∞ ATK for 1 attack"]
frame = "obelisk"
name-color = "silver"

[card.osiris]
id = 900000002
alias = 10000020
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Dragon-Type while it is on the field. \
This card's original ATK and DEF are each equal to the number of cards in your hand x X000. \
    (X is its Divine Hierarchy). \
If a monster(s) is Normal or Special Summoned to your opponent's field, \
    while this card is able to attack: \
    Choose that monster(s) as Target; \
    it loses 2000 ATK or DEF depending on its battle position, \
    also, after that if its ATK/DEF is 0 as a result, destroy it. \
    That monster cannot activate its effects in response to this effect's activation. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]
frame = "osiris"
name-color = "silver"

[card.ra]
id = 900000003
alias = 10000010
name = "Sun Divine Dragon of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Winged-Beast-Type while it is on the field. \
Unaffected by other card effects that prevent it from attacking, also its attacks cannot be negated. \
Once while face-up on the field: You can pay LP so that you only have 100 left; \
    this card become Fusion Monster and gains original ATK/DEF become equal to the amount of LP paid, \
    and also, any increase in LP is changed to increase it's original ATK/DEF instead. \
    If your "De-Fusion" targets this Fusion Monster, apply \
    "that target loses its above effects and its ATK/DEF become 0, \
    and if it do, its controller gains LP equal to that lost ATK" instead of. \
    Cards and effects cannot be activated in response to the above effects' activation. \
    You can also use this effect when this card is Normal or Special Summoned. \
You can pay 1000 LP, then choose 1 monster on the field as Target; \
    destroy that monster, ignoring card effects. \
While this card was Special Summoned from the GY, it gains the following effects. \
    This card must be become Fusion Monster by its own effect to gain, activate, and resolve the following effects.
● Once per turn, when an attack is declared involving this card: You can Tribute any number of other face-up monsters; \
    this card gains ATK equal to the Tributed monsters' combined original ATK had on the field, \
    until the end of this turn.
● After damage calculation, if it attacked, send all monsters your opponent controls to the GY.
"""
strings = [
    "Life Point Transfer",
    "Destroy 1 monster",
    "Tribute monster for ATK",
]
frame = "ra"
name-color = "silver"

[card.ra-sphere]
id = 900000004
alias = 10000080
name = "Sun Divine Dragon of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
If your "The Winged Dragon of Ra" is Normal Summoned, \
    Dimension Change it to this card with the same Divine Hierarchy, \
    or if it is Summoned to your field, \
    its original ATK/DEF can become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field instead. \
${EGYPTIAN_EFFECT} \
This card is also Machine-Type while it is on the field. \
Cannot attack. \
Neither player can target it for attacks or by card effects, \
    but does not prevent your opponent from attacking you directly. \
While it is in Dimension Zone: \
    You can Normal Summon "The Winged Dragon of Ra" to your opponent's field. \
Once per turn, except the turn this card is Dimension Changed: \
    The turn player can reveal 1 "Ancient Chant" from everywhere; \
    Dimension Change this card to the material monster with the same Divine Hierarchy, \
    and if they do, its original ATK/DEF become 4000, \
    or the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field. \
    This effect's activation cannot be negated. \
    The owner no need to reveal "Ancient Chant". \
"""
strings = [
    "Summon to your field",
    "Summon to opponent's field",
    "Select the form",
    "Battle Mode",
    "Sphere Mode",
    "Reveal \"Ancient Chant\"?",
]
frame = "ra"
name-color = "silver"

[card.ra-phoenix]
id = 900000005
alias = 10000090
name = "Sun Divine Dragon of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
If your "The Winged Dragon of Ra" is Special Summoned from the GY, \
    you can Dimension Change it to this card with the same Divine Hierarchy, \
If "The Winged Dragon of Ra" you control would be destroyed by its own effect, \
    Dimension Change it to this card with the same Divine Hierarchy instead, \
    and its original ATK/DEF become the same as that monster's original ATK/DEF had on the field. \
This card's effect activations and its effects cannot be negated or copied. \
This card is also Pyro-Type while it is on the field. \
Control of it cannot switch. \
Cannot be Tributed, or used as a material for an Summon by your opponent. \
Unaffected by other cards' effects, \
    and cannot be destroyed by battle, also you take no battle damage from that battle, \
    except for monsters with the higher Divine Hierarchy. \
Cannot attack, except by its own effect. \
Once per Chain, except the End Phase (Quick Effect): \
    You can pay 1000 LP; \
    attack 1 monster your opponent control, \
    then send that monster to the GY after the damage calculation, \
    ignoring card effects. \
During the End Phase, \
    Dimension Change this card to 1 "The Winged Dragon of Ra - Sphere Mode" \
    with the same Divine Hierarchy (transfer this card's materials to that monster), \
    or send it to the GY. \
"""
strings = [
    "Select the form",
    "Battle Mode",
    "Phoenix Mode",
    "Attack 1 monster & send it to GY",
    "Turn into Sphere Mode or to the GY",
]
frame = "ra"
name-color = "silver"

[card.dreadroot]
id = 900000006
alias = 62180201
name = "The Wicked Dreadroot"
type = "monster effect"
attribute = "divine dark"
race = "fiend"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_CUSTOM|1| and its Attribute is also DARK}
Cannot be Special Summoned. \
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
During the End Phase, if this card was Special Summoned, \
    return it to the location it was Special Summoned. \
Halve the ATK/DEF of all other monsters on the field, \
    whose Divine Hierarchy same or lower than this card's. \
Negate the effects of monsters destroyed by battle with this card. \
"""
strings = ["Return to the location it was Special Summoned"]
frame = "wicked"
name-color = "silver"

[card.eraser]
id = 900000007
alias = 57793869
name = "The Wicked Eraser"
type = "monster effect"
attribute = "divine dark"
race = "fiend"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_CUSTOM|1| and its Attribute is also DARK}
Cannot be Special Summoned. \
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
During the End Phase, if this card was Special Summoned, \
    return it to the location it was Special Summoned. \
This card's original ATK and DEF are each equal to the number of cards your opponent controls x X000. \
    (X is its Divine Hierarchy). \
During your Main Phase: You can destroy this card. \
If this card is sent from the field to the GY, \
    negate the effects of all face-up cards on the fiels, \
    also, after that send all cards on the field to the GY, \
    except 1 face-up monster you control (if any). \
"""
strings = ["Return to the location it was Special Summoned", "Destroy itself"]
frame = "wicked"
name-color = "silver"

[card.avatar]
id = 900000008
alias = 21208154
name = "The Wicked Avatar"
type = "monster effect"
attribute = "divine dark"
race = "fiend"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_CUSTOM|2| and its Attribute is also DARK}
Cannot be Special Summoned. \
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
During the End Phase, if this card was Special Summoned, \
    return it to the location it was Special Summoned. \
This card is also DARK-Attribute monster while it is on the field. \
If this card is Normal Summoned: \
    Your opponent cannot activate Spell/Trap Cards until the end of their 2nd turn after this effect's activation. \
This card's ATK/DEF are equal to the highest ATK on the field +100, except "The Wicked Avatar". \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, \
    and you take no battle damage from that battle. \
"""
strings = [
    "Return to the location it was Special Summoned",
    "Affected by effect \"Wicked God Avatar\": cannot activate Spell/Trap Cards",
]
frame = "wicked"
name-color = "silver"

[card.emissary-divine-beast]
id = 900000100
name = "Emissary of the Divine Beasts"
type = "monster link effect"
attribute = "light"
race = "fairy"
link-rating = 1
link-arrows = "bottom"
atk = 0
effect = """\
1 Normal Summoned "Palladium" monster
This card's Link Summon cannot be negated. \
When Link Summoned, your opponent cannot activate cards or effects. \
If this card is Link Summoned: \
    You can target up to 3 monsters in your GY; \
    this turn, this card gains ATK equal to the combined ATK of those monsters. \
Cannot attack. \
This card can be treated as 3 Tributes for the Tribute Summon of a Divine-Beast monster. \
    This effect cannot be negated. \
If you Tribute this card for the Tribute Summon of a Divine-Beast monster, \
    that monster gains the following effects, depending on its original name; \
    You can only use this effect of "Emissary of the Divine Beasts" once per turn.
● "Obelisk the Tormentor": If this card is Normal Summoned: You can add 1 "Fist of Fate" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
● "Slifer the Sky Dragon": If this card is Normal Summoned: You can add 1 "Thunderforce Attack" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
● "The Winged Dragon of Ra": If this card is Normal Summoned: You can add 1 "De-Fusion" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
"""
strings = [
    "Search \"Fist of Fate\"",
    "Search \"Thunderforce Attack\"",
    "Search \"De-Fusion\"",
]

[card.egyptian-god-slime-2]
id = 900000101
name = "Egyptian God Slime 2"
type = "monster fusion effect"
attribute = "water"
race = "aqua"
level = 10
atk = 2000
def = 2000
effect = """\
1 Aqua monster + 1 Level 10 WATER monster
Must first be either Fusion Summoned, or Special Summoned from your Extra Deck \
    by Tributing 1 Level 10 Aqua monster with 0 ATK. \
This card can be treated as 1 or 3 Tributes for the Tribute Summon of a monster. \
Cannot be targeted by card effects. \
Monsters your opponent controls with less ATK than this card cannot attack, \
    also they cannot activate their effects. \
"""
strings = []
name-color = "black"

[card.egyptian-god-slime-3]
id = 900000102
name = "Egyptian God Slime 3"
type = "monster fusion effect"
attribute = "water"
race = "aqua"
level = 10
atk = 3300
def = 1800
effect = """\
1 Aqua monster + 1 Level 10 WATER monster
Must first be either Fusion Summoned, or Special Summoned from your Extra Deck \
    by Tributing 1 Level 10 Aqua monster with 0 ATK. \
This card can be treated as 1 or 3 Tributes for the Tribute Summon of a monster. \
Cannot be destroyed by card effects. \
While this card is in Defense Position, you take no damage. \
"""
strings = []
name-color = "black"

[card.the-divine-name]
id = 900000200
name = "The Divine Name"
type = "spell"
effect = """\
This card's activation and effect cannot be negated. \
Declare 1 card name; excavate the top card of your Deck, \
    and if it is the declared card, add it to your hand, \
    then you can add to your hand, or Special Summon, \
    1 DIVINE monster from your Deck or GY. \
    Otherwise, send it to the GY. \
    You can only activate 1 "The Divine Name" per turn. \
During your Standby Phase, \
    reveal this card in your hand and look at the top card of your Deck. \
    You can only use this effect of "The Divine Name" once per turn. \
During your Main Phase, while you control 3 monsters whose original names are \
    "Slifer the Sky Dragon", "Obelisk the Tormentor", and "The Winged Dragon of Ra": \
    You can banish this card from your GY; \
    Add 1 "Holactie the Creator of Light" from your Deck, GY or Outside to your hand. \
    Cards and effects cannot be activated in response to this effect's activation. \
    You can only use this effect of "The Divine Name" once per Duel. \
"""
strings = ["Take a DIVINE monster"]

[card.divine-servant]
id = 900000201
name = "Divine Servant"
type = "spell quick-play"
effect = """\
During the Main Phase or Battle Phase: \
    Immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster, \
    or, if you control 3 or more monsters with different names, \
    you can add 1 "Slifer the Sky Dragon", "Obelisk the Tormentor", or "The Winged Dragon of Ra" \
    from your Deck to your hand, then, immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster. \
    When you do, you can Tribute a monster(s) your opponent controls, even though you do not control them. \
    You can only activate 1 "Divine Servant" per turn. \
    This card's activation and effect cannot be negated. \
During your Main Phase: \
    You can shuffle this card from your GY into the Deck, and if you do, \
    you can Normal Summon 1 Divine-Beast monster during your Main Phase this turn, in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
    You can only use this effect of "Divine Servant" once per turn. \
"""
strings = ["Summon via \"Divine Servant\""]

[card.divine-evolution]
id = 900000202
alias = 7373632
name = "Evolution of Divine-Beast"
type = "spell"
effect = """\
(This card's name is always treated as "Divine Evolution".)
This card's activation and effect cannot be negated. \
Choose 1 monster you control \
    whose original Attribute is DIVINE monster with Divine Hierarchy, \
    except a monster(s) already increased its Divine Hierarchy by card effects, \
    its Divine Hierarchy is increased by 1, \
    its effect activations and its activated effects cannot be negated, \
    it gains 1000 ATK/DEF, \
    also it gains these effects. \
    These changes ignoring its effects.
● When this card declares an attack: You can make your opponent send 1 monster they control to the GY (their choice)
During your Main Phase: \
    You can shuffle this card from your GY into the Deck, and if you do, \
    add 1 monster Level 10 from your GY to your hand. \
    You can only use this effect of "Evolution of Divine-Beast" once per turn. \
"""
strings = ["Affected by effect of \"Evolution of Divine-Beast\""]
