[card.millennium-hieroglyph]
id = 900000000
name = "Millennium Hieroglyph"
strings = [
    "Go to next turn",
    "Move monster",
    "Return banished cards to the GY",
    "Return cards to Deck",
    "Reset game",
]

[card.obelisk]
id = 900000001
alias = 10000000
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|Obelisk the Tormentor}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Warrior-Type while it is on the field. \
Once per turn, during the Main Phase or Battle Phase, \
    while this card is able to attack and did not declare an attack this turn (Quick Effect): \
    You can Tribute 2 other monsters, then activate 1 of these effects. \
    This card must be Attack Position to activate and to resolve these effects, \
    also it cannot attack for the rest of this turn.
● Inflict damage to your opponent equal to this card's ATK, \
    and if you do, destroy all monsters your opponent controls.
● This card attacks 1 face-up monster your opponent control, \
    and if you do, it gain ∞ ATK during that damage calculation only. \
    The total monster's Divine Hierarchy on the field must be 3 or more to activate this card's effect.
"""
strings = ["Damage & destroy", "Gain ∞ ATK & make a attack"]

[card.osiris]
id = 900000002
alias = 10000020
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Dragon-Type while it is on the field. \
This card's original ATK and DEF are each equal to the number of cards in your hand x X000. \
    (X is its Divine Hierarchy). \
If a monster(s) is Summoned to your opponent's field, \
    or control of a monster(s) changes to your opponent, \
    while this card is able to attack: \
    Target that monster(s), ignoring card effects; \
    it loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK or DEF is 0, destroy it, \
    that monster(s) cannot activate its effects in response to this effect's activation. \
    This card must be face-up Attack Position on the field to activate and to resolve this effect. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[card.ra]
id = 900000003
alias = 10000010
name = "Sun Divine Beast of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also Winged-Beast-Type while it is on the field. \
"""
strings = []

[card.ra-sphere]
id = 900000004
alias = 10000080
name = "Sun Divine Beast of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
If your "The Winged Dragon of Ra" is Normal Summoned to your opponent's field, \
    and they do not own "Ancient Chant", \
    Dimension Change it to this card with the same Divine Hierarchy. \
${EGYPTIAN_EFFECT} \
This card is also Machine-Type while it is on the field. \
Cannot attack. \
Neither player can target this card for attacks or by card effects, \
    but does not prevent your opponent from attacking you directly. \
While this card is in your Dimension Zone: \
    You can Normal Summon "The Winged Dragon of Ra" to your opponent's field, \
    but you cannot activate the following effect until the end of this turn. \
Once per turn: The original owner of this card can send it to the Dimension Zone; \
    Dimension Summon the Dimension Material Monster (it's Divine Hierarchy is the same as with this card's), \
    its original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field, or 4000/4000, \
    also it is unaffected by card effects that prevent it from attacking, also its attacks cannot be negated. \
    Cards and effects cannot be activated in response to this effect's activation. \
If you Normal Summon "The Winged Dragon of Ra", it gains the following effects.
● This card's original ATK/DEF become the combined ATK/DEF of the monsters Tributed for its Tribute Summon had on the field.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
"""
strings = [
    "Your field",
    "Opponent's field",
    "Cannot activate \"Sun Divine Beast of Ra - Sphere Mode\"'s effects",
    "Turn back to Normal Form",
    "Unstoppable Attack",
]

[card.ra-phoenix]
id = 900000005
alias = 10000090
name = "Sun Divine Beast of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
${EGYPTIAN_EFFECT} \
This card is also Pyro-Type while it is on the field. \
Cannot attack unless attack directly, but must pay 1000 LP. \
Unaffected by other card effects that prevent it from attacking, also its attacks cannot be negated. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy. \
You take no Battle Damage from battles involving this card. \
Once per Chain (Quick Effect): \
    You can pay 1000 LP, then target 1 other monster on the field; \
    send it to the GY, ignoring card effects. \
During the End Phase, \
    Dimension Change this card to 1 "The Winged Dragon of Ra - Sphere Mode" \
    with the same Divine Hierarchy (transfer materials to it), \
    or send it to the GY. \
If you Special Summon "The Winged Dragon of Ra" in Attack Position from the GY, \
    you can Dimension Change it to this card with the same Divine Hierarchy, \
    or you can pay LP so that you only have 100 left; it gains the following effects.
● This card become Fusion Monster and its original ATK/DEF become equal to the amount of LP paid, \
    and also, any increase in LP is changed to increase it's original ATK/DEF instead.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated.
● When an attack is declared involving this card: You can Tribute any number of other face-up monsters; \
    this card gains ATK equal to the Tributed monsters' combined original ATK had on the field, \
    until the end of this turn.
● After damage calculation, if it attacked, send all monsters your opponent controls to the GY.
● If "De-Fusion" targets this card, apply \
    "that target loses its above effects and its ATK/DEF become 0, \
    and if it do, its controller gains LP equal to that lost ATK" instead of. \
    This effect's activation and effect cannot be negated.
"""
strings = [
    "Do nothing",
    "Life Point Transfer",
    "Immortal Phoenix Form",
    "Send monster to grave",
    "Return to Dimension",
    "Tribtue monsters for ATK",
]

[card.dreadroot]
id = 900000006
alias = 62180201
name = "Wicked God Dreadroot"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Dreadroot}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also DARK Fiend monster while it is on the field. \
The ATK/DEF of all other monsters on the field are halved. \
Negate the effects of monsters destroyed by battle with it. \
"""
strings = []

[card.eraser]
id = 900000007
alias = 57793869
name = "Wicked God Eraser"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Eraser}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also DARK Fiend monster while it is on the field. \
This card's original ATK and DEF are each equal to the number of cards your opponent controls x X000. \
    (X is its Divine Hierarchy). \
During your Main Phase: You can destroy this card. \
If this card is sent from the field to the GY, \
    send all cards on the field to the GY, except 1 face-up monster you control. \
"""
strings = ["Destroy itself"]

[card.avatar]
id = 900000008
alias = 21208154
name = "Wicked God Avatar"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Wicked Avatar}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_SPSUMMON_EFFECT} \
This card is also DARK Fiend monster while it is on the field. \
If this card is Normal Summoned: \
    Your opponent cannot activate Spell/Trap Cards until the end of their 2nd turn after this effect's activation. \
This card's ATK/DEF are equal to the highest ATK on the field +100, except "The Wicked Avatar". \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, \
    and you take no battle damage from that battle. \
You take no effect damage. \
"""
strings = [
    "Affected by effect \"Wicked God Avatar\": cannot activate Spell/Trap Cards",
]

[card.emissary-divine-beast]
id = 900000009
name = "Emissary of the Divine Beasts"
type = "monster link effect"
attribute = "light"
race = "fairy"
link-rating = 1
link-arrows = "bottom"
atk = 0
effect = """\
1 "Palladium" monster
This card's Link Summon cannot be negated. \
When Link Summoned, your opponent cannot activate cards or effects. \
If this card is Link Summoned: \
    You can target up to 3 monsters in your GY; \
    this turn, this card gains ATK equal to the combined ATK of those monsters. \
Cannot attack. \
This card can be treated as 3 Tributes for the Tribute Summon of a Divine-Beast monster. \
    This effect cannot be negated. \
During your Main Phase, you can Normal Summon 1 Divine-Beast monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
If you Tribute this card for the Tribute Summon of a Divine-Beast monster, \
    that monster gains the following effects, depending on its original name; \
    You can only use this effect of "Emissary of the Divine Beasts" once per turn.
● "Obelisk the Tormentor": If this card is Normal Summoned: You can add 1 "Fist of Fate" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
● "Slifer the Sky Dragon": If this card is Normal Summoned: You can add 1 "Thunderforce Attack" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
● "The Winged Dragon of Ra": If this card is Normal Summoned: You can add 1 "De-Fusion" to your hand, \
    from your Deck, GY or Outside (if you do not own any.)
"""
strings = [
    "Summon via \"Emissary of the Divine Beasts\"",
    "Search \"Fist of Fate\"",
    "Search \"Thunderforce Attack\"",
    "Search \"De-Fusion\"",
]

[card.the-divine-name]
id = 900000010
name = "The Divine Name"
type = "spell"
effect = """\
This card's activation and effect cannot be negated. \
Declare 1 card name; excavate the top card of your Deck, \
    and if it is the declared card, add it to your hand, \
    then you can add to your hand, or Special Summon, \
    1 DIVINE monster from your Deck or GY. \
    Otherwise, send it to the GY. \
    You can only activate 1 "The Divine Name" per turn. \
During your Standby Phase, \
    reveal this card in your hand and look at the top card of your Deck. \
    You can only use this effect of "The Divine Name" once per turn. \
During your Main Phase, while you control 3 monsters whose original names are \
    "Slifer the Sky Dragon", "Obelisk the Tormentor", and "The Winged Dragon of Ra": \
    You can banish this card from your GY; \
    Add 1 "Holactie the Creator of Light" from your Deck, GY or Outside to your hand. \
    Cards and effects cannot be activated in response to this effect's activation. \
    You can only use this effect of "The Divine Name" once per Duel. \
"""
strings = ["Take a DIVINE monster"]

[card.divine-servant]
id = 900000011
name = "Divine Servant"
type = "spell quick-play"
effect = """\
This card's activation and effect cannot be negated. \
During the Main Phase or Battle Phase: Activate 1 of these effects; \
You can only activate 1 "Divine Servant" per turn.
● Immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster, \
    or, if you control 3 or more monsters with different names, \
    you can add 1 Divine-Beast monster from your Deck to your hand, then, \
    immediately after this effect resolves, Tribute Summon 1 Divine-Beast monster. \
    When you do, you can Tribute a monster(s) your opponent controls, even though you do not control them.
● Choose 1 monster you control \
    whose original Type is Divine-Beast monster and have Divine Hierarchy, \
    except a monster(s) already affected by "Divine Servant", \
    its Divine Hierarchy is increased by 1, \
    its effect activations and its activated effects cannot be negated, \
    it gains 1000 ATK/DEF. \
    These changes ignoring its effects. \
"""
strings = ["Summon Divine-Beast", "Evolute Divine-Beast"]
