[set.blue-eyes]
code = 0xdd

[set.chaos]
code = 0xcf

[set.elemental-hero]
code = 0x3008

[set.evil-hero]
code = 0x6008

[set.fusion]
code = 0x46

[set.hero]
code = 0x8

[set.junk]
code = 0x43

[set.kuriboh]
code = 0xa4

[set.majestic]
code = 0x3f

[set.neo-spacian]
code = 0x1f

[set.neos]
code = 0x9

[set.odd-eyes]
code = 0x99

[set.palladium]
code = 0x13a

[set.pendulum]
code = 0xf2

[set.red-eyes]
code = 0x3b

[set.rose-dragon]
code = 0x1123

[set.stardust]
code = 0xa3

[set.supreme-king]
code = 0xf8

[set.synchron]
code = 0x1017
