[set.blue-eyes]
code = 0xdd

[set.chaos]
code = 0xcf

[set.clear-wing]
code = 0xff

[set.elemental-hero]
code = 0x3008

[set.evil-hero]
code = 0x6008

[set.fusion]
code = 0x46

[set.fusion-dragon]
code = 0x1046

[set.dododo]
code = 0x82

[set.gagaga]
code = 0x54

[set.galaxy]
code = 0x7b

[set.gogogo]
code = 0x59

[set.hero]
code = 0x8

[set.junk]
code = 0x43

[set.kuriboh]
code = 0xa4

[set.magician]
code = 0x98

[set.majestic]
code = 0x3f

[set.neo-spacian]
code = 0x1f

[set.neos]
code = 0x9

[set.number]
code = 0x48

[set.number-c]
code = 0x1048

[set.number-c39]
code = 0x5048

[set.numeron]
code = 0x14b

[set.odd-eyes]
code = 0x99

[set.onomat]
code = 0x139

[set.palladium]
code = 0x13a

[set.pendulum]
code = 0xf2

[set.pendulum-dragon]
code = 0x10f2

[set.photon]
code = 0x55

[set.predaplant]
code = 0x10f3

[set.venom]
code = 0x50

[set.rank-down-magic]
code = 0x15d

[set.rank-up-magic]
code = 0x95

[set.rebellion]
code = 0x13b

[set.red-eyes]
code = 0x3b

[set.rose-dragon]
code = 0x1123

[set.stardust]
code = 0xa3

[set.starving-venom]
code = 0x1050

[set.supreme-king]
code = 0xf8

[set.supreme-king-dragon]
code = 0x20f8

[set.supreme-king-gate]
code = 0x10f8

[set.synchro]
code = 0x1017

[set.synchro-dragon]
code = 0x2017

[set.utopia]
code = 0x107f

[set.utopic]
code = 0x7f

[set.xyz]
code = 0x73

[set.xyz-dragon]
code = 0x2073

[set.zexal]
code = 0x7e

[set.zs]
code = 0x207e

[set.zubaba]
code = 0x8f

[set.zw]
code = 0x107e