[set.aesir]
code = 0x4b

[card.odin]
id = 410000010
alias = 93483212
name = "Odin the Allfather of Aesir"
type = "monster effect synchro"
attribute = "divine"
race = "creator-god"
level = 10
atk = 4000
def = 3500
effect = """\
${HIERARCHY_ALIAS|3|Odin, Father of the Aesir}
"""
strings = [
]

[card.thor]
id = 410000011
alias = 30604579
name = "Thor the Aesir of Thunder"
type = "monster effect synchro"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 3500
def = 2800
effect = """\
${HIERARCHY_ALIAS|1|Thor, Lord of the Aesir}
"""
strings = [
]

[card.loki]
id = 410000012
alias = 67098114
name = "Loki the Aesir of Mischief"
type = "monster effect synchro"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 3300
def = 3000
effect = """\
${HIERARCHY_ALIAS|1|Loki, Lord of the Aesir}
"""
strings = [
]

[card.freyja]
id = 410000013
name = "Freyja the Mother of the Aesir"
set = "aesir"
type = "monster effect synchro"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "3800"
def = "3700"
effect = """\
${HIERARCHY|2}
"""
strings = [
]