[card.blue-eyes-light-dragon]
id = 911000000
alias = 89631139
set = "blue-eyes"
name = "Blue-Eyes Light Dragon"
type = "monster normal"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Blue-Eyes White Dragon".)
You can Special Summon this card (from your hand) by revealing 1 Level 1 LIGHT Tuner in your hand. \
    You can only Special Summon "Blue-Eyes Light Dragon" once per turn this way. \
Once per turn: You can target 1 monster your opponent controls; \
    destroy it. This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy 1 monster"]

[card.blue-eyes-divine-dragon]
id = 911000001
set = "blue-eyes"
name = "Blue-Eyes Divine Dragon"
type = "monster fusion effect"
attribute = "light"
race = "dragon"
level = 12
atk = 4500
def = 3800
effect = """\
"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"
Must first be Fusion Summoned with the above materials. \
Cannot be Tributed, or be used as a material for an Summon by your opponent. \
Cannot be destroyed by card effects. Your opponent cannot target it with card effects. \
"""
strings = []