[set.blue-eyes]
code = 0xdd

[card.blue-eyes-white-dragon]
id = 410000201
alias = 89631139
name = "Blue-Eyes Sacred White Dragon"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card is also always treated as "Blue-Eyes White Dragon", also Normal Monster.)
You can Special Summon this card (from your hand or GY) by Tributing 1 Level 1 LIGHT Tuner in your hand or on your field. \
    You can only Special Summon "Blue-Eyes Sacred White Dragon" once per turn this way. \
Once per turn: You can target 1 monster your opponent controls; destroy it. \
    This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy a monster"]

[card.blue-eyes-divinity-dragon]
id = 410000202
set = "blue-eyes"
name = "Blue-Eyes Divinity Dragon"
type = "monster fusion effect"
attribute = "light"
race = "dragon"
level = 12
atk = 5000
def = 4500
effect = """\
"Blue-Eyes White Dragon" + 4 "Blue-Eyes" Dragon monsters
Must be Fusion Summoned with the above Fusion Materials. \
"""
strings = []

[card.blue-eyes-holy-dragon]
id = 410000203
set = "blue-eyes"
name = "Blue-Eyes Holy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 9
atk = 3000
def = 2500
effect = """\
1 Level 1 LIGHT Tuner + 1 non-Tuner "Blue-Eyes" Dragon monster
"""
strings = []

[card.blue-eyes-savior-dragon]
id = 410000204
set = "blue-eyes"
name = "Blue-Eyes Savior Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
level = 8
atk = 0
def = 0
effect = """\
2 Level 8 "Blue-Eyes" Dragon monsters
You can also Xyz Summon this card by using a "Blue-Eyes White Dragon" you control as the material. \
"""
strings = ["Xyz Summon by using a \"Blue-Eyes White Dragon\""]
