[card.blue-eyes-light-dragon]
id = 911000000
alias = 89631139
set = "blue-eyes"
name = "Blue-Eyes Light Dragon"
type = "monster normal"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Blue-Eyes White Dragon".)
You can Special Summon this card (from your hand) by revealing 1 Level 1 LIGHT Tuner in your hand. \
    You can only Special Summon "Blue-Eyes Light Dragon" once per turn this way. \
Once per turn: You can target 1 monster your opponent controls; \
    destroy it. This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy 1 monster"]

[card.blue-eyes-divine-dragon]
id = 911000001
set = "blue-eyes"
name = "Blue-Eyes Divine Dragon"
type = "monster fusion effect"
attribute = "light"
race = "dragon"
level = 12
atk = 4500
def = 3800
effect = """\
"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"
Must first be Fusion Summoned with the above materials. \
Cannot be Tributed, or be used as a material for an Summon by your opponent. \
Cannot be destroyed by card effects. Your opponent cannot target it with card effects. \
If this card attacks, your opponent cannot activate cards or effects until the end of the Damage Step. \
Once per turn, at the end of the Damage Step, if this card attacked: \
    This card can make a second and third attack during each Battle Phase this turn. \
    Other monsters cannot attack during the turn you activate this effect. \
Once per turn: You can target up to 3 cards your opponent controls; destroy them. \
    This card cannot attack the turn this effect is activated. \
"""
strings = [
    "Can make a second and third attack",
    "Make second and third attack",
    "Destroy up to 3 cards",
]

[card.blue-eyes-holy-dragon]
id = 911000002
set = "blue-eyes"
name = "Blue-Eyes Holy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 9
atk = 3000
def = 2500
effect = """\
1 Tuner + 1 non-Tuner "Blue-Eyes" monsters
Must first be Synchro Summoned. \
When your opponent activates a card or effect that targets a "Blue-Eyes" monster(s) you control (Quick Effect): \
    You can negate that effect. \
"""
strings = []

[card.blue-eyes-deep-dragon]
id = 911000003
set = "blue-eyes"
name = "Blue-Eyes Deep Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 8
atk = 0
def = 0
effect = """\
"""
strings = []

[card.chaos-eyes-azure-dragon]
id = 911000004
set = "chaos blue-eyes"
name = "Chaos-Eyes Azure Dragon"
type = "monster link effect"
attribute = "light"
race = "dragon"
link-rating = 2
link-arrows = "bottom-left bottom-right"
atk = 4000
effect = """\
(This card is always treated as a "Blue-Eyes" card.)
"""
strings = []
