[set.blue-eyes]
code = 0xdd

[card.blue-eyes-white-dragon]
id = 410000201
alias = 89631139
name = "Blue-Eyes Sacred White Dragon"
type = "monster effect"
attribute = "light"
race = "dragon"
level = 8
atk = 3000
def = 2500
effect = """\
(This card's name is always treated as "Blue-Eyes White Dragon". This card is always treated as a Normal Monster.)
You can Special Summon this card (from your hand) by Tributing 1 Level 1 LIGHT Tuner in your hand or on your field. \
    You can only Special Summon "Blue-Eyes Sacred White Dragon" once per turn this way. \
Once per turn: You can target 1 monster your opponent controls; destroy it. \
    This card cannot attack the turn this effect is activated. \
"""
strings = ["Destroy a monster"]
