[card.obelisk]
id = 910000001
alias = 10000000
name = "Giant Divine Soldier of Obelisk"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|Obelisk the Tormentor}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Warrior-Type while on the field. \
When a card or effect is activated that targets this card, negate that effect. \
Once per turn, during your Main Phase or your opponent's Battle Phase, while this card is able to attack (Quick Effect): \
    You can Tribute 2 other monsters; destroy all monsters your opponent controls. \
"""
strings = ["Destroy all monsters your opponent controls"]

[card.osiris]
id = 910000002
alias = 10000020
name = "Sky Divine Dragon of Osiris"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|Slifer the Sky Dragon}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Dragon-Type while on the field. \
The original ATK and DEF of this card each become equal to the number of cards in your hand x X000. (X is this card Divine Hierarchy.) \
If a monster(s) is Summoned to your opponent's field, while this card is able to attack: \
    That monster(s) loses 2000 ATK or DEF depending on its battle position, \
    then if its ATK or DEF has been reduced to 0 as a result, destroy it, \
    that monster(s) cannot activate its effects in response to this effect's activation. \
"""
strings = ["Reduce the monster(s)' ATK or DEF"]

[card.ra]
id = 910000003
alias = 10000010
name = "Winged Divine Beast of Ra"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Winged Dragon of Ra}
${EGYPTIAN_SUMMON} \
${EGYPTIAN_EFFECT} \
${EGYPTIAN_LIMIT} \
This card is also Winged-Beast-Type while on the field. \
"""
strings = []

[card.ra-sphere]
id = 910000004
alias = 10000080
name = "Winged Divine Beast of Ra - Sphere Mode"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Sphere Mode".)
Immediately after "The Winged Dragon of Ra" is Normal Summoned, \
    Dimension Change it to this card in the same battle position and Divine Hierarchy. \
${EGYPTIAN_EFFECT} \
This card is also Machine-Type while on the field. \
Cannot attack. \
Neither player can target this card for attacks or by card effects. \
Once per turn: The turn player can send this card to the Dimension Zone; \
    Dimension Summon the Dimension Material Monster, ignoring its Summoning conditions (it's Divine Hierarchy is the same as with this card's) \
    and if they do, it gains these effects. \
    Cards and effects cannot be activated in response to this effect's activation. \
    Only the original owner of this card can use this effect.
● The original ATK/DEF of this card become the combined original ATK/DEF of the monsters Tributed for its Tribute Summon, \
    if the combined ATK/DEF is 0/0 then it become 4000/4000.
● Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated. \
"""
strings = ["Turn back to Standard mode", "Unstoppable Attack"]

[card.ra-phoenix]
id = 910000005
alias = 10000080
name = "Winged Divine Beast of Ra - Immortal Phoenix"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "The Winged Dragon of Ra - Immortal Phoenix".)
During the Main or Battle Phase, \
    you can Dimension Change "The Winged Dragon of Ra" you control that was Special Summoned from the GY and did not declare an attack this turn \
    to this card in the same battle position, Divine Hierarchy. \
${EGYPTIAN_EFFECT} \
This card is also Pyro-Type while on the field. \
Cannot be destroyed by battle with a monster with lower Divine Hierarchy, also you take no battle damage from that battle. \
Unaffected by card effects that prevent it from attacking, also its attacks cannot be negated. \
When an attack is declared involving this card: You can Tribute any number of other monsters that did not declare an attack this turn; \
    this card gains ATK equal to the Tributed monsters' combined original ATK. \
After damage calculation, if this card attacked, send all monsters your opponent controls to the GY. \
Once per turn (Quick Effect): You can pay LP so that you only have 1 left; This card gains original ATK/DEF equal to the amount of LP paid, \
    and also, during this turn, while this card is on the field, any increase in LP is changed to increase it's ATK/DEF instead. \
    Cards and effects cannot be activated in response to this effect's activation. \
Once per Chain, during your Main Phase (Quick Effect): You can pay 1000 LP, \
    then send 1 other monster on the field with the same or lower Divine Hierarchy to the GY, ignoring card effects. \
During the End Phase, \
    Dimension Change this card to "The Winged Dragon of Ra - Sphere Mode" Dimension Monster in Defense Position \
    (it's Divine Hierarchy is the same as with this card's, transfer materials to it.) \
    if you don't, send this card to the GY. \
"""
strings = [
    "Tribtue monsters for ATK/DEF",
    "Life Point transfer",
    "Send 1 monster to the GY",
    "Return to Dimension",
]

[card.obelisk-max]
id = 910000006
alias = 10000000
name = "Giant Divine Soldier of Obelisk - Soul Energy MAX"
type = "monster dimension effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
(This card's name is always treated as "Obelisk the Tormentor".)
During the Battle Phase, \
    you can Dimension Change "Obelisk the Tormentor" you control that is able to attack this turn \
    to this card in the same battle position, Divine Hierarchy and original ATK/DEF, \
    by Tributing 2 face-up monsters you control. \
At the end of the Battle Phase, Dimension Change it to the Dimension Material Monster \
    in the same battle position, Divine Hierarchy and original ATK/DEF. \
${EGYPTIAN_EFFECT} \
This card is also Warrior-Type while on the field. \
When a card or effect is activated that targets this card, negate that effect. \
If this card battles, it gain ∞ ATK during damage calculation only. \
"""
strings = ["Gain ∞ ATK"]
