[macro]
ALIAS = """(This card's name is always treated as "$1". This card's base Divine Hierarchy is $2.)"""
RACE = """This card is also a $3 monster while face-up on the field."""
DIVINE_EFFECT = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Cannot be Tributed by your opponent, or be used as a material for a Summon by your opponent. \
Cannot be flipped face-down. \
Control of this card cannot be switched. \
Unaffected by other card effects that would make this card leave the field and other card effects are only applied on this card for 1 turn\
    , except for card with the same or higher Divine Hierarchy. \
Once per turn, during the End Phase, if this card was Special Summoned from the GY or Banished Zone: Send it to the GY.\
"""

[card.obelisk]
id = 410000001
ot = 32
alias = 10000000
name = "Obelisk the Giant Divine Soldier"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${ALIAS|Obelisk the Tormentor|1}
${DIVINE_EFFECT} \
${RACE|Warrior/Rock} \
When a card or effect is activated that targets this card (Quick Effect): You can negate that effect. \
Once per turn (Quick Effect): You can Tribute 2 other monsters; destroy all monsters your opponent controls\
    , and if you do, inflict damage equal to the ATK of this card to your opponent. \
    This card cannot declare an attack the turn this effect is activated.\
"""
strings = [
    "Destroy all monsters your opponent controls",
]

[card.slifer]
id = 410000002
ot = 32
alias = 10000020
name = "Slifer the Sky Divine Dragon"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|Slifer the Sky Dragon|1}
${DIVINE_EFFECT} \
${RACE|Dragon/Thunder} \
The original ATK/DEF of this card each become equal to the number of cards in your hand x 1000. \
If a monster(s) is Summoned to your opponent's field in face-up Position: That monster(s) loses 2000 ATK if it is in face-up Attack Position, but 2000 DEF if it is in face-up Defense Position\
    , then if its ATK or DEF has been reduced to 0 as a result, destroy it. \
    Also your opponent cannot activate those monster(s) effects in response to this effect's activation.\
"""
strings = [
    "Reduce the monster(s)' ATK or DEF",
]

[card.ra]
id = 410000003
ot = 32
alias = 10000010
name = "Ra the Sun Divine Phoenix"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|The Winged Dragon of Ra|2}
${DIVINE_EFFECT} \
${RACE|Winged-Beast/Pyro}\
"""
strings = []

[card.ra_sphere]
id = 410000004
ot = 32
alias = 10000080
name = "Ra the Sun Divine Sphere"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|The Winged Dragon of Ra - Sphere Mode|2}
${DIVINE_EFFECT} \
${RACE|Winged-Beast/Pyro}\
"""
strings = []

[card.ra_phoenix]
id = 410000005
ot = 32
alias = 10000090
name = "Ra the Sun Divine Immortal Phoenix"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|The Winged Dragon of Ra - Immortal Phoenix|2}
${DIVINE_EFFECT} \
${RACE|Winged-Beast/Pyro}\
"""
strings = []