[card.millennium-hieroglyph]
id = 400000000
name = "Millennium Hieroglyph"
strings = [
    "Do nothing",
    "Go to next turn",
    "Move monster",
    "Return all banished cards to the GY",
    "Search Field and Continuos",
    "Return cards to Deck",
    "Reset game",
]

[card.forbidden-polymerization]
id = 400000001
alias = 24094653
name = "Forbidden Polymerization"
type = "spell ritual"
effect = """\
(This card's name is always treated as "Polymerization".)
During your Main Phase, if this card is in your GY, except the turn this card was sent to the GY: \
    You can discard 1 Spell; add this card to your hand. \
Activate 1 of the following effects.
● Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters from your hand or field as Fusion Material, \
    you can also banish monster from your GY as Fusion Material.
● Ritual Summon 1 Ritual Monster from your hand, \
    by Tributing monsters from your hand or field and/or banish monster from your GY, \
    whose total Levels equal or exceed the Level of the Ritual Monster.
"""
strings = ["Fusion Summon", "Ritual Summon"]
