[card.millennium-hieroglyph]
id = 400000000
name = "Millennium Hieroglyph"
strings = [
    "Do nothing",
    "Go to next turn",
    "Move monster",
    "Return banished cards to the GY",
    "Search Field and Continuos",
    "Return cards to Deck",
    "Reset game",
]

[card.forbidden-polymerization]
id = 400000001
alias = 24094653
name = "Forbidden Fusion"
type = "spell"
effect = """\
(This card's name is always treated as "Polymerization".)
You can discard 1 card when activating this card, and if you do, \
    neither player can activate cards or effects in response to this card's activation. \
Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters from your hand or field as Fusion Material, \
    you can also banish monster from your GY as Fusion Material. \
During your Main Phase, if this card is in your GY: \
    You can discard 1 Spell; add this card to your hand. \
    You can only use this effect of "Forbidden Fusion" once per turn. \
"""
strings = ["Discard 1 card?"]
