[card.millennium-hieroglyph]
id = 400000000
name = "Millennium Hieroglyph"
strings = [
    "Immunity by \"Millennium Hieroglyph\"",
    "Go to next turn",
    "Create card",
    "Protect card",
    "Move monster",
    "Reset game",
    "Add cards to you hand",
    "Send cards to the GY",
    "Return cards to the Deck",
    "Add cards to Extra Deck face-up"
]

[card.hyper-polymerization]
id = 400000001
alias = 24094653
name = "Hyper Polymerization"
type = "spell"
effect = """\
(This card's name is always treated as "Polymerization").
Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Material, you can also banish monster from your GY as Fusion Material. \
    Your opponent cannot activate cards or effects in response to this card's activation. \
During your Main Phase, if this card is in your GY, except the turn this card was sent to the GY: You can discard 1 Spell; add this card to your hand.\
"""

[card.divine-reborn]
id = 400000002
alias = 83764718
name = "Divine Reborn"
type = "spell quick-play"
effect = """\
(This card's name is always treated as "Monster Reborn").
Target 1 monster in either GY; Special Summon it.
"""