[card.millennium-hieroglyph]
id = 900000000
name = "Millennium Hieroglyph"
strings = [
    "Do nothing",
    "Go to next turn",
    "Move monster",
    "Return banished cards to the GY",
    "Return cards to Deck",
    "Reset game",
    "Place Continuous"
]

[card.forbidden-polymerization]
id = 900000001
alias = 24094653
name = "Forbidden Fusion"
type = "spell"
effect = """\
(This card's name is always treated as "Polymerization".)
Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters from your hand or field as Fusion Material, \
    and if using 3 or more materials, that monster cannot be destroyed by card effects. \
    Neither player can activate cards or effects in response to this card's activation. \
During your Main Phase, if this card is in your GY: \
    You can discard 1 Spell; add this card to your hand. \
    You can only use this effect of "Forbidden Fusion" once per turn. \
"""
strings = []
