[macro]
ALIAS = """(This card's name is always treated as "$1". This card's base Divine Hierarchy is $2.$3)"""
3_TRIBUTE_SUMMON = """\
Requires 3 Tributes to Normal Summon (cannot be Normal Set). \
This card's Normal Summon cannot be negated.\
"""
EGYPTIAN = """\
This card's activation and effects cannot be negated. \
Cannot be Tributed by your opponent, or be used as a material for a Summon by your opponent. \
Cannot be flipped face-down. \
Control of this card cannot be switched. \
Unaffected by your opponent's monster effects, other cards' effects that would make this card leave the field, and other cards' effects are only applied on this card for 1 turn, \
    except effects from card with the same or higher Divine Hierarchy.\
"""
EGYPTIAN_LIMIT = """\
This card cannot activate its effect or attack during the turn it is Special Summoned. \
Once per turn, during the End Phase, if this card was Special Summoned from the GY: Send it to the GY.\
"""
RACE = """This card is also a $4 monster while face-up on the field."""

[card.obelisk]
id = 410000001
ot = 32
alias = 10000000
name = "Obelisk the Giant Divine Soldier"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${ALIAS|Obelisk the Tormentor|1|}
${3_TRIBUTE_SUMMON} \
${EGYPTIAN} \
${EGYPTIAN_LIMIT} \
${RACE|Warrior/Rock} \
Your opponent cannot target this card with card effects. \
Once per turn (Quick Effect): You can Tribute 2 other monsters; destroy all monsters your opponent controls, \
    and if you do, inflict damage equal to the ATK of this card to your opponent. \
    This card cannot declare an attack the turn this effect is activated.\
"""
strings = [
    "Destroy all monsters your opponent controls",
]

[card.slifer]
id = 410000002
ot = 32
alias = 10000020
name = "Slifer the Sky Divine Dragon"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|Slifer the Sky Dragon|1|}
${3_TRIBUTE_SUMMON} \
${EGYPTIAN} \
${EGYPTIAN_LIMIT} \
${RACE|Dragon/Thunder} \
The original ATK/DEF of this card each become equal to the number of cards in your hand x 1000. \
If a monster(s) is Summoned to your opponent's field in face-up Position: \
    That monster(s) loses 2000 ATK if it is in face-up Attack Position, but 2000 DEF if it is in face-up Defense Position, \
    then if its ATK or DEF has been reduced to 0 as a result, destroy it. \
    Also your opponent cannot activate those monster(s) effects in response to this effect's activation.\
"""
strings = [
    "Reduce the monster(s)' ATK or DEF",
]

[card.ra]
id = 410000003
ot = 32
alias = 10000010
name = "Ra the Sun Divine Phoenix"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|The Winged Dragon of Ra|2|}
Cannot be Special Summoned from the Deck. \
${3_TRIBUTE_SUMMON} \
${EGYPTIAN} \
${EGYPTIAN_LIMIT} \
${RACE|Winged-Beast/Pyro}\
"""

[card.ra_sphere]
id = 410000004
ot = 32
alias = 10000080
name = "Ra the Sun Divine Sphere"
type = "monster transform effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${ALIAS|The Winged Dragon of Ra - Sphere Mode|2|}
Whenever your "The Winged Dragon of Ra" is Normal Summoned: Transform Summon this card in the same battle position, by using it. \
${EGYPTIAN} \
${RACE|Winged-Beast/Pyro} \
Cannot attack. \
Twice per turn, this card cannot be destroyed by battle. \
You take no Battle Damage from battles involving this card. \
Once per turn: Any player can De-Transform this card, \
    and if they do, original ATK/DEF of the original form become the combined original ATK/DEF of the monsters Tributed for its Tribute Summon (min. 4000). \
    Only original owner of original form can use this effect. \
During the End Phase: Transform Summon this card in the same battle position, by using 1 "The Winged Dragon of Ra - Immortal Phoenix" Transform Monster. \
    (transfer its materials to this card.)\
"""
strings = [
    "Transform to Standard mode"
]

[card.ra_phoenix]
id = 410000005
ot = 32
alias = 10000090
name = "Ra the Sun Divine Immortal Phoenix"
type = "monster transform effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
"The Winged Dragon of Ra" is Special Summoned from the GY
${ALIAS|The Winged Dragon of Ra - Immortal Phoenix|2|}
${EGYPTIAN} \
${RACE|Winged-Beast/Pyro} \
Cannot be destroyed by battle or card effects. \
Unaffected by your opponent's Spell/Trap effects, and card effects that prevent it from attacking, and this card attacks cannot be negated. \
You take no Battle Damage from battles involving this card. \
After damage calculation, if this card attacked: You can send all monsters your opponent controls to the GY. \
Once per turn (Quick Effect): You can pay LP so that you only have 100 left; during this turn, while this card is on the field: \
    This card gains original ATK/DEF equal to the amount of LP paid, \
    and also, any increase in LP is changed to increase this card's ATK/DEF instead. \
    Cards and effects cannot be activated in response to this effect's activation. \
(Quick Effect): You can Tribute any number of other face-up monsters; \
    this card gains original ATK/DEF equal to the combined original ATK/DEF the Tributed monsters. \
Once per chain (Quick Effect): You can pay 1000 LP, then destroy 1 other monster on the field with the same or lower Divine Hierarchy, ignoring card effects. \
Once per turn, during the End Phase: Send it to the GY.\
"""
strings=[
    "Send monsters to the GY",
    "Life Point transfer",
    "Tribtue monsters for ATK/DEF",
    "Destroy 1 monster",
]