[set.hero]
code = 0x8

[set.elemental-hero]
code = 0x3008

[set.neos]
code = 0x9

[set.neo-spacian]
code = 0x1f

[card.neo-space-multiverse]
id = 410000400
alias = 42015635
set = "neos"
name = "Neo-Space Multiverse"
type = "spell field"
attribute = "spell"
effect = """\
(This card's name is always treated as "Neo Space".)
[ \
"Elemental HERO Honest Neos" is also treated as "Elemental HERO Neos". \
]

This card cannot be destroyed by card effects, also unaffected by monsters' effects. \
Special Summons of your Fusion Monsters that list "Elemental HERO Neos" as a material cannot be negated. \
Fusion Monsters that list "Elemental HERO Neos" as a material \
    do not have to activate their effects during the End Phase that shuffle them into the Extra Deck. \
During your Main Phase, you can Tribute Summon 1 "HERO" monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
"""
strings = ["Summon via \"Neo-Space Multiverse\""]

[card.spacian-hero-neos]
id = 410000401
alias = 89943723
name = "Spacian HERO Neos"
type = "monster normal"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
(This card is also always treated as "Elemental HERO Neos".)
You can Tribute summon this card by Tributing 1 "HERO" or "Neos" monster. \
If a Fusion Monster(s) you control that lists "Elemental HERO Neos" as material \
    is destroyed by battle or has left the field because of a card effect: \
    You Special Summon this card from your hand, Deck, or GY. \
    You can only use this effect of "Spacian HERO Neos" once per turn. \
"""
strings = ["Normal Summon with 1 \"HERO\" monster"]

[card.spacian-hero-neu]
id = 410000402
set = "elemental-hero"
name = "Spacian HERO Neu"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1900
def = 1300
effect = """\
(This card is always treated as an "Elemental HERO" card.)
While "Neo Space" is face-up on the field, this card’s name becomes "Elemental HERO Neos" while on the field or in the GY. \
    This effect cannot be negated. \
If this card is Normal or Special Summoned: You can add 1 Spell/Trap from your Deck to your hand \
    that specifically lists the card "Elemental HERO Neos" in its text. \
    You can only use this effect of "Spacian HERO Neu" once per turn. \
"""
strings = []

[card.elemental-hero-prime-neos]
id = 410000403
set = "elemental-hero neos"
name = "Elemental HERO Prime Neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + 1 Level 4 or lower Effect Monster, except "Neo-Spacian" monster
${NEOS_SUMMON} \
Gains 300 ATK for each "Neo-Spacian" and "HERO" monster in your GY. \
If this card destroys a monster by battle: Inflict damage to your opponent equal to that monster's original ATK. \
If Summoned by its owned effect, the following effect cannot be activated this turn. \
(Quick Effect): you can shuffle this card into the Extra Deck; \
    Special Summon 2 monsters with different names ("Elemental HERO Neos" or "Neo-Spacian" monsters) from your hand, Deck or GY, \
    but they cannot attack or activate their effects this turn. \
    You can only use this effect of "Elemental HERO Prime Neos" once per turn. \
"""
strings = [
    "Summoned by its own effect",
    "Inflict damage",
    "Shuffle to Extra Deck to Special Summon monster",
]

[card.elemental-hero-blazing-neos]
id = 410000404
set = "elemental-hero neos"
name = "Elemental HERO Blazing Neos"
type = "monster fusion effect"
attribute = "fire"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Flare Scarab" or Level 4 or lower FIRE Insect monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
Gains 400 ATK for each Spell/Trap Cards on the field. \
If this card attacks, your opponent cannot activate Spell/Trap Cards until the end of the Damage Step. \
While "Neo Space" is on the field, this card cannot be destroyed by battle. \
"""
strings = []

[card.elemental-hero-abyssal-neos]
id = 410000405
set = "elemental-hero neos"
name = "Elemental HERO Abyssal Neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin" or Level 4 or lower WATER Fish monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
Your opponent cannot banish cards from either GY. \
Once per turn: You can destroy 1 random card in your opponent's hand. \
    This is a Quick Effect if "Neo Space" is on the field. \
"""
strings = ["Destroy card in your opponent's hand"]

[card.elemental-hero-celestial-neos]
id = 410000406
set = "elemental-hero neos"
name = "Elemental HERO Celestial Neos"
type = "monster fusion effect"
attribute = "wind"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Air Hummingbird" or Level 4 or lower WIND Winged-Beast monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
Your opponent cannot target this card with card effect. \
While your LP is higher your opponent's, this card gains ATK equal to the difference. \
While "Neo Space" is on the field, you take no effect damage. \
"""
strings = []

[card.elemental-hero-colossal-neos]
id = 410000407
set = "elemental-hero neos"
name = "Elemental HERO Colossal Neos"
type = "monster fusion effect"
attribute = "earth"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Grand Mole" or Level 4 or lower EARTH Rock monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
Your opponent's hand size limit becomes 5. \
Once per turn: You can target 1 card your opponent controls; return it to the hand. \
    This is a Quick Effect if "Neo Space" is on the field. \
"""
strings = ["Banish itself", "Return card your opponent controls to hand"]

[card.elemental-hero-shining-neos]
id = 410000408
set = "elemental-hero neos"
name = "Elemental HERO Shining Neos"
type = "monster fusion effect"
attribute = "earth"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Glow Moss" or Level 4 or lower LIGHT Plant monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
Cannot be destroyed by card effects. \
Once per turn, during the Main Phase: You can destroy 1 card your opponent controls, \
    and if you do, apply the effect based on its type. \
    This is a Quick Effect if "Neo Space" is on the field.
● Monster: This card gains 500 ATK.
● Spell: Banish 1 random monster from your opponent's Extra Deck.
● Trap: Banish 1 card from the your opponent's GY.
"""
strings = ["Destroy 1 face-up card and apply effect"]

[card.elemental-hero-void-neos]
id = 410000409
set = "elemental-hero neos"
name = "Elemental HERO Void Neos"
type = "monster fusion effect"
attribute = "earth"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Dark Panther" or Level 4 or lower DARK Beast monster
${NEOS_SUMMON} \
${NEOS_END_PHASE} \
When this attacking card destroys a monster by battle: \
    You can activate this effect; this card can make a second attack in a row. \
Once per turn: You can target 1 face-up Effect Monster your opponent controls; \
    negate its effects, and if you do, this card gains that monster's effects until the End Phase. \
    This is a Quick Effect if "Neo Space" is on the field. \
"""
strings = ["Attack again", "Negate & copy effect"]
