[set.hero]
code = 0x8

[set.elemental-hero]
code = 0x3008

[set.neos]
code = 0x9

[set.neo-spacian]
code = 0x1f

[card.neo-space-multiverse]
id = 410000400
alias = 42015635
set = "neos"
name = "Neo-Space Multiverse"
type = "spell field"
attribute = "spell"
effect = """\
(This card's name is always treated as "Neo Space".)
[ \
"Elemental HERO Honest Neos" is also treated as "Elemental HERO Neos". \
]

This card cannot be destroyed by card effects, also unaffected by monsters' effects. \
Special Summons of your Fusion Monsters that list "Elemental HERO Neos" as a material cannot be negated. \
Fusion Monsters that list "Elemental HERO Neos" as a material \
    do not have to activate their effects during the End Phase that shuffle them into the Extra Deck. \
During your Main Phase, you can Tribute Summon 1 "HERO" monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
"""
strings = ["Summon via \"Neo-Space Multiverse\""]

[card.spacian-hero-neos]
id = 410000401
alias = 89943723
name = "Spacian HERO Neos"
type = "monster normal"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
(This card is also always treated as "Elemental HERO Neos".)
You can Tribute summon this card by Tributing 1 "HERO" or "Neos" monster. \
If a Fusion Monster(s) you control that lists "Elemental HERO Neos" as material \
    is destroyed by battle or has left the field because of a card effect: \
    You Special Summon this card from your hand, Deck, or GY. \
    You can only use this effect of "Spacian HERO Neos" once per turn. \
"""
strings = ["Normal Summon with 1 \"HERO\" monster"]

[card.spacian-hero-neu]
id = 410000402
set = "elemental-hero"
name = "Spacian HERO Neu"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1900
def = 1300
effect = """\
(This card is always treated as an "Elemental HERO" card.)
While "Neo Space" is face-up on the field, this card’s name becomes "Elemental HERO Neos" while on the field or in the GY. \
    This effect cannot be negated. \
If this card is Normal or Special Summoned: You can add 1 Spell/Trap from your Deck to your hand \
    that specifically lists the card "Elemental HERO Neos" in its text. \
    You can only use this effect of "Spacian HERO Neu" once per turn. \
"""
strings = []

[card.elemental-hero-shining-neos]
id = 410000403
set = "elemental-hero neos"
name = "Elemental HERO Shining Neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
"Elemental HERO Neos" + 1 Level 4 or lower Effect Monster, except "Neo-Spacian" monster
Must first be either Fusion Summoned, \
    or Special Summoned from your Extra Deck by shuffling the above cards you control into the Deck. \
Gains 200 ATK for each "Neo-Spacian" and "HERO" monster in your GY. \
If this card destroys a monster by battle: Inflict damage to your opponent equal to that monster's original ATK. \
If Summoned by its owned effect, the following effect cannot be activated this turn. \
During the Main Phase (Quick Effect): you can shuffle this card into the Extra Deck; \
    Special Summon 1 "Elemental HERO Neos" and 1 "Neo-Spacian" monster from your hand, Deck or GY in Defense Position, \
    but they cannot activate their effects this turn. \
    You can only use this effect of "Elemental HERO Shining Neos" once per turn. \
"""
strings = ["Summoned by its own effect", "Inflict damage", "Special Summon \"Neos\" and \"Neo-Spacian\" monster"]
