[card.asgard]
id = 930000000
set = "aesir"
name = "Asgard the Aesir Realm"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
"""
strings = []

[card.odin]
id = 930000001
set = "aesir"
name = "Odin, Allfather of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 12
atk = 4000
def = 3500
effect = """\
1 "Nordic Ascendant" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
When Summoned this way: You can add 1 card from your Deck to your hand. \
"""
strings = []

[card.frigga]
id = 930000002
set = "aesir"
name = "Frigga, Mother of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 11
atk = 3800
def = 3200
effect = """\
1 "Nordic Champion" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.thor]
id = 930000003
set = "aesir"
name = "Thor, Aesir of Thunder"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3500
def = 2800
effect = """\
1 "Nordic Beast" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.sif]
id = 930000004
set = "aesir"
name = "Sif, Lady of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3000
def = 3300
effect = """\
1 "Nordic" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.loki]
id = 930000005
set = "aesir"
name = "Loki, Aesir of Mischief"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link-rating = 3
link-arrows = "top-left top-right bottom"
atk = 3300
effect = """\
3 monsters whose total Levels equal 10, including an "Nordic Alfar" Tuner
${NORDIC_GOD_EFFECT|Link} \
${NORDIC_GOD_REBORN} \
"""
strings = []

[card.surtr]
id = 930000007
set = "nordic"
name = "Surtr, Bringer of the Nordic Ragnarok"
type = "monster xyz effect"
attribute = "divine"
race = "creator-god"
rank = 10
atk = 4000
def = 3500
effect = """\
3 Level 10 "Nordic" monsters
${NORDIC_GOD_EFFECT|Xyz} \
"""
strings = []

[card.tyr-of-the-nordic-champions]
id = 2333365
ot = "ocg tcg"
set = "nordic-champion"
name = "Tyr of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 2000
def = 2000
effect = """\
Your opponent's monsters cannot target "Nordic" monsters for attacks, except "Tyr of the Nordic Champions". \
If there is no other "Nordic" monster on the field, destroy this card. \
"""
strings = []
