[card.asgard]
id = 930000000
set = "aesir"
name = "Asgard the Aesir Realm"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
"""
strings = []

[card.odin]
id = 930000001
set = "aesir"
name = "Odin, Allfather of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 12
atk = 4000
def = 3500
effect = """\
1 "Nordic Ascendant" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
(Quick Effect): You can activate this effect; until the end of this turn, while this card is on the field, \
    original "Aesir" monsters you control are unaffected by Spell/Trap effects. \
    Your opponent cannot activate Spell/Trap Cards in response to this effect's activation. \
    You cannot activate this effect if your cards or effects are in that Chain. \
    You can only use this effect of "Odin, Allfather of the Aesir" once per turn. \
${NORDIC_GOD_REBORN} \
If Summoned this way: You can look at up to 5 cards from the top of your Deck, \
    then place them on the top of the Deck in any order, and if you do, draw 1 card. \
"""
strings = ["\"Aesir\" monsters unaffected by Spell/Trap"]

[card.frigga]
id = 930000002
set = "aesir"
name = "Frigga, Mother of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 11
atk = 3800
def = 3200
effect = """\
1 "Nordic Champion" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
Once per turn, when your opponent's card or effect is activated that targets a card(s) on the field (Quick Effect): \
    You can negate the effect, and if you do, you can apply that negated effect at your own. \
${NORDIC_GOD_REBORN} \
If Summoned this way: You can add to your hand, or Special Summon, 1 "Nordic" monster from your Deck or GY. \
"""
strings = ["Negate the effect", "Use the negated effect"]

[card.thor]
id = 930000003
set = "aesir"
name = "Thor, Aesir of Thunder"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3500
def = 2800
effect = """\
1 "Nordic Beast" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
Once per turn, during your turn (Quick Effect): You can activate this effect; until the end of this turn, \
    negate the effects of all face-up monsters your opponent currently controls, \
    also this card can gains the original effects of 1 monster they control while this card is face-up on the field (your choice). \
${NORDIC_GOD_REBORN} \
If Summoned this way: You can inflict 800 damage to your opponent for each "Aesir" monster you control. \
"""
strings = [
    "Negate effects of face-up monsters your opponent currently controls",
    "Gain effects of 1 monsters",
]

[card.sif]
id = 930000004
set = "aesir"
name = "Sif, Lady of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3200
def = 3100
effect = """\
1 LIGHT "Nordic" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
Once per turn, if the effect activation of your monster is negated by your opponent's card effect (except during the Damage Step): \
    You can apply the negated effect, then, if that effect was activated on the field and the monster now in the GY, \
    Special Summon it in the same position it was in when on the field, \
    This effect's activation cannot be negated. \
    This card must be face-up on the field to activate and to resolve this effect. \
${NORDIC_GOD_REBORN} \
If Summoned this way: You can gain 1000 LP for each "Aesir" monster you control. \
"""
strings = ["Apply the negated monster's effect"]

[card.loki]
id = 930000005
set = "aesir"
name = "Loki, Aesir of Mischief"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link-rating = 3
link-arrows = "7top-left top-right bottom"
atk = 3300
effect = """\
3 monsters whose total Levels equal 10, including an "Nordic Alfar" Tuner (substitute accepted)
${NORDIC_GOD_EFFECT|Link} \
Once per turn, when your opponent activates a card or effect during your turn (Quick Effect): \
    You can negate the activation, and if you do, destroy it. \
    Then, if it was a Spell/Trap, you can Set it to your field. \
${NORDIC_GOD_REBORN} \
If Summoned this way: You can add to your hand, or Set, 1 Trap from your GY. \
"""
strings = ["Negate activation", "Set the destroyed card to your field"]

[card.laufey]
id = 930000006
set = "nordic"
name = "Laufey the Nordic Giant"
type = "monster link effect"
attribute = "water"
race = "rock"
link-rating = 4
link-arrows = "top left right bottom"
atk = "?"
effect = """\
4 "Nordic" monsters that have Level with different names, except Tokens
You can only Special Summon "Laufey the Nordic Giant(s)" once per turn. \
Must be Link Summoned. \
You can also use DARK monsters in your hand as material to Link Summon this card. \
${NORDIC_GOD_EFFECT|Link} \
This card's original ATK becomes equal 200 x combined Levels of Link Materials used for its Link Summon. \
If this card is destroyed by battle or card effect: \
    You can shuffle this card into the Extra Deck, and if you do, \
    Special Summon up to 4 Level 5 or lower "Nordic" monsters with different names in Defense Position, \
    from your hand, Deck or GY, but it cannot activate its effect this turn. \
    You can only use this effect of "Laufey the Nordic Giant" once per turn. \
"""
strings = []

[card.hela]
id = 930000007
set = "nordic"
name = "Hela, Ruler of the Nordic Underworld"
type = "monster fusion effect"
attribute = "dark"
race = "zombie"
level = 9
atk = 800
def = 2800
effect = """\
3 "Nordic" monsters with different Types
${NORDIC_GOD_EFFECT|Fusion} \
"""
strings = []

[card.surtr]
id = 930000008
set = "nordic"
name = "Surtr, Bringer of the Nordic Ragnarok"
type = "monster xyz effect"
attribute = "fire"
race = "fiend"
rank = 12
atk = 5000
def = 0
effect = """\
3 DARK "Nordic" monsters whose original Level is 8 or higher, with different names
Must be Xyz Summoned. \
${NORDIC_GOD_EFFECT|Xyz} \
"""
strings = []

[card.brunhild]
id = 930000009
set = "nordic-ascendant"
name = "Brunhild of the Nordic Ascendant"
type = "monster effect"
attribute = "light"
race = "fairy"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hildr]
id = 930000010
set = "nordic-ascendant"
name = "Hildr of the Nordic Ascendant"
type = "monster effect"
attribute = "light"
race = "fairy"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.sigrdrifa]
id = 930000011
set = "nordic-ascendant"
name = "Sigrdrifa of the Nordic Ascendant"
type = "monster tuner effect"
attribute = "light"
race = "fairy"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.frey]
id = 930000012
set = "nordic-champion"
name = "Frey of the Nordic Champions"
type = "monster tuner effect"
attribute = "light"
race = "warrior"
level = 6
atk = 0
def = 0
effect = """\
"""
strings = []

[card.beyla]
id = 930000013
set = "nordic-champion"
name = "Beyla of the Nordic Champions"
type = "monster tuner effect"
attribute = "light"
race = "warrior"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hervor]
id = 930000014
set = "nordic-champion"
name = "Hervor of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.eir]
id = 930000015
set = "nordic-champion"
name = "Eir of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 2
atk = 0
def = 0
effect = """\
"""
strings = []

[card.eikthyrnir]
id = 930000016
set = "nordic-beast"
name = "Eikthyrnir of the Nordic Beasts"
type = "monster tuner effect"
attribute = "light"
race = "beast"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.alsvid]
id = 930000017
set = "nordic-beast"
name = "Alsvid of the Nordic Beasts"
type = "monster tuner effect"
attribute = "earth"
race = "beast"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hildisvini]
id = 930000018
set = "nordic-beast"
name = "Hildisvini of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
level = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.ratatoskr]
id = 930000019
set = "nordic-beast"
name = "Ratatoskr of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
level = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.moros]
id = 930000020
set = "nordic-alfar"
name = "Moros of the Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
level = 5
atk = 0
def = 0
effect = """\
"""
strings = []

[card.narfi]
id = 930000021
set = "nordic-alfar"
name = "Narfi of the Nordic Alfar"
type = "monster tuner effect"
attribute = "dark"
race = "spellcaster"
level = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.dvalinn]
id = 930000022
set = "nordic-alfar"
name = "Dvalinn of The Nordic Alfar"
type = "monster tuner effect"
attribute = "light"
race = "spellcaster"
level = 2
atk = 0
def = 0
effect = """\
"""
strings = []

[card.alp]
id = 930000023
set = "nordic-alfar"
name = "Alp of the Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
level = 1
atk = 0
def = 0
effect = """\
"""
strings = []

[card.idun]
id = 930000024
set = "nordic"
name = "Idun the Nordic Young"
type = "monster spirit effect"
attribute = "light"
race = "fairy"
level = 5
atk = 0
def = 0
effect = """\
Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. \
"""
strings = []

[card.huginn-muninn]
id = 930000025
set = "nordic"
name = "Huginn and Muninn the Nordic Eyes"
type = "monster union effect"
attribute = "light"
race = "winged-beast"
level = 1
atk = 0
def = 0
effect = """\
"""
strings = []

[card.gungnir]
id = 930000026
set = "nordic-relic"
name = "Divine Nordic Relic Gungnir"
type = "spell equip"
effect = """\
"""
strings = []

[card.brisingamen]
id = 930000027
set = "nordic-relic"
name = "Divine Nordic Relic Brisingamen"
type = "spell equip"
effect = """\
"""
strings = []

[card.mjollnir]
id = 930000028
set = "nordic-relic"
name = "Divine Nordic Relic Mjollnir"
type = "spell equip"
effect = """\
"""
strings = []

[card.andvaranaut]
id = 930000029
set = "nordic-relic"
name = "Divine Nordic Relic Andvaranaut"
type = "spell equip"
effect = """\
"""
strings = []

[card.laevateinn]
id = 930000030
set = "nordic-relic"
name = "Divine Nordic Relic Laevateinn"
type = "spell equip"
effect = """\
"""
strings = []

[card.yule]
id = 930000031
name = "Yule"
type = "spell"
effect = """\
"""
strings = []

[card.nordic-valhalla]
id = 930000032
set = "nordic"
name = "Valhalla, Nordic Celestial Haven"
type = "spell"
effect = """\
"""
strings = []

[card.nordic-sessrumnir]
id = 930000033
set = "nordic"
name = "Sessrumnir, Nordic Celestial Hall"
type = "spell"
effect = """\
"""
strings = []

[card.nordic-feast]
id = 930000034
set = "nordic"
name = "Feast for the Nordic Lords"
type = "spell quick-play"
effect = """\
"""
strings = []

[card.bifrost]
id = 930000035
set = "nordic"
name = "Bifrost the Nordic Bridge"
type = "spell quick-play"
effect = """\
"""
strings = []

[card.fiery-armageddon]
id = 930000036
set = "nordic"
name = "Nordic Horror - Fiery Armageddon"
type = "trap counter"
effect = """\
"""
strings = []

[card.ouroboros-break]
id = 930000037
set = "nordic"
name = "Nordic Horror - Ouroboros Break"
type = "trap counter"
effect = """\
"""
strings = []

[card.tyr-of-the-nordic-champions]
id = 2333365
ot = "ocg tcg"
set = "nordic-champion"
name = "Tyr of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 2000
def = 2000
effect = """\
Your opponent's monsters cannot target "Nordic" monsters for attacks, except "Tyr of the Nordic Champions". \
If there is no other "Nordic" monster on the field, destroy this card. \
"""
strings = []
