[card.asgard]
id = 930000000
set = "aesir"
name = "Asgard the Aesir Realm"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
"""
strings = []

[card.odin]
id = 930000001
set = "aesir"
name = "Odin, Allfather of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 12
atk = 4000
def = 3500
effect = """\
1 "Nordic Ascendant" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
When Summoned this way: You can add 1 card from your Deck to your hand. \
"""
strings = []

[card.frigga]
id = 930000002
set = "aesir"
name = "Frigga, Mother of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 11
atk = 3800
def = 3200
effect = """\
1 "Nordic Champion" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.thor]
id = 930000003
set = "aesir"
name = "Thor, Aesir of Thunder"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3500
def = 2800
effect = """\
1 "Nordic Beast" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.sif]
id = 930000004
set = "aesir"
name = "Sif, Lady of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
level = 10
atk = 3200
def = 3100
effect = """\
1 LIGHT "Nordic" Tuner + 2+ non-Tuner monsters
${AESIR_GOD_EFFECT} \
"""
strings = []

[card.loki]
id = 930000005
set = "aesir"
name = "Loki, Aesir of Mischief"
type = "monster link effect"
attribute = "divine"
race = "creator-god"
link-rating = 3
link-arrows = "top-left top-right bottom"
atk = 3300
effect = """\
3 monsters whose total Levels equal 10, including an "Nordic Alfar" Tuner (substitute accepted)
${NORDIC_GOD_EFFECT|Link} \
${NORDIC_GOD_REBORN} \
"""
strings = []

[card.laufey]
id = 930000006
set = "nordic"
name = "Laufey the Nordic Giant"
type = "monster link effect"
attribute = "water"
race = "rock"
link-rating = 4
link-arrows = "top left right bottom"
atk = "?"
effect = """\
4 Level 4 or lower "Nordic" monsters, except Tokens
${NORDIC_GOD_EFFECT|Link} \
"""
strings = []

[card.hela]
id = 930000007
set = "nordic"
name = "Hela, Ruler of the Nordic Underworld"
type = "monster fusion effect"
attribute = "dark"
race = "zombie"
rank = 9
atk = 800
def = 2800
effect = """\
3 "Nordic" monsters with different Types
${NORDIC_GOD_EFFECT|Fusion} \
"""
strings = []

[card.surtr]
id = 930000008
set = "nordic"
name = "Surtr, Bringer of the Nordic Ragnarok"
type = "monster xyz effect"
attribute = "fire"
race = "fiend"
rank = 12
atk = 5000
def = 0
effect = """\
3 DARK "Nordic" monsters whose original Level is 8 or higher, with different names
${NORDIC_GOD_EFFECT|Xyz} \
"""
strings = []

[card.Brunhild]
id = 930000009
set = "nordic-ascendant"
name = "Brunhild of the Nordic Ascendant"
type = "monster effect"
attribute = "light"
race = "fairy"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hildr]
id = 930000010
set = "nordic-ascendant"
name = "Hildr of the Nordic Ascendant"
type = "monster effect"
attribute = "light"
race = "fairy"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.sigrdrifa]
id = 930000011
set = "nordic-ascendant"
name = "Sigrdrifa of the Nordic Ascendant"
type = "monster effect"
attribute = "light"
race = "fairy"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.frey]
id = 930000012
set = "nordic-champion"
name = "Frey of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
rank = 6
atk = 0
def = 0
effect = """\
"""
strings = []

[card.beyla]
id = 930000013
set = "nordic-champion"
name = "Beyla of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hervor]
id = 930000014
set = "nordic-champion"
name = "Hervor of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
rank = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.eir]
id = 930000015
set = "nordic-champion"
name = "Eir of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
rank = 2
atk = 0
def = 0
effect = """\
"""
strings = []

[card.eikthyrnir]
id = 930000016
set = "nordic-beast"
name = "Eikthyrnir of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.alsvid]
id = 930000017
set = "nordic-beast"
name = "Alsvid of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.hildisvini]
id = 930000018
set = "nordic-beast"
name = "Hildisvini of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
rank = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.ratatoskr]
id = 930000019
set = "nordic-beast"
name = "Ratatoskr of the Nordic Beasts"
type = "monster effect"
attribute = "earth"
race = "beast"
rank = 3
atk = 0
def = 0
effect = """\
"""
strings = []

[card.moros]
id = 930000020
set = "nordic-alfar"
name = "Moros of the Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
rank = 5
atk = 0
def = 0
effect = """\
"""
strings = []

[card.narfi]
id = 930000021
set = "nordic-alfar"
name = "Narfi of the Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
rank = 4
atk = 0
def = 0
effect = """\
"""
strings = []

[card.dvalinn]
id = 930000022
set = "nordic-alfar"
name = "Dvalinn of The Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
rank = 2
atk = 0
def = 0
effect = """\
"""
strings = []

[card.alp]
id = 930000023
set = "nordic-alfar"
name = "Alp of the Nordic Alfar"
type = "monster effect"
attribute = "dark"
race = "spellcaster"
rank = 1
atk = 0
def = 0
effect = """\
"""
strings = []

[card.tyr-of-the-nordic-champions]
id = 2333365
ot = "ocg tcg"
set = "nordic-champion"
name = "Tyr of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 2000
def = 2000
effect = """\
Your opponent's monsters cannot target "Nordic" monsters for attacks, except "Tyr of the Nordic Champions". \
If there is no other "Nordic" monster on the field, destroy this card. \
"""
strings = []
