[card.asgard-the-aesir-realm]
id = 930000000
set = "aesir"
name = "Asgard the Aesir Realm"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
"""
strings = []

[card.odin-allfather-of-the-aesir]
id = 930000001
set = "aesir"
name = "Odin, Allfather of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
rank = 12
atk = 4000
def = 3500
effect = """\
1 "Nordic Ascendant" Tuner + 2+ non-Tuner monsters
${AESIR_EFFECT} \
When Summoned this way: You can add 1 card from your Deck to your hand. \
"""
strings = []

[card.frigga-mother-of-the-aesir]
id = 930000002
set = "aesir"
name = "Frigga, Mother of the Aesir"
type = "monster synchro effect"
attribute = "divine"
race = "creator-god"
rank = 10
atk = 3000
def = 4000
effect = """\
1 "Nordic Champion" Tuner + 2+ non-Tuner monsters
${AESIR_EFFECT} \
"""
strings = []

[card.tyr-of-the-nordic-champions]
id = 2333365
ot = "ocg tcg"
set = "nordic-champion"
name = "Tyr of the Nordic Champions"
type = "monster effect"
attribute = "light"
race = "warrior"
rank = 4
atk = 2000
def = 2000
effect = """\
Your opponent's monsters cannot target "Nordic" monsters for attacks, except "Tyr of the Nordic Champions". \
If there is no other "Nordic" monster on the field, destroy this card. \
"""
strings = []
