[card.armityle]
id = 410000006
alias = 43378048
name = "Armityle the Creator of Chaos Phantasm"
type = "monster effect fusion"
attribute = "divine"
race = "creator-god"
level = 12
atk = "0"
def = "0"
effect = """\
${HIERARCHY_ALIAS|3|Armityle the Chaos Phantasm}
${DIVINE_IMMUNITY} \
"""
strings = [
]

[card.raviel]
id = 410000007
alias = 69890967
name = "Raviel the Divine Lord of Phantasm Demons"
type = "monster effect fusion"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|2|Raviel, Lord of Phantasms}
${DIVINE_IMMUNITY} \
${DIVINE_LIMIT}\
"""
strings = [
]

[card.hamon]
id = 410000008
alias = 32491822
name = "Hamon the Divine Lord of Striking Thunders"
type = "monster effect fusion"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|Hamon, Lord of Striking Thunder}
${DIVINE_IMMUNITY} \
${DIVINE_LIMIT}\
"""
strings = [
]

[card.uria]
id = 410000009
alias = 6007213
name = "Uria the Divine Lord of Searing Flames"
type = "monster effect fusion"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|Uria, Lord of Searing Flames}
${DIVINE_IMMUNITY} \
${DIVINE_LIMIT}\
"""
strings = [
]
