[set.red-eyes]
code = 0x3b

[set.fusion]
code = 0x46

[card.erupted-field-black-dragon]
id = 410000300
name = "Erupted Field of the Black Dragon"
type = "spell field"
attribute = "spell"
effect = """\
During your Main Phase, you can Normal Summon 1 Gemini monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
If this card in its owner's Field Zone is destroyed by an opponent's card effect: \
    You can Special Summon 1 "Red-Eyes Black Dragon" from your hand, Deck or GY. \
Activate 1 of these effects; You can only use this effect of "Erupted Field of the Black Dragon" once per turn.
● Send 1 "Red-Eyes" monster from your hand or Deck to the GY; add from your Deck to your hand, \
    1 "Red-Eyes" Spell/Trap or Spell/Trap that specifically lists the card "Red-Eyes Black Dragon". \
    except "Erupted Field of the Black Dragon".
● If you control a "Red-Eyes" monster (Quick Effect): You can target 1 Normal Monster in your GY; Special Summon it.
"""
strings = [
    "Summon via \"Erupted Field of the Black Dragon\"",
    "Add Spell/Trap",
    "Special Summon a Normal Monster",
]

[card.red-eyes-black-dragon]
id = 410000301
alias = 74677422
name = "Red-Eyes Sacred Black Dragon"
type = "monster normal"
attribute = "dark"
race = "dragon"
level = 7
atk = 2400
def = 2000
effect = """\
(This card is also always treated as "Red-Eyes Black Dragon")
If this card is sent from the hand or Deck to the GY: You can Special Summon it. \
    You can only use this effect of "Red-Eyes Sacred Black Dragon" once per turn. \
Once per turn, if damage calculation is performed involving this card, at the end of the Battle Phase: \
    You can inflict damage to your opponent equal to this card's original ATK. \
"""
strings = ["Inflict damage by original ATK"]

[card.red-eyes-ultimate-dragon]
id = 410000302
set = "red-eyes"
name = "Red-Eyes Ultimate Dragon"
type = "monster fusion effect"
attribute = "dark"
race = "dragon"
level = 11
atk = 3600
def = 3000
effect = """\
"Red-Eyes Black Dragon" + 2 "Red-Eyes" monsters
Must be Fusion Summoned with the above Fusion Materials. \
"""
strings = []

[card.red-eyes-abyss-dragon]
id = 410000303
set = "red-eyes"
name = "Red-Eyes Abyss Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 8
atk = 2400
def = 2000
effect = """\
1 Level 1 DARK Tuner + 1 non-Tuner "Red-Eyes" monster
For this card's Synchro Summon, you can treat 1 Dragon monster with 0 ATK/DEF you control as a Tuner. \
Gains 300 ATK for each Dragon monster in your GY. \
"""
strings = []

[card.red-eyes-mechanical-dragon]
id = 410000304
set = "red-eyes"
name = "Red-Eyes Mechanical Dragon"
type = "monster xyz effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2800
def = 2400
effect = """\
2 Level 7 "Red-Eyes" monsters
You can also Xyz Summon this card by using a "Red-Eyes Black Dragon" you control as the material. \
Cannot be destroyed by card effects while it has Xyz Material. \
While this card has Xyz Material, each time your opponent activates a card or effect, \
    inflict 500 damage to your opponent immediately after it resolves. \
When a card or effect is activated (Quick Effect): \
    You can detach 1 material from this card; \
    negate the activation, and if you do, destroy it, \
    also inflict 1000 damage to your opponent. \
    You can only use this effect of "Red-Eyes Mechanical Dragon" once per turn. \
"""
strings = [
    "Xyz Summon by using a \"Red-Eyes Black Dragon\"",
    "Negate the activation"
]

[card.red-eyes-armored-dragon]
id = 410000305
set = "red-eyes"
name = "Red-Eyes Armored Dragon"
type = "monster link effect"
attribute = "dark"
race = "dragon"
link-arrows = "bottom-left bottom-right"
link-rating = 2
atk = 2400
effect = """\
2 DARK monsters, including 1 Level 5 or higher "Red-Eyes" monster
"""
strings = []

[card.red-eyes-polymerization]
id = 410000306
set = "red-eyes fusion"
name = "Red-Eyes Polymerization"
type = "spell quick-play"
attribute = "spell"
effect = """\
During the Main Phase: Fusion Summon 1 Fusion Monster that lists a "Red-Eyes" monster as material from your Extra Deck, \
    using monsters from your hand, Deck, or field as Fusion Materials, \
    and if you do, its name becomes "Red-Eyes Black Dragon". \
    You cannot Normal or Special Summon other monsters the turn you activate this card, except "Red-Eyes" monsters. \
    You can only activate 1 "Red-Eyes Polymerization" per turn. \
"""
strings = ["Activated \"Red-Eyes Polymerization\""]
