[set.red-eyes]
code = 0x3b

[card.red-eyes-black-dragon]
id = 410000301
alias = 74677422
name = "Red-Eyes Sacred Black Dragon"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2400
def = 2000
effect = """\
(This card's name is always treated as "Red-Eyes Black Dragon". This card is treated as a Normal Monster.)
If this card is sent from the hand or Deck to the GY: You can Special Summon it. \
    You can only use this effect of "Red-Eyes Sacred Black Dragon" once per turn this way. \
Once per turn, if damage calculation is performed involving this card, at the end of the Battle Phase: \
    You can inflict damage to your opponent equal to this card's original ATK. \
"""
strings = ["Inflict damage by original ATK"]
