[set.majestic]
code = 0x3f

[set.stardust]
code = 0xa3

[set.rose-dragon]
code = 0x1123

[set.synchron]
code = 0x1017

[card.mausoleum-signer-dragons]
id = 410000500
name = "Mausoleum of the Signer Dragons"
type = "spell field"
attribute = "spell"
effect = """\
[ \
Add from Outside "Majestic" versions of your Signer Dragons, \
    downgraded versions of your "Shooting Star Dragon", \
    and alternative versions of your "Shooting Quasar Dragon". \
Alternative versions of Signer Dragons is always treated as Signer Dragons. \
]

During your Draw Phase, before you draw: You can give up your normal draw this turn, \
    and if you do, add 1 "Signer Overdrive" from your Deck or GY to your hand. \
Special Summons of your "Power Tool" Synchro Monsters and Level 7 or higher Dragon Synchro Monsters cannot be negated. \
Neither player can return "Majestic" Synchro Monsters from the field to the Extra Deck. \
During your Main Phase, you can Normal Summon 1 Tuner monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
If a "Power Tool" Synchro Monster(s) or Level 7 or higher Dragon Synchro Monster(s) is Special Summoned: You can draw 1 card. \
If a face-up "Power Tool" Synchro Monster(s) or Level 7 or higher Dragon Synchro Monster(s) you control leaves the field to activate your card effect, or by your card effect: \
    You can apply 1 of the following effects. You cannot apply that same effect of "Mausoleum of the Signer Dragons" for the rest of this turn.
● Special Summon 1 of those monsters.
● Any damage you take this turn is halved.
"""
strings = [
    "Add \"Signer Overdrive\"",
    "Summon via \"Mausoleum of the Signer Dragons\"",
    "Halve any damage you take",
]

[card.majestic-black-dragon]
id = 410000501
set = "majestic"
name = "Majestic Black Dragon"
type = "monster synchro effect"
attribute = "dark"
race = "dragon"
level = 10
atk = 3920
def = 2600
effect = """\
"Majestic Dragon" + "Black-Winged Dragon" + 1 non-Tuner monster
If you would take damage from a card effect, place 1 Black Feather Counter on this card instead. \
This card gain 400 ATK for each Black Feather Counter on it. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, it loses 700 ATK for each Black Feather Counter you removed, \
    then inflict damage to your opponent equal to the ATK lost by this effect. \
During the End Phase: Target 1 "Black-Winged Dragon" in your GY; \
    return this card from the field to the Extra Deck, then Speicla Summon that target. \
"""
strings = ["Negate effects, down atk & inflict damage"]

[card.majestic-rose-dragon]
id = 410000502
set = "majestic rose-dragon"
name = "Majestic Rose Dragon"
type = "monster synchro effect"
attribute = "fire"
race = "dragon"
level = 9
atk = 3760
def = 2800
effect = """\
"Majestic Dragon" + "Black Rose Dragon" + 1 non-Tuner monster
If this card is Synchro Summoned: You can destroy all cards all cards your opponent controls. \
If a monster(s) is Special Summoned to your opponent's field: \
    Target 1 Special Summoned monster your opponent controls; \
    return that target to the hand. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects, and if you do, its ATK becomes 0. \
    These changes last until the end of this turn. \
During the End Phase: Target 1 "Black Rose Dragon" in your GY; \
    return this card from the field to the Extra Deck, then Speicla Summon that target. \
"""
strings = ["Negate effect"]

[card.majestic-fairy-dragon]
id = 410000503
set = "majestic"
name = "Majestic Fairy Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 9
atk = 3640
def = 4000
effect = """\
"Majestic Dragon" + "Ancient Fairy Dragon" + 1 non-Tuner monster
Your opponent cannot target Field Spell you control with card effects, \
    also it cannot be destroyed by your opponent's card effects. \
Once per turn: You can Special Summon 1 monster from your hand or GY. \
    This card cannot declare an attack the turn this effect is activated. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects until the end of this turn, \
    and if you do, gain LP equal to its ATK. \
During the End Phase: Target 1 "Ancient Fairy Dragon" in your GY; \
    return this card from the field to the Extra Deck, then Speicla Summon that target. \
"""
strings = ["Special Summon a monster", "Negate effect & gain LP"]

[card.majestic-tool-dragon]
id = 410000504
set = "majestic"
name = "Majestic Tool Dragon"
type = "monster synchro effect"
attribute = "earth"
race = "dragon"
level = 9
atk = 3720
def = 3500
effect = """\
"Majestic Dragon" + "Power Tool Dragon" + 1 non-Tuner monster
If this card would be destroyed while equipped with an Equip Spell Card(s), \
    you can send 1 of those cards to the GY instead. \
Once per turn: You can equip 1 Equip Spell from your hand, Deck to this card. \
Once per turn: You can target 1 face-up monster your opponent controls; \
    negate its effects, and if you do, it is unaffected by your opponent's card effects. \
    These changes last until the end of this turn. \
During the End Phase: Target 1 "Power Tool Dragon" in your GY; \
    return this card from the field to the Extra Deck, then Speicla Summon that target. \
"""
strings = ["Negate effect"]

[card.signer-overdrive]
id = 410000505
name = "Signer Overdrive"
type = "quick-play spell"
effect = """\
While you control "Mausoleum of the Signer Dragons", \
    if a "Power Tool" Synchro Monster, or Level 7 or higher Dragon Synchro Monster is Synchro Summoned to your field, \
    except with effects of "Signer Overdrive": \
    You can add this card from your GY to your hand. \
    You can only use this effect of "Signer Overdrive" once per turn. \
During the Main Phase, activate 1 of these effect.
● Special Summon 1 Tuner Dragon Synchro Monster from your Extra Deck or GY. \
    (This Special Summon is treated as a Synchro Summon.)
● Add to your hand, or Special Summon, 1 Tuner from your Deck, then you can send 1 monster from your Deck to the GY.
● Banish 1 Tuner and up to 2 non-Tuner monsters you control and/or from your GY, and if you do, \
    Special Summon 1 Synchro Monster from your Extra Deck whose Level equals the total Levels of those banished monsters. \
    (This Special Summon is treated as a Synchro Summon.)
"""
strings = ["Special Summon a Dragon","Search Tuner", "Synchro Summon"]

[card.spark-synchron]
id = 410000506
set = "synchron"
name = "Spark Synchron"
type = "monster tuner effect"
attribute = "light"
race = "machine"
level = 3
atk = 1300
def = 500
effect = """\
For a Synchro Summon, you can substitute this card for any 1 "Synchron" Tuner. \
If this card is Summoned: \
    You can Special Summon 1 Level 2 or lower monster from your hand or GY in Defense Position, \
    but it cannot activate its effects this turn, \
    also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Synchro Monsters. \
You can Tribute this card; Special Summon 1 "Synchron" Tuner from your Deck or GY in Defense Position, \
    except "Spark Synchron". \
You can only use this effect of "Spark Synchron" once per turn. \
"""
strings = ["Special Summon a \"Synchron\" Tuner"]

[card.mach-synchron]
id = 410000507
set = "synchron"
name = "Mach Synchron"
type = "monster tuner effect"
attribute = "wind"
race = "machine"
level = 2
atk = 300
def = 100
effect = """\
For a Synchro Summon, you can substitute this card for any 1 "Synchron" Tuner. \
If this card is sent to the GY as Synchro Material: \
    You can add 1 Level 2 or lower monster from your Deck to your hand, \
    except "Mach Synchron". \
If this card is in your GY: You can discard 1 card; \
    Special Summon this card in Defense Position, \
    but banish it when it leaves the field, \
    also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Synchro Monsters. \
You can only use 1 "Mach Synchron" effect per turn, and only once that turn. \
"""
strings = []

[card.stardust-moose]
id = 410000509
set = "stardust"
name = "Stardust Moose"
type = "monster effect"
attribute = "light"
race = "beast"
level = 2
atk = 800
def = 800
effect = """\
This card can be treated as a Level 1 monster when used for a Synchro Summon. \
    This effect cannot be negated. \
If this card is in your hand or GY, while you control a face-up Tuner monster: \
    You can Special Summon this card in Defense Position, \
    but banish it when it leaves the field. \
You can Tribute this card; Special Summon 1 Level 1 Dragon monster from your hand or GY in Defense Position. \
You can only use each effect of "Spark Moose" once per turn. \
"""
strings = ["Special Summon a monster"]

[card.ancient-stardust-dragon]
id = 410000510
alias = 44508094
set = "stardust"
name = "Ancient Stardust Dragon"
type = "monster synchro tuner effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """\
1 Tuner + 1+ non-Tuner monsters
(This card is always treated as "Stardust Dragon")
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
Once per turn, you can activate 1 of these effects.
● (Quick Effect): You can target 1 face-up card you control; \
    once during this turn, it cannot be destroyed by battle or card effects.
● When a card or effect is activated that would destroy a card(s) on the field (Quick Effect): \
    You can Tribute this card; \
    negate the activation, and if you do, destroy it. \
    During the End Phase, if this effect was activated this turn (and was not negated): \
    You can Special Summon this card from your GY.
"""
strings = [
    "Affected by \"Ancient Stardust Dragon\"",
    "Protect card",
    "Negate the activation",
]

[card.shooting-stardust-dragon]
id = 410000511
set = "stardust"
name = "Shooting Stardust Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 10
atk = 3300
def = 2500
effect = """\
1 Tuner Synchro Monster + 1 "Stardust Dragon" or "Stardust" Dragon Synchro Monster
(This card is also always treated as "Shooting Star Dragon")
Once per turn, during your opponent's turn, you can (Quick Effect): \
    Immediately after this effect resolves, Synchro Summon this card from your Extra Deck using monsters you control. \
When a card or effect is activated that targets and would destroy other card(s) on the field (Quick Effect): \
    You can negate the activation, and if you do, destroy it. \
Once per turn: You can excavate the top 5 cards of your Deck, shuffle them back in, \
    also this card's maximum number of attacks per Battle Phase this turn equals the number of Tuner monsters excavated. \
Once per turn, when your opponent activates a card, effect OR an opponent's monster attacks (Quick Effect): \
    You can banish this card until the End Phase, \
    and if you do, negate the next attack this turn from a monster your opponent controls. \
"""
strings = ["Negate the activation", "Multi-Attack", "Banish"]

[card.shooting-star-synchron]
id = 410000512
set = "synchron"
name = "Shooting Star Synchron"
type = "monster synchro tuner effect"
attribute = "light"
race = "machine"
level = 2
atk = 200
def = 1500
effect = """\
1 Tuner + 1 non-Tuner monster
If this card is Synchro Summoned: You can draw 1 card. \
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
Once per Chain, during your opponent's Main Phase, you can (Quick Effect): \
    Immediately after this effect resolves, Synchro Summon using this card you control. \
While this card is in your GY: You can shuffle 1 other Tuner monster in your GY into the Deck, \
    and if you do, Special Summon this card in Defense Position, \
    also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Synchro Monsters. \
    You can only use this effect of "Shooting Star Synchron" once per turn. \
"""
strings = []