[set.stardust]
code = 0xa3

[set.synchron]
code = 0x1017

[card.mausoleum-signer-dragons]
id = 410000500
name = "Mausoleum of the Signer Dragons"
type = "spell field"
attribute = "spell"
effect = """\
[ \
Add from Outside "Majestic" versions of your Signer Dragons, \
    downgraded versions of your "Shooting Star Dragon", \
    and alternative versions of your "Shooting Quasar Dragon". \
Alternative versions of Signer Dragons is always treated as Signer Dragons. \
]

Special Summons of your "Power Tool" Synchro Monsters and Dragon Synchro Monsters cannot be negated. \
Neither player can return "Majestic" Synchro Monsters from the field to the Extra Deck. \
During your Draw phase, before you draw: \
    You can place 1 Level 1 Dragon monster from your hand or Deck on top of your Deck. \
During your Main Phase, you can Normal Summon 1 Tuner monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
If a "Power Tool" Synchro Monster(s) or Dragon Synchro Monster(s) is Special Summoned: You can draw 1 card. \
If a face-up "Power Tool" Synchro Monster(s) or Dragon Synchro Monster(s) you control leaves the field to activate your card effect, or by your card effect: \
    You can apply 1 of the following effects. You cannot apply that same effect of "Mausoleum of the Signer Dragons" for the rest of this turn.
● Special Summon 1 of those monsters.
● Any damage you take this turn is halved.
"""
strings = [
    "Summon via \"Mausoleum of the Signer Dragons\"",
    "Halve any damage you take",
]

[card.ancient-stardust-dragon]
id = 410000501
alias = 44508094
set = "stardust"
name = "Ancient Stardust Dragon"
type = "monster synchro tuner effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """\
1 Tuner + 1+ non-Tuner monsters
(This card is always treated as "Stardust Dragon")
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
Once per turn, you can activate 1 of these effects.
● (Quick Effect): You can target 1 face-up card you control; \
    once during this turn, it cannot be destroyed by battle or card effects.
● When a card or effect is activated that would destroy a card(s) on the field (Quick Effect): \
    You can Tribute this card; \
    negate the activation, and if you do, destroy it. \
    During the End Phase, if this effect was activated this turn (and was not negated): \
    You can Special Summon this card from your GY.
"""
strings = [
    "Affected by \"Ancient Stardust Dragon\"",
    "Protect card",
    "Negate the activation",
]

[card.shooting-stardust-dragon]
id = 410000502
set = "stardust"
name = "Shooting Stardust Dragon"
type = "monster synchro effect"
attribute = "light"
race = "dragon"
level = 10
atk = 3300
def = 2500
effect = """\
1 Tuner Synchro Monster + 1 "Stardust Dragon" or "Stardust" Dragon Synchro Monster
(This card is also always treated as "Shooting Star Dragon")
Once per turn, during your opponent's turn, you can (Quick Effect): \
    Immediately after this effect resolves, Synchro Summon this card from your Extra Deck using monsters you control. \
When a card or effect is activated that targets and would destroy other card(s) on the field (Quick Effect): \
    You can negate the activation, and if you do, destroy it. \
Once per turn: You can excavate the top 5 cards of your Deck, shuffle them back in, \
    also this card's maximum number of attacks per Battle Phase this turn equals the number of Tuner monsters excavated. \
Once per turn, when your opponent activates a card, effect OR an opponent's monster attacks (Quick Effect): \
    You can banish this card until the End Phase, \
    and if you do, negate the next attack this turn from a monster your opponent controls. \
"""
strings = ["Negate the activation","Multi-Attack", "Banish"]

[card.shooting-star-synchron]
id = 410000503
set = "synchron"
name = "Shooting Star Synchron"
type = "monster synchro tuner effect"
attribute = "light"
race = "machine"
level = 2
atk = 650
def = 500
effect = """\
1 Tuner + 1 non-Tuner monster
If this card is Synchro Summoned: You can draw 1 card. \
If this card you control is used as Synchro Material, you can treat it as a non-Tuner, and as Level 4 monster. \
    This effect cannot be negated. \
Once per Chain, during your opponent's Main Phase, you can (Quick Effect): \
    Immediately after this effect resolves, Synchro Summon using this card you control. \
While this card is in your GY: You can shuffle 1 other Tuner monster in your GY into the Deck, \
    and if you do, Special Summon this card in face-up Defense Position. \
    You can only use this effect of "Shooting Star Synchron" once per turn. \
"""
strings = []