[set.stardust]
code = 0xa3

[card.mausoleum-signer-dragons]
id = 410000500
name = "Mausoleum of the Signer Dragons"
type = "spell field"
attribute = "spell"
effect = """\
[ \
Add from Outside "Majestic" versions of your Signer Dragons and alternative versions of "Shooting Quasar Dragon". \
Alternative versions of Signer Dragons is always treated as Signer Dragons. \
]

Special Summons of your "Power Tool" Synchro Monsters and Dragon Synchro Monsters cannot be negated. \
Neither player can return "Majestic" Synchro Monsters from the field to the Extra Deck. \
During your Draw phase, before you draw: \
    You can place 1 Level 1 Dragon monster from your hand or Deck on top of your Deck. \
During your Main Phase, you can Normal Summon 1 Tuner monster in addition to your Normal Summon/Set. \
    (You can only gain this effect once per turn.) \
If a "Power Tool" Synchro Monster(s) or Dragon Synchro Monster(s) is Special Summoned: You can draw 1 card. \
If a face-up "Power Tool" Synchro Monster(s) or Dragon Synchro Monster(s) you control leaves the field to activate your card effect, or by your card effect: \
    You can apply 1 of the following effects. You cannot apply that same effect of "Mausoleum of the Signer Dragons" for the rest of this turn.
● Special Summon 1 of those monsters.
● Any damage you take this turn is halved.
"""
strings = [
    "Summon via \"Mausoleum of the Signer Dragons\"",
    "Halve any damage you take",
]

[card.ancient-stardust-spark-dragon]
id = 410000501
alias = 44508094
set = "stardust"
name = "Ancient Stardust Spark Dragon"
type = "monster synchro tuner effect"
attribute = "light"
race = "dragon"
level = 8
atk = 2500
def = 2000
effect = """\
1 Tuner + 1+ non-Tuner monsters
(This card is also always treated as "Stardust Dragon")
If this card you control is used as Synchro Material, you can treat it as a non-Tuner. \
    This effect cannot be negated. \
Once per turn, you can activate 1 of these effects.
● (Quick Effect): You can target 1 face-up card you control; \
    once during this turn, it cannot be destroyed by battle or card effects.
● When a card or effect is activated that would destroy a card(s) on the field (Quick Effect): \
    You can Tribute this card; \
    negate the activation, and if you do, destroy it. \
    During the End Phase, if this effect was activated this turn (and was not negated): \
    You can Special Summon this card from your GY.
"""
strings = [
    "Affected by \"Ancient Stardust Spark Dragon\"",
    "Protect card",
    "Negate the activation",
]
