[card.supreme-gate]
id = 950000000
name = "Supreme Gate"
type = "spell field"
effect = """\
Your opponent cannot target cards in your Pendulum Zones with card effects. \
You can target 1 other face-up card you control; destroy it, and if you do, add from your Deck or GY to your hand, \
    1 "Odd-Eyes" card or 1 card that specifically lists "Supreme King Z-ARC" in its text, except the destroyed card and "Supreme Gate". \
    You can only use this effect of "Supreme Gate" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "Supreme Gate" for the rest of this turn (even if this card leaves the field).
● Fusion: Special Summon 1 monster from your Deck or GY with the same original Level as that Fusion Monster, in Defense Position, but it cannot activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Search & add card",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[card.soul-supreme-ruler-zarc]
id = 950000005
alias = 13331639
set = "supreme-king-dragon"
name = "Supreme Ruler Z-ARC"
type = "monster effect pendulum link"
attribute = "divine"
race = "dragon"
pendulum-scale = 13
link-rating = 4
link-arrows = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Unaffected by your opponent's card effects. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is also always treated as "Supreme King Z-ARC".)
Must be Link Summoned. \
This card's Special Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Your opponent cannot target this card with card effects. \
Cannot be destroyed by card effects. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Possession of this card cannot be switched. \
If this card is Special Summoned: Negate the effect and destroy all cards your opponent controls. \
Once per turn, when a card(s) is added to your opponent's hand (except during the Draw Phase or the Damage Step): \
    You can destroy that card(s). \
Once per turn, you can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
    This card cannot declare an attack the turn this effect is activated. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = ["Negate effect and destroy all card", "Destroy added cards", "Summon a Dragon"]

[card.supreme-soul]
id = 950000006
name = "Supreme Soul"
type = "spell link"
link-rating = 3
link-arrows = "top-left top top-right"
effect = """\
You must have 2 cards in your Pendulum Zones to activate this card. \
Pendulum Summons of your Pendulum Monsters cannot be negated. \
Any your Pendulum Monster sent to the GY or banished is add to the Extra Deck face-up. \
Once per turn (Quick Effect): You can target 1 card in your Pendulum Zone; Special Summon it, ignoring its Summoning conditions. \
Once per turn (Quick Effect): You can target 1 Pendulum Monster in your Monster Zone; place that Pendulum Monster in your Pendulum Zone. \
You can banish 4 monsters from your hand, field, and/or GY (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
You can only use this effect of "Supreme Soul" once per turn. \
"""
strings = [
    "Add monster to your hand",
    "Special Summon monster from Pendulum Zone",
    "Place monster in Pendulum Zone",
    "Summon Z-Arc",
]
