[card.supreme-gate]
id = 950000000
name = "Supreme Gate"
type = "spell field"
effect = """\
Your opponent cannot target cards in your Pendulum Zones with card effects. \
Any your Pendulum Monster sent to the GY is add to the Extra Deck face-up. \
You can target 1 other face-up card you control; destroy it, and if you do, add from your Deck, GY or Extra Deck to your hand, \
    1 "Supreme King Gate" monster, "Supreme King Dragon" monster, "Pendulum" Spell/Trap \
    or card that specifically lists "Supreme King Z-ARC" in its text, except the destroyed card and "Supreme Gateway". \
    You can only use this effect of "Supreme Gate" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "Supreme Gate" for the rest of this turn (even if this card leaves the field).
● Fusion: Special Summon 1 monster from your Deck or GY with the same original Level as that Fusion Monster, in Defense Position, but it cannot activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Search & add card",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[card.supreme-king-zarc]
id = 950000001
alias = 13331639
set = "supreme-king"
name = "Supreme King Z-ARC - Overlord"
type = "monster link pendulum effect"
attribute = "dark"
race = "dragon"
pendulum-scale = 13
link-rating = 4
link-arrows = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Unaffected by your opponent's card effects. \
Pendulum Scale of card in your other Pendulum Zone become 0. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
Once per turn, if you have a card in your other Pendulum Zone: \
    You can destroy it, and if you do, \
    place 1 Pendulum Monster from your hand, Deck, GY or Extra Deck face-up in your Pendulum Zone,
    except the destroyed card. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is always treated as "Supreme King Z-ARC".)
Must be Link Summoned, and can then be Pendulum Summoned. \
You can Pendulum Summon this card regardless of your Pendulum Scales. \
This card's Special Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Your opponent cannot target this card with card effects. \
Cannot be destroyed by card effects. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Possession of this card cannot be switched. \
If this card is Special Summoned: Destroy all cards your opponent controls. \
Once per turn, when a card(s) is added to your opponent's hand (except during the Draw Phase or the Damage Step): \
    You can destroy that card(s). \
Once per turn, you can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
    This card cannot declare an attack the turn this effect is activated. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Place pendulum monster",
    "Negate effect and destroy all card",
    "Destroy added cards",
    "Summon a Dragon",
]

[card.odd-eyes-venom-dragon]
id = 950000002
set = "odd-eyes venom supreme-king-dragon"
name = "Odd-Eyes Venom Dragon - Overlord"
type = "monster fusion pendulum effect"
attribute = "dark"
race = "dragon"
level = 9
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Once per turn, during the Standby Phase: Place 1 Venemy Counter on each face-up monster your opponent controls. \
Once per turn, if a monster you control battles an opponent's monster, before damage calculation: \
    You can make that monster you control gains 500 ATK for each Venemy Counter on the field until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Monster + 1 "Starving Venom" Fusion Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Fusion Summoned with above materials on the field, and can then be Pendulum Summoned. \
If this card is Fusion Summoned: \
    This card gain ATK equal to the combined ATK of all monsters your opponent currently controls, until the end of this turn. \
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Each time a card(s) is sent from the field to the GY, place 1 Venemy Counter on this card for each sent card. \
Once per turn (Qick Effect): You can target 1 face-up monster your opponent controls or in their GY; until the End Phase, \
    that monster has its effects negated, and also, this card gains its effects and its original ATK. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Place Venemy Counter",
    "Make 1 monster gain ATK up by Venemy Counter",
    "Negate effect & gain effect, ATK of a monster",
]

[card.odd-eyes-wing-dragon]
id = 950000003
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Wing Dragon - Overlord"
type = "monster synchro pendulum effect"
attribute = "dark"
race = "dragon"
level = 8
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, if your monster battles an opponent's monster, before damage calculation: \
    You can make that monster you control gain ATK equal to the current ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Tuner + 1 non-Tuner "Clear Wing" Synchro Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Synchro Summoned, and can then be Pendulum Summoned. \
If this card Is Synchro Summoned: \
    Negate the effects of all monsters your opponent currently controls, until the end of this turn. \
Once per turn, at the start of the Damage Step, if this card battles an opponent's monster: \
    You can destroy that opponent's monster, and if you do this card gains ATK equal to the destroyed monster's original ATK until the end of this turn, \
    also, this card can make a second attack in a row. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; until the end of this turn, \
    that monster has its effects negated, and also change its ATK to 0. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Gain ATK of battling monster's ATK",
    "Destroy battling monster",
    "Negate effect & down attack of a monster",
]

[card.odd-eyes-raging-dragon]
id = 950000004
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Raging Dragon - Overlord"
type = "monster xyz pendulum effect"
attribute = "dark"
race = "dragon"
rank = 7
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, at the end of the Damage Step, if your monster attacked an opponent's monster: \
    You can halve the ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
2+ Level 7 monsters, including 1 "Odd-Eyes" Dragon Pendulum Monster and 1 "Rebellion" Xyz Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Xyz Summoned, and can then be Pendulum Summoned. \
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. \
If this card Is Xyz Summoned: \
    This turn, it can make a second and third attack during each Battle Phase. \
Once per turn, you can can detach any number of materials from this card, then destroy that many card your opponent controls. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; until the end of this turn, \
    that monster has its effects negated, and also its ATK becomes half its current ATK, and if it does, this card gains that lost ATK. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Halve ATK of battling monster",
    "Can make 3 attacks",
    "Destroy card on the field",
    "Negate effect & halve ATK of a monster",
]

[card.supreme-soul]
id = 950000005
name = "Supreme Soul"
type = "spell link"
link-rating = 3
link-arrows = "top-left top top-right"
effect = """\
This card's activation and effect cannot be negated. \
When this card is activated: \
    Place in your Pendulum Zone 2 "Supreme King Gate", "Supreme King Dragon" Pendulum Monsters with different names \
    from your hand, Deck, GY and/or Extra Deck face-up, \
    and if you do, you can add to you hand from your Deck, GY or Extra Deck face-up, \
    1 "Supreme King Dragon" monster that have Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones. \
Face-up Spells/Traps you control cannot be destroyed by your opponent's card effects. \
Your opponent's cannot target monsters this card points to with card effects. \
Once per turn, you can banish 4 monsters from your hand, field, GY and/or Extra Deck face-up (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
You can only use each of the following effects of "Supreme Soul" twice per turn.
● Target 1 card in your Pendulum Zone; Special Summon it, ignoring its Summoning conditions.
● Target 1 Pendulum Monster in your Monster Zone; place that Pendulum Monster in your Pendulum Zone.

[ \
Add from Outside "Supreme Dragon" versions of your Four Dimension Dragons to your Extra Deck. \
] \
"""
strings = [
    "Add 1 \"Supreme King Dragon\" to your hand",
    "Summon Z-ARC",
    "Special Summon monster from Pendulum Zone",
    "Place monster in Pendulum Zone",
]

[card.supreme-king-dragon-oddwurm]
id = 950000006
set = "supreme-king-dragon odd-eyes"
name = "Supreme King Dragon Oddwurm"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2500
def = 2000
effect = """\
(This card is always treated as "Odd-Eyes" card.)
If this card's Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones: \
    You can Special Summon this card from your hand or GY. \
    You can only Special Summon "Supreme King Dragon Oddwurm" once per turn this way. \
If this card is Normal or Special Summoned: \
    You can add 1 "Spiral Flame Strike" from your Deck or GY to your hand, \
    then you can add 1 "Odd-Eyes" Dragon Pendulum Monster that is banished or in your Deck, GY to your Extra Deck face-up. \
If this card destroys an opponent's monster by battle: Inflict damage to your opponent equal to the destroyed monster's original ATK. \
If this card is destroyed by battle or card effect: \
    You can Special Summon 1 "Odd-Eyes" Dragon monster or "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck face-up, \
    except "Supreme King Dragon Oddwurm". \
    You can only use each effect of "Supreme King Dragon Oddwurm" once per turn. \
"""
strings = [
    "Add 1 \"Odd-Eyes\" Dragon Pendulum Monster to Extra Deck",
    "Inflict damage equal to the destroyed monster's original ATK",
]

[card.supreme-king-dragon-venowurm]
id = 950000007
set = "supreme-king-dragon"
name = "Supreme King Dragon Venowurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Unless you have "Supreme King Z-ARC" or a "Magician", "Odd-Eyes", "Supreme King Gate", "Supreme King Dragon" card in your other Pendulum Zone, \
    this card's Pendulum Scale becomes 4. \
Once per turn: You can Fusion Summon 1 Dragon Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Materials. \
"""
effect = """\
Cannot be used as Fusion Material, except for the Fusion Summon of a Dragon Fusion Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then the targeted monster's Attribute become DARK. \
You can declare 1 monster's name, except "Supreme King Z-ARC"; \
    until the End Phase, this card's name becomes that name. \
You can Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using this card you control as Fusion Material, as well as other monsters you control or cards in your Pendulum Zones. \
You can only use each effect of "Supreme King Dragon Venowurm" once per turn. \
"""
strings = ["Change a name"]

[card.supreme-king-dragon-wingwurm]
id = 950000008
set = "supreme-king-dragon"
name = "Supreme King Dragon Wingwurm"
type = "monster pendulum tuner effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Unless you have "Supreme King Z-ARC" or a "Magician", "Odd-Eyes", "Supreme King Gate", "Supreme King Dragon" card in your other Pendulum Zone, \
    this card's Pendulum Scale becomes 4. \
Once per turn: You can target 1 Pendulum Monster you control; this turn, \
    that face-up monster is treated as a Tuner, also its Level becomes 1 (even if this card leaves the field). \
"""
effect = """\
Cannot be used as Synchro Material, except for the Synchro Summon of a Dragon Synchro Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then reduce targeted monster's Level by this card' Level (min. 1). \
You can declare a Level from 1 to 8; this card becomes that Level until the end of this turn. \
Once per turn: You can Special Summon 1 card from your Pendulum Zone; but it has its effects negated (if any), \
    and if you do, immediately after this effect resolves, Synchro Summon 1 Synchro Monster using only that monster and this card. \
You can only use each effect of "Supreme King Dragon Wingwurm" once per turn. \
"""
strings = ["Make monster become Tuner", "Change Level"]

[card.supreme-king-dragon-rebelliwurm]
id = 950000009
set = "supreme-king-dragon"
name = "Supreme King Dragon Rebelliwurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 8
atk = 1500
def = 1000
pendulum-effect = """\
Unless you have "Supreme King Z-ARC" or a "Magician", "Odd-Eyes", "Supreme King Gate", "Supreme King Dragon" card in your other Pendulum Zone, \
    this card's Pendulum Scale becomes 4. \
Once per turn: You can target 1 face-up Xyz Monster you control, and 1 Pendulum Monster that has Level you control; until the end of this turn, \
    that Xyz Monster's Rank becomes equal to the Level of the other, \
    and also you can use it as an Xyz Material for an Xyz Summon using its Rank as if it were a Level. \
    (even if this card leaves the field). \
"""
effect = """\
Cannot be used as Xyz Material, except for the Xyz Summon of a Dragon Xyz Monster. \
If this card is in your hand, GY or Extra Deck: \
    You can target 1 Pendulum Monster or Dragon monster with 2500 ATK more you control; \
    its ATK become 0 and negate its effects, \
    and if you do, Special Summon this card in Defense Position, then the targeted monster's Level becomes the same as this card's. \
You can Tribute this card from your hand or face-up field, then target 1 Rank 4 DARK Dragon Xyz Monster you control; \
    Special Summon from your Extra Deck, 1 DARK Dragon Xyz Monster that is 1 Rank higher than that monster you control, \
    by using it as the Xyz Material. \
    (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to that target also become Xyz Materials on the Summoned monster.) \
Once per turn: You can Special Summon 1 card from your Pendulum Zone; but it has its effects negated (if any), \
    and if you do, immediately after this effect resolves, Xyz Summon 1 Xyz Monster using only that monster and this card. \
You can only use each effect of "Supreme King Dragon Rebelliwurm" once per turn. \
"""
strings = ["Make Xyz monster gain Level", "Rank-Up DARK Dragon monster"]

[card.sky-iris-magician]
id = 950000010
set = "magician"
name = "Sky Iris Magician"
type = "monster fusion pendulum effect"
attribute = "wind"
race = "spellcaster"
level = 7
pendulum-scale = 0
atk = 2000
def = 2800
pendulum-effect = """\
All monsters you control gain 100 ATK and DEF for each face-up Pendulum Monster with different names in your Extra Deck. \
If a Pendulum Monster(s) you control is destroyed by battle or by card effect: \
    You can Special Summon this card from your Pendulum Zone in Defense Position, \
    then, you can place 1 of those monsters in your Pendulum Zone. \
    You can only use this effect of "Sky Iris Magician" once per turn. \
"""
effect = """\
1 "Magician" Pendulum Monster + 1 monster that was Special Summoned from Extra Deck
If this card is Fusion Summoned: You can add 1 Pendulum Monster form your Deck or Extra Deck face-up to your hand. \
You can Special Summon 1 monster from your Pendulum Zone, ignoring their Summoning conditions, \
    and if you do, you can place this card in your Pendulum Zone. \
During the End Phase: \
    You can Special Summon as many monsters as possible from your GY or Extra Deck face-up \
    that were destroyed by battle or an opponent's card effect this turn. \
You can only use each effect of "Sky Iris Magician" once per turn. \
"""
strings = [
    "Place 1 of destroyed monsters in Pendulum Zone",
    "Special Summon monster from Pendulum Zone",
    "Special Summon all the destroyed monster",
]

[card.supreme-wrath]
id = 950000011
name = "Supreme Wrath"
type = "trap"
effect = """\
While this card is in your GY, you can target 1 "Supreme King Dragon" Xyz Monster you control; \
    attach up to 2 "Supreme King Dragon" monsters to it as materials, from your GY and/or face-up from your Extra Deck. \
    You can only use this effect of "Supreme Wrath" once per turn. \
Activate 1 of these effects. You can only activate 1 "Supreme Wrath" once per turn.
● Immediately after this effect resolves, Pendulum Summon a monster(s).
● Destroy as many cards in the Pendulum Zones as possible (min 2.), then activate 1 "Supreme Soul" directly from your hand, Deck, or GY.
● If you control "Supreme King Z-ARC": Destroy as many monsters you control as possible, except "Supreme King Z-ARC", \
    and if you do, Special Summon up to 4 "Supreme King Dragon" monsters with different names from your hand, Deck, Extra Deck, and/or GY, \
    ignoring their Summoning conditions. (This is treated as a Properly Summon.)
"""
strings = [
    "Pendulum Summon",
    "Activate \"Supreme Soul\"",
    "Special Summon a dragon(s)",
]
