[card.supreme-gate]
id = 950000000
name = "Supreme Gate"
type = "spell field"
effect = """\
Your opponent cannot target cards in your Pendulum Zones with card effects. \
Any your Pendulum Monster sent to the GY is add to the Extra Deck face-up. \
You can target 1 other face-up card you control; destroy it, and if you do, add from your Deck or GY to your hand, \
    1 "Supreme King Dragon" monster or 1 card that specifically lists "Supreme King Z-ARC" in its text, except the destroyed card and "Supreme Gateway". \
    You can only use this effect of "Supreme Gate" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "Supreme Gate" for the rest of this turn (even if this card leaves the field).
● Fusion: Special Summon 1 monster from your Deck or GY with the same original Level as that Fusion Monster, in Defense Position, but it cannot activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Search & add card",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[card.supreme-king-zarc]
id = 950000001
alias = 13331639
set = "supreme-king"
name = "Supreme King Z-ARC - Overlord"
type = "monster effect link pendulum"
attribute = "dark"
race = "dragon"
pendulum-scale = 13
link-rating = 4
link-arrows = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Face-up Spells/Traps you control are unaffected by your opponent's card effects. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is always treated as "Supreme King Z-ARC".)
Must be Link Summoned. \
This card's Special Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Your opponent cannot target this card with card effects. \
Cannot be destroyed by card effects. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Possession of this card cannot be switched. \
If this card is Special Summoned: Negate the effect and destroy all cards your opponent controls. \
Once per turn, when a card(s) is added to your opponent's hand (except during the Draw Phase or the Damage Step): \
    You can destroy that card(s). \
Once per turn, you can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
    This card cannot declare an attack the turn this effect is activated. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Negate effect and destroy all card",
    "Destroy added cards",
    "Summon a Dragon",
]

[card.odd-eyes-venom-dragon]
id = 950000002
set = "odd-eyes venom supreme-king-dragon"
name = "Odd-Eyes Venom Dragon - Overlord"
type = "monster effect fusion pendulum"
attribute = "dark"
race = "dragon"
level = 9
pendulum-scale = 0
atk = 3000
def = 2500
pendulum-effect = """\
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Monster + 1 "Starving Venom" Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Fusion Summoned, and can then be Pendulum Summoned. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = []

[card.odd-eyes-wing-dragon]
id = 950000003
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Wing Dragon - Overlord"
type = "monster effect synchro pendulum"
attribute = "dark"
race = "dragon"
level = 8
pendulum-scale = 0
atk = 3000
def = 2500
pendulum-effect = """\
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Tuner + 1 non-Tuner "Clear Wing" Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Synchro Summoned, and can then be Pendulum Summoned. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = []

[card.odd-eyes-raging-dragon]
id = 950000004
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Raging Dragon - Overlord"
type = "monster effect xyz pendulum"
attribute = "dark"
race = "dragon"
rank = 7
pendulum-scale = 0
atk = 3000
def = 2500
pendulum-effect = """\
"""
effect = """\
2 Level 7 monsters, including 1 "Odd-Eyes" Dragon Pendulum Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Xyz Summoned, and can then be Pendulum Summoned. \
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = []

[card.supreme-soul]
id = 950000005
name = "Supreme Soul"
type = "spell link"
link-rating = 3
link-arrows = "top-left top top-right"
effect = """\
When this card is activated: Place in your Pendulum Zone 2 "Magician" Pendulum Monsters with different names from your hand, Deck, and/or GY, \
Other face-up Spells/Traps you control cannot be destroyed by your opponent's card effects. \
Your opponent's cannot target monsters this card points to with card effects. \
Once per turn, you can banish 4 monsters from your hand, field, GY and/or Extra Deck face-up (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
    Neither player can activate cards or effects in response to this card's activation. \
You can only use each of the following effects of "Supreme Soul" twice per turn.
● Target 1 card in your Pendulum Zone; Special Summon it, ignoring its Summoning conditions.
● Target 1 Pendulum Monster in your Monster Zone; place that Pendulum Monster in your Pendulum Zone.

[ \
Add from Outside "Supreme Dragon" versions of your Four Dimension Dragons to your Extra Deck. \
] \
"""
strings = [
    "Summon Z-ARC",
    "Special Summon monster from Pendulum Zone",
    "Place monster in Pendulum Zone",
]
