[card.supreme-gate]
id = 450000000
name = "Supreme Gate"
type = "spell field"
effect = """\
"""
strings = []

[card.soul-supreme-dragon]
id = 450000001
name = "Soul of Supreme Dragon"
type = "spell link"
link-rating = 3
link-arrows = "top-left top top-right"
effect = """\
"""
strings = []
