[card.supreme-gate]
id = 950000000
name = "Supreme Gate"
type = "spell field"
effect = """\
Your opponent cannot target cards in your Pendulum Zones with card effects. \
Any your Pendulum Monster sent to the GY is add to the Extra Deck face-up. \
You can target 1 other face-up card you control; destroy it, and if you do, add from your Deck, GY or Extra Deck to your hand, \
    1 "Supreme King Dragon" monster, "Supreme King Gate" monster, "Pendulum" Spell/Trap \
    or card that specifically lists "Supreme King Z-ARC" in its text, except the destroyed card and "Supreme Gateway". \
    You can only use this effect of "Supreme Gate" once per turn. \
If you Special Summon any of these monsters using a Pendulum Monster(s) as material: You can activate the appropriate effect. \
    You cannot apply that same effect of "Supreme Gate" for the rest of this turn (even if this card leaves the field).
● Fusion: Special Summon 1 monster from your Deck or GY with the same original Level as that Fusion Monster, in Defense Position, but it cannot activate its effects this turn.
● Synchro: Add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand.
● Xyz: Take 1 Tuner from your Deck or GY with an equal or lower Level than that Xyz Monster's Rank, and add it to your hand or Special Summon it in Defense Position.
"""
strings = [
    "Search & add card",
    "Special Summon a monster with same Level",
    "Add \"Fusion\" Spell",
    "Add or Special Summon a Tuner",
]

[card.supreme-king-zarc]
id = 950000001
alias = 13331639
set = "supreme-king"
name = "Supreme King Z-ARC - Overlord"
type = "monster effect link pendulum"
attribute = "dark"
race = "dragon"
pendulum-scale = 13
link-rating = 4
link-arrows = "top bottom-left bottom bottom-right"
atk = 4000
pendulum-effect = """\
Unaffected by your opponent's card effects. \
Pendulum Scale of card in your other Pendulum Zone become 0. \
Fusion, Synchro, and Xyz Monsters your opponent controls cannot activate their effects. \
Once per turn, if you have no cards in your other Pendulum Zone: You can place 1 Pendulum Monster from your Deck, GY or Extra Deck face-up in your Pendulum Zone. \
"""
effect = """\
4 Dragon monsters (1 Fusion, 1 Synchro, 1 Xyz, and 1 Pendulum)
(This card is always treated as "Supreme King Z-ARC".)
Must be Link Summoned. \
This card's Special Summon cannot be negated. \
This card's activation and effects cannot be negated. \
Your opponent cannot target this card with card effects. \
Cannot be destroyed by card effects. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Possession of this card cannot be switched. \
If this card is Special Summoned: Destroy all cards your opponent controls. \
Once per turn, when a card(s) is added to your opponent's hand (except during the Draw Phase or the Damage Step): \
    You can destroy that card(s). \
Once per turn, you can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck, \
    ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
    This card cannot declare an attack the turn this effect is activated. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Place pendulum monster",
    "Negate effect and destroy all card",
    "Destroy added cards",
    "Summon a Dragon",
]

[card.odd-eyes-venom-dragon]
id = 950000002
set = "odd-eyes venom supreme-king-dragon"
name = "Odd-Eyes Venom Dragon - Overlord"
type = "monster effect fusion pendulum"
attribute = "dark"
race = "dragon"
level = 9
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Once per turn, during the Standby Phase: Place 1 Venemy Counter on each face-up monster your opponent controls. \
Once per turn, if a monster you control battles an opponent's monster, before damage calculation: \
    You can make that monster you control gains 500 ATK for each Venemy Counter on the field until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Monster + 1 "Starving Venom" Fusion Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Fusion Summoned with above materials on the field, and can then be Pendulum Summoned. \
If this card is Fusion Summoned: \
    This card gain ATK equal to the combined ATK of all monsters your opponent currently controls, until the end of this turn. \
All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. \
Each time a card(s) is sent from the field to the GY, place 1 Venemy Counter on this card for each sent card. \
Once per turn (Qick Effect): You can target 1 face-up monster your opponent controls or in their GY; until the End Phase, \
    that monster has its effects negated, and also, this card gains its effects and its original ATK. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Place Venemy Counter",
    "Make 1 monster gain ATK up by Venemy Counter",
    "Negate effect & gain effect, ATK of a monster",
]

[card.odd-eyes-wing-dragon]
id = 950000003
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Wing Dragon - Overlord"
type = "monster effect synchro pendulum"
attribute = "dark"
race = "dragon"
level = 8
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, if your monster battles an opponent's monster, before damage calculation: \
    You can make that monster you control gain ATK equal to the current ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
1 "Odd-Eyes" Dragon Pendulum Tuner + 1 non-Tuner "Clear Wing" Synchro Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Synchro Summoned, and can then be Pendulum Summoned. \
If this card Is Synchro Summoned: \
    Negate the effects of all monsters your opponent currently controls, until the end of this turn. \
Once per turn, at the start of the Damage Step, if this card battles an opponent's monster: \
    You can destroy that opponent's monster, and if you do this card gains ATK equal to the destroyed monster's original ATK until the end of this turn, \
    also, this card can make a second attack in a row. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; until the end of this turn, \
    that monster has its effects negated, and also change its ATK to 0. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Gain ATK of battling monster's ATK",
    "Destroy battling monster",
    "Negate effect & down attack of a monster",
]

[card.odd-eyes-raging-dragon]
id = 950000004
set = "odd-eyes supreme-king-dragon"
name = "Odd-Eyes Raging Dragon - Overlord"
type = "monster effect xyz pendulum"
attribute = "dark"
race = "dragon"
rank = 7
pendulum-scale = 10
atk = 3000
def = 2500
pendulum-effect = """\
Once per turn, at the end of the Damage Step, if your monster attacked an opponent's monster: \
    You can halve the ATK of the opponent's monster it is battling until the end of the Damage Step. \
"""
effect = """\
2+ Level 7 monsters, including 1 "Odd-Eyes" Dragon Pendulum Monster and 1 "Rebellion" Xyz Monster
(This card is always treated as "Supreme King Dragon" card.)
Must be Xyz Summoned, and can then be Pendulum Summoned. \
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. \
If this card Is Xyz Summoned: \
    This turn, it can make a second and third attack during each Battle Phase. \
Once per turn, you can can detach any number of materials from this card, then destroy that many card your opponent controls. \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; until the end of this turn, \
    that monster has its effects negated, and also its ATK becomes half its current ATK, and if it does, this card gains that lost ATK. \
If this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. \
"""
strings = [
    "Halve ATK of battling monster",
    "Can make 3 attacks",
    "Destroy card on the field",
    "Negate effect & halve ATK of a monster",
]

[card.supreme-soul]
id = 950000005
name = "Supreme Soul"
type = "spell link"
link-rating = 3
link-arrows = "top-left top top-right"
effect = """\
This card's activation and effect cannot be negated. \
When this card is activated: \
    Place in your Pendulum Zone 2 "Supreme King Dragon", "Supreme King Gate" Pendulum Monsters with different names \
    from your hand, Deck, GY and/or Extra Deck face-up, \
    and if you do, you can add to you hand from your Deck, GY or Extra Deck face-up, \
    1 "Supreme King Dragon" monster that have Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones. \
Face-up Spells/Traps you control cannot be destroyed by your opponent's card effects. \
Your opponent's cannot target monsters this card points to with card effects. \
Once per turn, you can banish 4 monsters from your hand, field, GY and/or Extra Deck face-up (1 each with "Pendulum Dragon", "Xyz Dragon", "Synchro Dragon", and "Fusion Dragon" in their names); \
    Special Summon 1 "Supreme King Z-ARC" from your Extra Deck, ignoring its Summoning conditions. (This is treated as a Properly Summon.) \
You can only use each of the following effects of "Supreme Soul" twice per turn.
● Target 1 card in your Pendulum Zone; Special Summon it, ignoring its Summoning conditions.
● Target 1 Pendulum Monster in your Monster Zone; place that Pendulum Monster in your Pendulum Zone.

[ \
Add from Outside "Supreme Dragon" versions of your Four Dimension Dragons to your Extra Deck. \
] \
"""
strings = [
    "Add 1 \"Supreme King Dragon\" to your hand",
    "Summon Z-ARC",
    "Special Summon monster from Pendulum Zone",
    "Place monster in Pendulum Zone",
]

[card.supreme-king-dragon-oddwurm]
id = 950000006
set = "supreme-king-dragon odd-eyes"
name = "Supreme King Dragon Oddwurm"
type = "monster effect"
attribute = "dark"
race = "dragon"
level = 7
atk = 2500
def = 2000
effect = """\
(This card is always treated as "Odd-Eyes" card.)
If this card's Level between (exclusive) the Pendulum Scales of the cards in your Pendulum Zones: \
    You can Special Summon this card from your hand or GY. \
    You can only Special Summon "Supreme King Dragon Oddwurm" once per turn this way. \
If this card is Normal or Special Summoned: \
    You can add 1 "Odd-Eyes" Dragon Pendulum Monster from your Deck or GY to your Extra Deck face-up, \
    then you can add 1 "Spiral Flame Strike" from your Deck or GY to your hand. \
If this card is destroyed by battle or card effect: \
    You can Special Summon 1 "Supreme King Dragon" monster from your hand, Deck, GY or Extra Deck face-up, \
    except "Supreme King Dragon Oddwurm". \
    You can only use each effect of "Supreme King Dragon Oddwurm" once per turn. \
"""
strings = [
    "Add 1 \"Odd-Eyes\" Dragon Pendulum Monster to Extra Deck",
    "Add 1 \"Spiral Flame Strike\" to your hand",
]

[card.supreme-king-dragon-venowurm]
id = 950000007
set = "supreme-king-dragon"
name = "Supreme King Dragon Venowurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 5
atk = 1500
def = 1000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[card.supreme-king-dragon-wingwurm]
id = 950000008
set = "supreme-king-dragon"
name = "Supreme King Dragon Wingwurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 5
atk = 1500
def = 1000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[card.supreme-king-dragon-rebelliwurm]
id = 950000009
set = "supreme-king-dragon"
name = "Supreme King Dragon Rebelliwurm"
type = "monster pendulum effect"
attribute = "dark"
race = "dragon"
level = 4
pendulum-scale = 5
atk = 1500
def = 1000
pendulum-effect = """\
"""
effect = """\
"""
strings = []

[card.supreme-wrath]
id = 950000010
name = "Supreme Wrath"
type = "trap"
effect = """\
While this card is in your GY, you can target 1 "Supreme King Dragon" Xyz Monster you control; \
    attach up to 2 "Supreme King Dragon" monsters to it as materials, from your GY and/or face-up from your Extra Deck. \
    You can only use this effect of "Supreme Wrath" once per turn. \
Activate 1 of these effects. You can only activate 1 "Supreme Wrath" once per turn.
● Immediately after this effect resolves, Pendulum Summon a monster(s).
● Destroy as many cards in the Pendulum Zones as possible (min 2.), then activate 1 "Supreme Soul" directly from your hand, Deck, or GY.
● If you control "Supreme King Z-ARC": Destroy as many monsters you control as possible, except "Supreme King Z-ARC", \
    and if you do, Special Summon up to 4 "Supreme King Dragon" monsters with different names from your hand, Deck, Extra Deck, and/or GY, \
    ignoring their Summoning conditions. (This is treated as a Properly Summon.)
"""
strings = [
    "Pendulum Summon",
    "Activate \"Supreme Soul\"",
    "Special Summon a dragon(s)",
]
