[card.the-last-hope-remain]
id = 940000000
name = "The Last Hope Remain"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
"Astral", "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster you control can be treated as 2 monsters when used for an Xyz Summon. \
Your opponent cannot activate cards or effects in response to the activation of your cards and effects that target an Xyz Monster(s) you control. \
If an Xyz Monster(s) is Special Summoned to your field, you can attach 1 Xyz Monster from your Extra Deck or GY to 1 of them as material. \
Once per turn, during your Draw Phase, instead of conducting your normal draw: \
    You can add 1 "Rank-Up-Magic" or "Rank-Down-Magic" Spell from your Deck to your hand. \
You can shuffle into your Deck, 1 "Double or Nothing" or "ZW -", "ZS -", "Zexal", "Number" card that is banished or in your hand or GY, \
    and if you do, you can add to your hand 1 "Astral", "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster from your Deck or GY. \
    You can only use this effects of "The Last Hope Remain" once per turn.

[ \
Add from Outside all "ZEXAL", "ZW -" and "ZS -" Xyz monsters. \
] \
"""
strings = [
    "Attach Xyz Monster as material",
    "Add 1 \"Rank-Up-Magic\" or \"Rank-Down-Magic\" Spell",
    "Shuffle card into the Deck",
]

[card.rank-change-magic-numeron-force]
id = 940000001
set = "numeron rank-down-magic rank-up-magic"
name = "Rank-Change-Magic Numeron Force"
type = "spell quick-play"
effect = """\
(This card is always treated as a "Rank-Up-Magic" and "Rank-Down-Magic" card.)
During the Main Phase: Target 1 Xyz Monster you control; Special Summon from your Extra Deck, \
    1 "Number" monster with the same Type that has a number between "1" and "99" and is 1 to 3 Rank higher/lower than that monster, \
    by using it as material. (This is treated as an Xyz Summon. Transfer its materials to the Summoned monster.) \
    The monster Xyz Summoned by this effect gains this effect.
● Your opponent cannot target this card with card effects.
If this card is in your GY: You can shuffle it into the Deck, \
    then, you can add 1 "ZEXAL Construction" from your Deck or GY to your hand. \
    You can only use this effect of "Rank-Change-Magic Numeron Force" once per turn.

[ \
Add from Outside all Rank-Changed versions of your "Number" Xyz monsters. \
] \
"""
strings = ["Add \"ZEXAL Construction\""]

[card.genesis-numeron-dragon]
id = 940000002
set = "number numeron"
name = "Number 100: Genesis Numeron Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 1
atk = 0
def = 0
effect = """\
5 "Number" Xyz Monsters with the same Rank
You can also Xyz Summon this card by discarding 1 "Rank-Up-Magic" Spell Card, \
    then using 1 "Number 100: Numeron Dragon" you control as the Xyz Material. \
    (Transfer its Xyz Materials to this card.) \
Must be Special Summoned by its own effect. \
This card's Special Summon, activation and effects cannot be negated. \
Possession of this card cannot be switched. \
Cannot be flipped face-down. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
This card gains the effects of all "Number" Xyz Monsters attached to it, except "Number 100: Genesis Numeron Dragon". \
Once per turn (Quick Effect): You can target 1 face-up card you control or is banished; attach it and its materials to this card as material. \
Once per turn: You can target 1 "Number" Xyz Monster in your GY, except "Number 100: Genesis Numeron Dragon"; \
    Special Summon it, ignoring its Summoning conditions and rule (This is treated as an Xyz Summon.) \
"""
strings = [
    "Xyz Summon by discarding 1 \"Rank-Up-Magic\" Spell",
    "Attach material",
    "Special Summon \"Number\" Xyz Monster in GY",
]

[card.utopia-beyond-the-shining]
id = 940000003
set = "number-c39 utopia chaos"
name = "Number S39: Utopia Beyond the Shining"
type = "monster xyz effect"
attribute = "light"
race = "warrior"
rank = 8
atk = 3500
def = 3000
effect = """\
3 Level 8 LIGHT monsters
(This card is always treated as a "Number C39" card.)
Must be Xyz Summoned. \
This card's Xyz Summon cannot be negated. \
When Xyz Summoned, your opponent's cards and effects cannot be activated. \
Once per turn (Quick Effect): You can equip 1 "ZW -" monster from your Deck, GY or Extra Deck to this card, \
    as if it were equipped by its own effect. This activation and effect cannot be negated. \
If this card has "Number 39: Utopia Beyond" as an Xyz Material, it gains this effect.
● "Number" Xyz Monster you control are unaffected by your opponent's card effects.
"""
strings = ["Equip 1 \"ZW -\" monster"]
