[card.the-last-hope]
id = 940000000
name = "The Last Hope"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
Your "Astral", "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster can be treated as 2 monsters when used for an Xyz Summon. \
Your opponent cannot activate cards or effects in response to the activation of your cards and effects that target an Xyz Monster(s) you control. \
If an Xyz Monster(s) is Special Summoned to your field: You can attach 1 Xyz Monster from your Extra Deck or GY to it as material. \
You can only use each of the following effects of "The Last Hope" once per turn.
● During your Draw Phase, instead of conducting your normal draw: \
    You can add 1 "Rank-Up-Magic" or "Rank-Down-Magic" Spell from your Deck or GY to your hand.
● You can shuffle 1 "Double or Nothing" or "ZW -", "ZS -", "Zexal" card in your hand or GY into your Deck; \
    and if you do, you can add to your hand 1 "Astral", "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster from your Deck or GY.

[ \
Add from Outside all "ZW -" and "ZS -" Xyz monsters. \
] \
"""
strings = [
    "Attach Xyz Monster as material",
    "Add 1 \"Rank-Up-Magic\" or \"Rank-Down-Magic\" Spell",
    "Shuffle card into the Deck",
]

[card.rank-change-magic-numeron-force]
id = 940000001
set = "numeron rank-down-magic rank-up-magic"
name = "Rank-Change-Magic Numeron Force"
type = "spell quick-play"
effect = """\
(This card is always treated as a "Rank-Up-Magic" and "Rank-Down-Magic" card.)
During the Main Phase: Target 1 Xyz Monster you control; Special Summon from your Extra Deck, \
    1 "Number" monster that has a number between "1" and "99" and is 1, 2, 3 Rank higher or lower than that monster you control, \
    by using it as material. (This is treated as an Xyz Summon. Transfer its materials to the Summoned monster.) \
If this card is in your GY: You can draw 1 card, and if you do, shuffle this card into the Deck. \
    You can only use this effect of "Rank-Change-Magic Numeron Force" once per turn.

[ \
Add from Outside all Rank-Changed versions of your "Number" Xyz monsters. \
] \
"""
strings = []

[card.number-100]
id = 940000002
set = "number numeron"
name = "Number 100: Genesis Numeron Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 0
atk = "?"
def = "?"
effect = """\
5 "Number" Xyz Monsters with the same Rank
This card's Special Summon, activation and effects cannot be negated. \
Possession of this card cannot be switched. \
Cannot be flipped face-down. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
This card gains the effects of all "Number" Xyz Monsters attached to it, except "Number 100: Genesis Numeron Dragon". \
"""
strings = []
