[card.the-last-hope]
id = 940000000
name = "The Last Hope Remain"
type = "spell field"
effect = """\
This card's activation and effect cannot be negated. \
If your "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster is used as an material for an Xyz Summon, you can treat it as 2 monsters. \
Your opponent cannot activate cards or effects in response to the activation of your cards and effects that target an Xyz Monster(s) you control. \
During your Draw Phase, instead of conducting your normal draw: \
    You can add 1 "Rank-Up-Magic" or "Rank-Down-Magic" Spell from your Deck or GY to your hand. \
Once per turn: You can shuffle 1 "Double or Nothing" or "ZW -", "ZS -", "Zexal" card in your hand or GY into your Deck; \
    and if you do, you can add to your hand 1 "Zubaba", "Gagaga", "Gogogo", and "Dododo" monster from your Deck or GY. \
You can only use each effect of "The Last Hope Remain" once per turn.

[ \
Add from Outside all "ZW -" and "ZS -" Xyz monsters. \
] \
"""
strings = [
    "Add 1 \"Rank-Up-Magic\" or \"Rank-Down-Magic\" Spell",
    "Shuffle card into the Deck",
]

[card.rank-change-magic-emperor-force]
id = 940000001
set = "rank-down-magic rank-up-magic"
name = "Rank-Change-Magic Emperor Force"
type = "spell"
effect = """\
(This card is always treated as a "Rank-Up-Magic" and "Rank-Down-Magic" card.)

[ \
Add from Outside all Rank-Changed versions of your "Number" Xyz monsters. \
] \
"""
strings = []

[card.number-100]
id = 940000002
name = "Number 100: Genesis Numeron Dragon"
type = "monster xyz effect"
attribute = "light"
race = "dragon"
rank = 0
atk = "?"
def = "?"
effect = """\
"""
strings = []
