[card.dreadroot]
id = 410000006
alias = 62180201
name = "Dreadroot the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Dreadroot}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
Halve the ATK and DEF of all your opponent's monsters on the field. \
If this card attacks a Defense Position monster, inflict piercing battle damage.\
"""
strings = [
]

[card.eraser]
id = 410000007
alias = 57793869
name = "Eraser the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Eraser}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
The original ATK/DEF of this card each become equal to the number of cards your opponent controls x 1000. \
If this card leaves the field: Send all cards your opponent controls to the GY.\
"""
strings = [
]

[card.avatar]
id = 410000008
alias = 21208154
name = "Avatar the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Wicked Avatar}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
The original and final ATK/DEF of this card are each 100 points higher than the highest face-up monster's ATK on the field, \
    except "The Wicked Avatar" and monsters with higher Divine Hierarchy. \
If this card battles, your opponent cannot activate cards or effects until the end of the Damage Step, \
    except card with higher Divine Hierarchy. \
"""
strings = [
]

[card.zorc]
id = 410000009
name = "Zorc Necrophades the Creator of Shadow Realm"
type = "monster effect xyz"
attribute = "divine"
race = "creator-god"
level = 12
atk = "?"
def = "?"
effect = """\
3+ DARK Divine-Beast monsters with same Level and different names
${HIERARCHY|3}
Must be Xyz Summoned and cannot be Special Summoned by other cards' effects. \
${GOD_IMMUNITY} \
This card is also a DARK Fiend monster while face-up on the field. \
This card gains the effects of all monsters attached to it, except original Creator-God monsters.\
"""
strings = [
]