[card.dreadroot]
id = 410000006
alias = 62180201
name = "Dreadroot the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = 4000
def = 4000
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Dreadroot}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
Halve the ATK and DEF of all your opponent's monsters on the field. \
If this card attacks a Defense Position monster, inflict piercing battle damage.\
"""
strings = [
]

[card.eraser]
id = 410000007
alias = 57793869
name = "Eraser the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|1|The Wicked Eraser}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
The original ATK/DEF of this card each become equal to the number of cards your opponent controls x 1000. \
If this card leaves the field: Send all monsters your opponent controls to the GY.\
"""
strings = [
]

[card.avatar]
id = 410000008
alias = 21208154
name = "Avatar the Wicked God"
type = "monster effect"
attribute = "divine"
race = "divine-beast"
level = 10
atk = "?"
def = "?"
effect = """\
${HIERARCHY_ALIAS|2|The Wicked Avatar}
${WICKED_SUMMON} \
${DIVINE_IMMUNITY} \
${TO_GRAVE_LIMIT} \
This card is also a DARK Fiend monster while face-up on the field. \
The original and final ATK/DEF of this card are each 100 points higher than the highest face-up monster's ATK on the field (except "The Wicked Avatar").
"""
strings = [
]

[card.zorc]
id = 410000009
name = "Zorc Necrophades the Creator of Shadow Realm"
type = "monster effect xyz"
attribute = "divine"
race = "creator-god"
level = 12
atk = 5000
def = 5000
effect = """\
3 DARK Divine-Beast monsters with the same Level and different names
${HIERARCHY|3}
This card's activation and effects cannot be negated. \
Cannot be Tributed, or be used as a material for a Summon by your opponent. \
Cannot be flipped face-down. \
Control of this card cannot be switched. \
Unaffected by other cards' effects, except cards' effects with the same or higher Divine Hierarchy. \
Cannot be destroyed by battle with a monster with have no or lower Divine Hierarchy, also you take no Battle Damage from that battle. \
This card is also a DARK Fiend monster while face-up on the field.\
"""
strings = [
]