[armityle]
id = 900002000
alias = 43378048
rarity = "gold"
name = "Armityle, the Chaos Phantasm Ruler"
type = "monster fusion effect"
attribute = "divine"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Armityle the Chaos Phantasm".)
"""
strings = []
