[raviel]
id = 900002001
alias = 69890967
rarity = "gold"
frame-path = "frame/raviel.png"
name = "Raviel, Ruler of Phantasms Demons"
type = "monster effect"
attribute = "divine"
race = "fiend"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Raviel, Lord of Phantasms".)
Cannot be Normal Summoned/Set. \
Must be Special Summoned (from your hand) by Tributing 3 monsters. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Negate the effects of your opponent's monsters destroyed by battle with this card. \
The above effects cannot be negated. \
Each time your opponent Normal or Special Summons a monster(s), \
    Special Summon 1 "Phantasm Token" (Fiend/DARK/Level 1/ATK 1000/DEF 1000), \
    but it cannot declare an attack. \
Once per turn: You can Tribute up to 2 monsters; \
    this card gains ATK equal to the Tributed monsters' combined ATK had on the field, \
    until the end of this turn. \
"""
strings = [
    "Special Summon a \"Phantasm Token\"",
    "Tribute up to 2 monsters to gain ATK",
]

[uria]
id = 900002002
alias = 6007213
rarity = "gold"
frame-path = "frame/uria.png"
name = "Uria, Ruler of Searing Flames"
type = "monster effect"
attribute = "divine"
race = "pyro"
level = 10
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Uria, Lord of Searing Flames".)
Cannot be Normal Summoned/Set. \
Must be Special Summoned (from your hand) by sending 3 Traps you control to the GY. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
Gains 1000 ATK/DEF for each Trap in your GY. \
The above effects cannot be negated. \
Once per turn: You can target 1 Set Spell/Trap your opponent controls; destroy it. \
    Neither player can activate Spell/Trap Cards in response to this effect's activation. \
"""
strings = ["Destroy 1 Set Spell/Trap"]

[hamon]
id = 900002003
alias = 32491822
rarity = "gold"
frame-path = "frame/hamon.png"
name = "Hamon, Ruler of Striking Thunder"
type = "monster effect"
attribute = "divine"
race = "thunder"
level = 10
atk = 4000
def = 4000
effect = """\
(This card's name is always treated as "Hamon, Lord of Striking Thunder".)
Cannot be Normal Summoned/Set. \
Must be Special Summoned (from your hand) by sending 3 Spells you control to the GY. \
This card's Special Summon cannot be negated. \
Control of it cannot switch. \
Cannot be Tributed, or used as material for an Summon by your opponent. \
While this card is in face-up Defense Position, \
    monsters your opponent controls cannot target monsters for attacks, except this one. \
The above effects cannot be negated. \
If this card destroys an opponent's monster by battle: \
    Inflict 1000 damage to your opponent. \
"""
strings = ["Inflict 1000 damage to your opponent"]

[armityle]
id = 900002004
alias = 43378048
rarity = "gold"
name = "Armityle, the Chaos Phantasm Emperor"
type = "monster fusion effect"
attribute = "divine"
race = "fiend"
level = 12
atk = 0
def = 0
effect = """\
(This card's name is always treated as "Armityle the Chaos Phantasm".)
"""
strings = []
